### PR TITLE
lantiq: Fix buttons for ARV752DPW

### PR DESCRIPTION
**Pull request by FooDeas**
- set correct GPIOs for buttons
- set correct input event codes
- include corresponding headers and use macros

The changes have been tested successfully.

Signed-off-by: Andreas Eberlein <foodeas@aeberlein.de>

### CODE REVIEW

**Comment by blogic** [comment]
lgtm, we should do the sanity thing globally for lantiq dts files

**Comment by mkresin** [comment]
Yeah, I've assigned the ticket to me to do the sanity thingy for the remaining boards.

**Comment by FooDeas** [comment]
Okay. And what happens with my PR now?

**Comment by mkresin** [comment]
Your patch as accepted.

I've added your patches to my [staging tree](https://git.lede-project.org/?p=lede/mkresin/staging.git;a=summary). I've modified the remaining device tree source files already, but the device tree macros can only be used with boards already migrated to the new image build code. I'm working at the moment to bring the last two boards to the new build code.

Please do have a little patience until I'm finished. I will commit all changes at once to not touch the same files twice.

**Comment by FooDeas** [comment]
Thanks for answer! I am pleased to see that improvements are actually taken into account here.
If I can support you, just let me know.

**Comment by mkresin** [comment]
Finally merged. Thanks a lot!

**Pull request closed without merging**
