### PR TITLE
17.01: mwlwifi: update driver to 2017-08-10

### PR DESCRIPTION
**Pull request by hnyman**
Backport the update to version 10.3.4.0-20170810 from LEDE master, where this 2017-08-10 version has been for the last month since #1288

I did not include the recent firmware blob update that is present in kaloz/mwlwifi, as that has not been included in the master, yet.

Run-tested with WRT3200ACM running 17.01-SNAPSHOT r3560-79f57e422d

@stintel 
@anomeome

### CODE REVIEW

**Comment by anomeome** [comment]
I have been running with the updated BLOB on a rango for close to a month now, and it seems fine. As far as I can tell, @yuhhaurlin has adopted the convention of stamping with a version number when things are considered _ready for prime time_, so I don't think it should find it's way into stable until that happens.

**Comment by WildByDesign** [comment]
I have been running the latest mwlwifi kernel driver (10.3.4.0-20170810) for approx. 46 days on WRT3200ACM device on trunk builds and also a user backported package for stable branch LEDE with much better stability and also utilizing multiple SSID's.

I have been running the latest firmware (9.3.0.8) for WRT3200ACM for approx. 22 days now, also with great stability and reliable uptime. This home network consists of a good mix of laptops, multiple iPhones and iPads.

Please consider this pull request for stable branch 17.01.4 release since the current driver is quite outdated and has significant stability issues.

**Comment by neheb** [comment]
+1

**Comment by stintel** [comment]
Sorry, 17.01.4 was tagged without update to mwlwifi. Please request a backport of these changes on the mailinglist, so people can comment on it there as well.

**Comment by hnyman** [comment]
> Whenever possible, cherry-pick is preferred, so this PR will probably not be accepted/merged as we do for master.

Well, the PR commit produces identical Makefile as is in the master currently and the package has no other files, so in practice it is a cherry-pick, but commit message does not contain a line about a cherry-pick. Instead, I wrote "backport" there.

**Comment by stintel** [comment]
We'd still have to review it. With a clean cherry-pick we can assume it's the same as in master. It was announced on the mailing-list that this is preferred over sending patches for it. While that mail did not mention Github and PRs, we prefer cherry-pick over PR the same way.

**Pull request closed without merging**
