### PR TITLE
ar71xx: add support to TP-Link MR6400 v2

### PR DESCRIPTION
**Pull request by heinzek**
TP-Link TL-MR6400 v2 is a router based on Qualcomm/Atheros QCA9531
with build in 3G/LTE modem.

Specification:

- 650/390/216 MHz (CPU/DDR/AHB)
- 64 MB of RAM (DDR)
- 8 MB of FLASH (SPI NOR)
- 2T2R 2.4 GHz
- 4x 10/100 Mbps Ethernet
- 6x LED, 2x button
- UART header on PCB

Currently not working:
- Update from oficial web interface

Flash instruction:
1. Set PC to fixed ip address 192.168.0.66
2. Download lede-ar71xx-generic-tl-mr6400-v2-squashfs-factory.bin
and rename it to mr6400_tp_recovery.bin
3. Start a tftp server with the file mr6400_tp_recovery.bin in its root directory
4. Turn off the router
5. Press and hold Reset button
6. Turn on router with the reset button pressed and wait ~15 seconds
7. Release the reset button and after a short time
the firmware should be transferred from the tftp server
8. Wait ~40 second to complete recovery.

Flash instruction under U-Boot, using UART:

1. tftp 0x81000000 lede-ar71xx-...-sysupgrade.bin
2. erase 0x9f020000 +$filesize
3. cp.b $fileaddr 0x9f020000 $filesize
4. reset

~~Second commit add the TP-Link LTE Module ID to the usb-serial option driver.~~
TP-Link LTE module is now supported.

Third commit remove unneeded option ID from adb-enablemodem script,
because TP-Link LTE Module is supported by option driver.

### CODE REVIEW

**Comment by psyborg55** [comment]
do you know the gpio/buttons configuration to include it in mach file too?

**Comment by blogic** [comment]
@heinzek 
2/3 - the patches should be annotated git style. can you please also send the patch upstream
3/3 - the explaination of why the lines should be removed is missing.

**Comment by heinzek** [comment]
Patch is sended and accepted:
https://git.kernel.org/pub/scm/linux/kernel/git/johan/usb-serial.git/commit/?h=usb-linus&id=837ddc4793a69b256ac5e781a5e729b448a8d983

3/3 - commit message fixed.

**Comment by heinzek** [comment]
Fixed

**Comment by pepe2k** [comment]
@heinzek,

Is there really a reason to have separate board (and machine) names per version 1 and 2 of this model? As far as I can see, both versions are (from h/w point of view) a 1:1 copies and differ only in LTE module installed inside (which results also in different set of packages). They even share the same TP-Link HWID...

What about just separate images, with different set of packages or even one image which covers both models? Thus, instead of having `tl-mr6400` and `tl-mr6400-v2`, keep just first one and also get rid of `ATH79_MACH_TL_MR6400_V2`. What do you think?

Cheers,
Piotr

**Comment by heinzek** [comment]
@pepe2k I think you're right. I tried mr6400v1 image on mr6400v2 router and it works OK.
Can i close this PR and open new to remove unneeded option ID? or remove only first commit?

**Comment by pepe2k** [comment]
> @pepe2k I think you're right. I tried mr6400v1 image on mr6400v2 router and it works OK.
> Can i close this PR and open new to remove unneeded option ID? or remove only first commit?

I will take care of this, please don't close it.

Cheers,
Piotr

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Pull request closed without merging**
