### PR TITLE
mwlwifi: update to last commit

### PR DESCRIPTION
**Pull request by Ansuel**
Switch to marvel testing repo, update to last driver... Better wifi stability for wrt3200 router

Compiled and Tested wrt1900acs

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by wongsyrone** [comment]
It's still under debugging. No hurry.

**Comment by thagabe** [comment]
Wrong move, right now marveltesting is just that a repo for testing not stable. No go from me.

Just my 2 cents,
-Gabe

**Comment by Ansuel** [comment]
So do you think that the main driver will be updated soon ? 
i'm using it right now and i can't see any problem... 
I mean these changes will not be pushed on the stable code so... we can take these kind of testing driver

**Comment by borkra** [comment]
Sorry, which "main" driver? Marvell just moved from OpenWRT maintainer hosted project/repository to their own (took them long enough). Nothing else changes, it still hosts code drops from Marvell FullMAC driver development team.

The new driver seems snappier...

**Comment by Ansuel** [comment]
There are 2 repo for mwlwifi testing and the one that we are using now... 
I think that the changes to te testing repo will be merged to the stable one right?

**Comment by borkra** [comment]
There is no testing and stable, stable releases are for paying customers, and Lede is not one of those. 

It looks like Marvell moved all their code drops to the mrvltest. What will happen to kalosz repository your guess is as good as mine.

**Comment by Ansuel** [comment]
@borkra so you think that the kalosz repo won't be updated anymore? (could be, cause in the new repo we have an increse of version... if it's just for testing, then why create commit to update version?) Then i think this PR is right...

**Comment by borkra** [comment]
I have the same estimation about kalosz repository.

And BTW, what is released in all these repositories is Marvell code drops for Open Source, it's not everything they have and not where development happens.

**Comment by Ansuel** [comment]
ok now i need some help...
I also find THIS https://github.com/yuhhaurlin/mwlwifi
It have different commit (really different commit) and an upgraded driver o.O 

Can't underestand nothing....

**Comment by anomeome** [comment]
My understanding was [this](https://forum.lede-project.org/t/secret-wifi-driver-for-wrt3200acm/2718/6) Regardless you need to update hash

**Comment by diizzyy** [comment]
It's a no go unless it magically fixes WRT3200ACM wifi which it doesn't atm.

**Comment by Ansuel** [comment]
What are the problem with wrt3200?

**Comment by heinzek** [comment]
Tested this with WRT3200ACM and wifi is "not working".
+ wifi leds are on when connect device to network, but there is no transfer to router.

**Comment by Ansuel** [comment]
@heinzek did you try the other driver? this? https://github.com/yuhhaurlin/mwlwifi

**Comment by heinzek** [comment]
Yes. This has the same problems. 

Tested firmware from first post:
https://forum.lede-project.org/t/secret-wifi-driver-for-wrt3200acm/2718

WiFi speed ~360Mbit/s looks good but i dont trust "Chinese" firmware.

**Comment by hnyman** [comment]
They have now (finally) updated the Kaloz repo with the 20170421 driver that is still "Pre-QA". So no reason to switch repos.

And in any case, you should not drop the PKG_MIRROR_HASH. Just calculate the hash yourself after the first download and update hash in Makefile.

**Comment by Ansuel** [comment]
@hnyman nice! Think we can push this right?
Actually the check command was broken as in some old version it ust remove the mirror hash if it was empty (and not rewrite it with the correct one, now it's good)

**Comment by diizzyy** [comment]
@hnyman 
Which device?
On my WRT3200ACM the 11ac interface doesn't enabled at all :(

**Comment by hnyman** [comment]
> Which device?
> On my WRT3200ACM the 11ac interface doesn't enabled at all :(

My WRT3200ACM. It is the only device I have of the series.
Running the build lede-r3986-e1d433b293-20170421 , which is downloadable from my dropbox (link in the CPU freq thread):  https://www.dropbox.com/sh/sorrebbshah0pfa/AABiU6Wi_bWlIqnmwHEGEiKua?dl=0

```
root@LEDE:~# grep r3 /etc/banner
   \  DE    \  /    Reboot (SNAPSHOT, r3986-e1d433b293)
root@LEDE:~# iwinfo
mlan0     ESSID: unknown
          Access Point: 00:00:00:00:00:00
          Mode: Client  Channel: unknown (unknown)
          Tx-Power: unknown  Link Quality: unknown/70
          Signal: unknown  Noise: unknown
          Bit Rate: unknown
          Encryption: unknown
          Type: nl80211  HW Mode(s): 802.11bgnac
          Hardware: 02DF:9135 0000:0000 [Generic MAC80211]
          TX power offset: unknown
          Frequency offset: unknown
          Supports VAPs: yes  PHY name: phy2

wlan0     ESSID: "HN5WLAN"
          Access Point: 60:38:E0:BC:36:22
          Mode: Master  Channel: 36 (5.180 GHz)
          Tx-Power: 20 dBm  Link Quality: unknown/70
          Signal: unknown  Noise: unknown
          Bit Rate: 6.0 MBit/s
          Encryption: WPA2 PSK (CCMP)
          Type: nl80211  HW Mode(s): 802.11nac
          Hardware: 11AB:2B40 11AB:0000 [Generic MAC80211]
          TX power offset: unknown
          Frequency offset: unknown
          Supports VAPs: yes  PHY name: phy0

wlan1     ESSID: "HNWLAN"
          Access Point: 60:38:E0:BC:36:21
          Mode: Master  Channel: 3 (2.422 GHz)
          Tx-Power: 20 dBm  Link Quality: unknown/70
          Signal: unknown  Noise: unknown
          Bit Rate: 1.0 MBit/s
          Encryption: WPA2 PSK (CCMP)
          Type: nl80211  HW Mode(s): 802.11bgn
          Hardware: 11AB:2B40 11AB:0000 [Generic MAC80211]
          TX power offset: unknown
          Frequency offset: unknown
          Supports VAPs: yes  PHY name: phy1
```

**Comment by Ansuel** [comment]
@hnyman the driver that you are using is this or other?

**Comment by hnyman** [comment]
> the driver that you are using is this or other?

Not sure to what you refer with "this". I built my firmware using the new driver in Kaloz/mwlwifi, released today, although still being "pre-QA".

My change to the sources is visible above.
PKG_VERSION:=10.3.4.0-20170421
PKG_SOURCE_VERSION:=6ba335bb8c8abb04856003865dcd7f0d990debac

(I do not think that we should use mrvltest repo at this point.)

**Comment by Ansuel** [comment]
@hnyman yep... think we have 3 stage of develp... yuhhaurlin --> mwltest --> kaloz

**Comment by diizzyy** [comment]
```
[   18.643311] ieee80211 phy0: cmd 0x9111=SetNewStation timed out
[   18.649173] ieee80211 phy0: return code: 0x1111
[   18.653730] ieee80211 phy0: timeout: 0x1111
[   18.657929] ieee80211 phy0: failed execution
[   22.661305] ieee80211 phy0: cmd 0x801c=80211RadioControl timed out
[   22.667511] ieee80211 phy0: return code: 0x001c
[   22.672066] ieee80211 phy0: timeout: 0x001c
[   22.676264] ieee80211 phy0: failed execution
[   26.681305] ieee80211 phy0: cmd 0x8123=SetWMMMode timed out
[   26.686901] ieee80211 phy0: return code: 0x0123
[   26.691455] ieee80211 phy0: timeout: 0x0123
[   26.695654] ieee80211 phy0: failed execution
[   30.699314] ieee80211 phy0: cmd 0x8115=SetEDCAParams timed out
[   30.705176] ieee80211 phy0: return code: 0x0115
[   30.709722] ieee80211 phy0: timeout: 0x0115
[   30.713924] ieee80211 phy0: failed execution
[   34.717312] ieee80211 phy0: cmd 0x8115=SetEDCAParams timed out
[   34.723174] ieee80211 phy0: return code: 0x0115
[   34.727722] ieee80211 phy0: timeout: 0x0115
[   34.731924] ieee80211 phy0: failed execution
[   38.735309] ieee80211 phy0: cmd 0x8115=SetEDCAParams timed out
[   38.741166] ieee80211 phy0: return code: 0x0115
[   38.745720] ieee80211 phy0: timeout: 0x0115
[   38.749918] ieee80211 phy0: failed execution
[   38.754210] ieee80211 phy0: change: 0xffffffff
[   42.753307] ieee80211 phy0: cmd 0x801c=80211RadioControl timed out
[   42.759511] ieee80211 phy0: return code: 0x001c
[   42.764065] ieee80211 phy0: timeout: 0x001c
[   42.768263] ieee80211 phy0: failed execution
```

**Comment by Ansuel** [comment]
Try to reset wifi settings

**Comment by wongsyrone** [comment]
One off-topic question does anyone also come across the random crash on WRT1900AC v1 when using the 4.9.x kernel, which mentioned in https://github.com/lede-project/source/commit/047695a0294fd7046ba45e5490156c2b8e936a81. I attached USB-TTL cable; unfortunately, I cannot get any useful info from kernel log.

**Comment by Ansuel** [comment]
@wongsyrone i have wrt1900acs no reboot problem at all...

**Comment by anomeome** [comment]
Yes, [issue](https://forum.lede-project.org/t/wrt1900acv1-reboots-kernel-4-9/2025) still exists. Does the new mwlwifi work in a resonable manner?

**Comment by Ansuel** [comment]
@anomeome leds looks like to works better from what i can read...
Now i'm refreshing the kernel to the new version so... need to wait to actually build it

**Comment by anomeome** [comment]
Build r3988-f66e7cb 4.9.20 with this latest mwlwifi on rango gave a random reboot; but with current 4.9k experience on mamba maybe it's the driver, but...

**Comment by Ansuel** [comment]
Test this new version pls?

**Comment by Noltari** [comment]
NACK, this version has severe memory issues:
https://gist.github.com/Noltari/56a3ff5ca2d10f74e4afc6709aed7e23

**Comment by Ansuel** [comment]
@Noltari on shelby it's good, so revert to the old version (04-21?)

**Comment by lewisdiamond** [comment]
@Noltari Did you have this commit in your build? 
https://github.com/kaloz/mwlwifi/commit/2b7a4302ecb5fe9071aa009331386029d10deb84

**Comment by Noltari** [comment]
@lewisdiamond nope, I don't think so.
Did you check that https://github.com/kaloz/mwlwifi/commit/2b7a4302ecb5fe9071aa009331386029d10deb84 fixes all memory issues?
I read somewhere it still had high memory usage and I thought it wasn't fixed yet...

**Comment by anomeome** [comment]
Apparently the much larger footprint is to be expected due to RX buffers.

**Comment by lewisdiamond** [comment]
@Noltari I haven't even tested it yet. I'm building right now and probably not testing before later today. As @anomeome said, I hear the higher memory usage is for buffers.

**Comment by Ansuel** [comment]
Test new version ?

**Comment by Ansuel** [comment]
New version ? test ? @anomeome @Noltari @wongsyrone

**Comment by diizzyy** [comment]
...so affected devices:

WRT1200AC: Unknown
WRT1900ACv1: Unknown
WRT1900ACv2: Unknown
WRT1900ACSv1 : Unknown
WRT1900ACSv2: Unknown
WRT3200ACM: Better than before at least :-)

**Comment by wongsyrone** [comment]
working well on WRT1900ACv1

**Comment by wongsyrone** [comment]
Forgot to mention, I am testing it on 4.4.x kernel due to the random reboot on 4.9.x.

**Comment by hnyman** [comment]
@Ansuel 
You might update the PR for the newest commit from last week that fixed some issues.

Based on discussion in issues at kaloz/mwlwifi, it sounds like there may still be a memory leak and possibly also 802.11r functionality is broken at least for some routers.

**Comment by Ansuel** [comment]
@hnyman done sorry for the delay

**Comment by anomeome** [comment]
It's been stamped with a version #, she be one to take for a spin.

**Comment by wongsyrone** [comment]
Two new commits from upstream to fix memory issues.

**Comment by Ansuel** [comment]
@anomeome @wongsyrone @hnyman can you test this?

**Comment by wongsyrone** [comment]
Sorry. I tested https://github.com/kaloz/mwlwifi/commit/2d4b9bcd6c82043284fc83a3b4c92d93db39a9c1 on mamba.

**Comment by starcms** [comment]
I have tested [kaloz/mwlwifi@f8a3c79](url) (the version official tagged 10.3.40-20170512).  However, I have also tested it with its latest commit, [kaloz/mwlwifi@2b4b9bc](url).  Both run perfectly on caimen (WRT1200AC).  

However, I have heard from many rango (WRT3200ACM) owners that the commits since the official version 10.3.40-20170512 make incredible performance and reliability enhacements.

I would recommend merging the absolute latest version,  [kaloz/mwlwifi@2b4b9bc](url).  It improves greatly rango's performance; the performance of the other models are the same or marginally better (it doesn't add any new issues that were not already present in the driver version currently included in LEDE; it only has improvements)

**Comment by hnyman** [comment]
I have tested the 2d4b9bc with wrt3200acm in my own builds and have not noticed anything strange, so far.

**Comment by Ansuel** [comment]
then... should be good to upgrade right?

**Comment by nbd168** [comment]
Merged, thanks.

**Pull request closed without merging**
