### PR TITLE
ar71xx: add support for LigoWawe LigoDLB Propeller 5

### PR DESCRIPTION
**Pull request by robimarko**
LigoDLB Propeller 5 is 5 GHz AP based on Qualcomm AR9342 rev 2.
https://www.ligowave.com/products/ligodlb-propeller-5
Specifications:

560/450/225/40 MHz (CPU/DDR/AHB/REF)
64MB of RAM
16 MB of FLASH (8 MB usable because of dual image)
1x 10/100 Mbps Ethernet with 24V POE IN
6x LED, 1x button
UART header on PCB
JTAG header on PCB

Currently not working:

Update from oficial web interface
LigoWawe uses they custom app to flash images and therefore flashing LEDE images does not work.

Flash instruction:

Set PC to fixed ip address 192.168.2.254
Download lede-ar71xx-generic-dlb-5-squashfs-sysupgrade.bin and rename it to fwupdate.bin
Start a tftp server with the file fwupdate.bin in its root directory
Turn off the router
Press and hold Reset button
Turn on router with the reset button pressed and wait 6 or more seconds
LED-s will start flashing and after it is done device should boot into LEDE.

Device specifics:
Bootloader has Netconsole built it,you can access it by holding reset button while powering on for at least 3 seconds and less than 6 seconds.
It can be usefull for recovery as serial pads are on PCB and device is not meant to be opened at all.

8 MB of 16 MB of SPI flash is usable.
That is due to LigoWawe using dual firmware bootloader.
So if after 3 boots boot counter is not reset bootloader will boot the other firmware image.
Due to that at boot boot counter for used firmware image is reset to 0.

Signed-off-by: Robert Marko robimarko@gmail.com

### CODE REVIEW

**Comment by pepe2k** [comment]
@robimarko, could you provide me full flash dump from this device?

Cheers,
Piotr

**Comment by robimarko** [comment]
@pepe2k Sure,here it is.
https://drive.google.com/drive/folders/0B1VOQQ-_EIXKSXRTUklUYml5b0U?usp=sharing

Regards
Robert Marko

**Comment by pepe2k** [comment]
@robimarko, thanks! Do you maybe know where I can get their (LigoWave/Deliberant) official firmware? I have a custom OEM board (fcc: https://fccid.io/UB8-FWBD1907) which seems to be based on dlb-2 but it runs also a custom firmware.

Anyway, I will have a look at your work in next days and maybe combine support for both boards. Still trying to catch up with everything after my holidays and great OpenWrt Summit :)

Cheers,
Piotr

**Comment by robimarko** [comment]
@pepe2k You can get official firmware binaries here:
https://www.ligowave.com/downloads
You will find navigation for firmware type on the lower right side.

Pretty much all DLB models are based on the same hardware with different antennas and maybe LED more or less.
This is only one I had access to.

**Comment by robimarko** [comment]
@pepe2k Any news?

**Comment by robimarko** [comment]
@pepe2k Rebased on master and solved conflicts

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Comment by pepe2k** [comment]
Moved to https://github.com/openwrt/openwrt/pull/593.

**Pull request closed without merging**
