### PR TITLE
libevent2: update to 2.1.8-stable

### PR DESCRIPTION
**Pull request by liudf0716**
Signed-off-by: Dengfeng Liu <liudengfeng@kunteng.org>

### CODE REVIEW

**Comment by diizzyy** [comment]
Use the release tarball and you need to fix build variants.

**Comment by wongsyrone** [comment]
I am just wondering why libopenssl is added as default dependency.

**Comment by liudf0716** [comment]
@wongsyrone if not add libopenssl as default depends, it can not compile by error needing libcrypto.
I have debug this errors and found libevent.so depending libcrypto, so I add libopenssl as default depends

**Comment by liudf0716** [comment]
@diizzyy  I use git and clone its release tag, I think it's the same as release tarball.
anyway, this pr will fix because I found CMake not supported but I set it to compile in cmake mode

**Comment by diizzyy** [comment]
Stop creating a new pr, just push your now changes to the branch and squash it.
fyi, `--disable-openssl       disable support for openssl encryption`

**Comment by wongsyrone** [comment]
Did you test whether other programs depending on libevent2 can compile or not?

**Comment by liudf0716** [comment]
@diizzyy Ok, thanks for your kindly remind.

**Comment by liudf0716** [comment]
@wongsyrone cause my project apfree_wifidog need latest libevent version, so I have tested in apfree_wifidog program.

**Comment by diizzyy** [comment]
You need to a few more, like transmission and tmux.

**Comment by wongsyrone** [comment]
Yes, especially run-test.

**Comment by liudf0716** [comment]
@wongsyrone for apfree_wifidog, of course I run-test

**Comment by liudf0716** [comment]
@diizzyy I try tmux, it ok

**Comment by liudf0716** [comment]
lldpd also ok

**Pull request closed without merging**
