### PR TITLE
busybox: run sysntpd at higher priority

### PR DESCRIPTION
**Pull request by mstorchak**
Signed-off-by: Maxim Storchak <m.storchak@gmail.com>

### CODE REVIEW

**Comment by blogic** [comment]
please add a description explaining why.

**Comment by mstorchak** [comment]
Also I'd like to note that this change is essentially free: no code change, no extra deps, no config change. It's only +3 bytes in the initscript and +1 extra syscall at start time.

**Comment by kdarbyshirebryant** [comment]
Next you'll be claiming that maintaining accurate time is more important than bittorrenting ;-)  Which of course it is.

DNSSEC is one protocol immediately springing to mind that likes accurate time.

**Comment by blogic** [comment]
lgtm @jow-  ?

**Comment by jow-** [comment]
LGTM

**Comment by blogic** [comment]
merged, thanks !

**Comment by mstorchak** [comment]
Thank you!

**Comment by ConorOG** [comment]
Hopefully there isn't now a rush of priority upping.

**Pull request closed without merging**
