### PR TITLE
hostapd: don't configure unsupported htmode for wpa_supplicant

### PR DESCRIPTION
**Pull request by yogo1212**
Hi :-)

```$ uci show wireless.radio0
wireless.radio0=wifi-device
wireless.radio0.type='mac80211'
wireless.radio0.channel='11'
wireless.radio0.hwmode='11g'
wireless.radio0.path='platform/qca953x_wmac'
wireless.radio0.htmode='HT20'

$ uci show wireless.mesh0
wireless.mesh0=wifi-iface
wireless.mesh0.ifname='w-mesh0'
wireless.mesh0.device='radio0'
wireless.mesh0.network='mesh'
wireless.mesh0.mode='adhoc'
wireless.mesh0.encryption='psk2'
wireless.mesh0.ssid='mesh'
wireless.mesh0.bssid='02:BA:CC:22:33:66'
wireless.mesh0.disabled='0'
wireless.mesh0.key='batmesh123'
```
->
```
$ cat /var/run/wpa_supplicant-w-mesh0.conf
ap_scan=2

network={
        scan_ssid=0
        ssid="mesh"
        key_mgmt=WPA-PSK
        mode=1
        fixed_freq=1
        frequency=2462
        disable_ht40=1
        max_oper_chwidth=0
        mode=1
        psk="batmesh123"
        proto=RSN
        bssid=02:BA:CC:11:55:90
        beacon_int=100
        htmode=HT20
}
```

the log entries from netifd
```
Mon Nov 20 10:41:39 2017 daemon.notice netifd: radio0 (14880): Line 17: unknown network field 'htmode'.
Mon Nov 20 10:41:40 2017 daemon.notice netifd: radio0 (14880): Line 18: failed to parse network block.
```
are generated by wpa_supplicant
```
$ wpa_supplicant -i w-mesh0 -c /var/run/wpa_supplicant-w-mesh0.conf
Successfully initialized wpa_supplicant
Line 17: unknown network field 'htmode'.
Line 18: failed to parse network block.
Failed to read or parse configuration '/var/run/wpa_supplicant-w-mesh0.conf'.
```

### CODE REVIEW

**Comment by nbd168** [comment]
Your changes are missing your Signed-off-by. Please fix

**Comment by yogo1212** [comment]
@nbd168 oops. forgot to push :-|

**Comment by nbd168** [comment]
Merged, thanks.

**Comment by yogo1212** [comment]
pleasure :-)
have a nice day

**Pull request closed without merging**
