### PR TITLE
openssl: Remove DTLS and J-PAKE

### PR DESCRIPTION
**Pull request by neheb**
Nothing uses these.

By the way, is no-whrlpool a typo?

### CODE REVIEW

**Comment by champtar** [comment]
Hi @neheb,
Dtls can be used for some vpn, webrtc, ..., so maybe no packages use it yet but i would prefer to have a config option

**Comment by neheb** [comment]
Just pushed

**Comment by blogic** [comment]
@neheb please rebase this so that there is a patch to make both configurable. having patch 1 remove dtls to have patch 2 re-add it as configurable is not very nice/clean

**Comment by neheb** [comment]
Hmm? I didn't make both configurable since J-PAKE is used by nothing. Same with DTLS but I had a request to make it so.

**Comment by blogic** [comment]
ok, well patch 1 still removes dtls for patch to add it back

**Comment by blogic** [comment]
@neheb can you rebase the patches  fixing the dtls quirk ?

**Comment by neheb** [comment]
Yeah I'll do it when I get back from work.

**Comment by neheb** [comment]
Force pushed some new ones. Hopefully good now.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
