### PR TITLE
uboot-kirkwood: add uboot for nsa310b

### PR DESCRIPTION
**Pull request by bobafetthotmail**
this commit allows to make a standalone u-boot for nsa310b.

While both first-stage and second-stage u-boot work fine if
installed to flash or loaded with kwboot,
I could not get stock u-boot nor bodhi's u-boot to chainload
any second stage u-boot (I also tried with dockstar's uboot
that works fine on this device if loaded with kwboot).

Signed-off-by: Alberto Bursi <alberto.bursi@outlook.it>

### CODE REVIEW

**Comment by nbd168** [comment]
Merged to my staging tree, thanks.

**Comment by bobafetthotmail** [comment]
please drop it from the staging tree, I need to alter default mtdparts due to feedback in other PRs.

**Comment by kofec** [comment]
@bobafetthotmail 
I have bodhi's u-boot. Before changes provided by nbd168. I was able to run LEDE from usb. 
My questions:
1) Should this work with your changes and your uImage (start with bodhi's u-boot direcly from USB) - I didn't integrate dtb file - just point where it is located in env?
2) As I understand after your changes I will be possible to start from internal flash? So extroot should work ? So then it will be even better becuase we can use f2fs or ext4 on USB ?
3) Last question - Will sysupgrade work ?
thank again for your hard work

**Comment by bobafetthotmail** [comment]
1. yes, it should work like that with bodhi's uboot, also with this one (as it is pretty much a clone of bodhi's), but I didn't test this as it's not needed for LEDE.

2. yes, I have LEDE running in the flash of my nsa310. extroot will work, but should not be needed as there is 128 MiB of flash in this NAS, uboot needs 1 MiB and the rest is for LEDE.

3. yes, sysupgrade is working. I actually tested this because it's necessary for LEDE.

**Pull request closed without merging**
