### PR TITLE
new

### PR DESCRIPTION
**Pull request by linfang26**

### CODE REVIEW

**Comment by stintel** [comment]
Let me start by thanking you for your work. I have quite a few remarks though.
- These commits have to go: Merge branch 'master' of http://git.lede-project.org/source
- Encoding issues in commit messages need to be fixed
- Fix typo commit should be squashed with the commit that introduced the typo
- Use a space after a colon
- Drop the target and package prefixes
- Ideally this PR should be split into several smaller PRs, with each PR containing only related changes

**Comment by ignisf** [comment]
> * Encoding issues in commit messages need to be fixed

What @stintel means is that the commit messages have to be in English.

**Comment by Biercenter** [comment]
Thanks so much for @981213 , can you commit your luci-app-syncdial?  :-)

**Comment by 981213** [comment]
Sorry I'm wondering why you created such a boring pull request....
There are so many commits that you should just use it on your own branch if you like(Such as changing the regdb illegally:-P ).This PR should be closed I think.

**Pull request closed without merging**
