### PR TITLE
[RFD] Skip building images in core and allow IB configuration via menuconfig

### PR DESCRIPTION
**Pull request by dfc-d**
This patch series of three commits adds the option skip building images during the core built while allowing the user an easy way to set an appropriate configuration via menuconfig in imagebuilder.

### CODE REVIEW

**Comment by nbd168** [comment]
Can you try adding an if !IB_NO_CORE_IMAGE block around the entire "Target Images" menu instead of putting it in every symbol one by one?

**Comment by nbd168** [comment]
As for the second commit, I don't think it actually makes things better, I'd prefer to leave it out for now. Symbols like TARGET_IMAGE_IMAGES_PAD certainly look weird

**Comment by dfc-d** [comment]
The second commit is so that convert-config.pl can skip CONFIG_IMAGE_ config symbols when creating Config-build.in for preserving user's configuration (since if you didn't build images in core it doesn't make sense to preserve the no image config in the imagebuilder).

**Comment by nbd168** [comment]
I don't think it's actually necessary to skip these symbols. In case of a no-image config, no symbols will be copied over. In case of a config with images, the values will be used as defaults, while still allowing the user to configure them.

**Comment by dfc-d** [comment]
Actually with a recent patch that preserves unset config options as well as set options (so that compilation gets the result in SDK as in core), that is no longer true.

**Comment by nbd168** [comment]
It's still true even with that patch, since unavailable options are not emitted to .config.

**Comment by dfc-d** [comment]
Ah, missed that.  Will rework based on that.

**Comment by blogic** [comment]
4 weeks with no feedback. please reopen when you have time again.

**Pull request closed without merging**
