### PR TITLE
17.01: mwlwifi: update driver to 2017-08-10

### PR DESCRIPTION
**Pull request by hnyman**
Backport the update to version 10.3.4.0-20170810 from LEDE master, where this 2017-08-10 version has been for the last month since #1288

Run-tested with WRT3200ACM running 17.01-SNAPSHOT r3560-79f57e422d

This is second try, with cherry-pick approach this time, as #1425 was closed for not being a straight cherry-pick but a "backport" with a squashed commit. Identical end-result...

### CODE REVIEW

**Comment by anomeome** [comment]
This is sorely needed in LEDE stable as @yuhhaurlin is wanting a common / known image, with current mwlwifi. on which to reproduce [issue](https://github.com/kaloz/mwlwifi/issues/225) Master is obviously not an option, and pointing people at an image done by unknown / random sources / user doesn't fly either.

**Comment by lucize** [comment]
for how many days did you have it in test ?
today master is crashing on me with the issues reported on mwlwifi github, last time it took me only 2 hours

**Comment by anomeome** [comment]
I have been running with this on a rango since before it was pushed to master, not sure what the longest uptime might be as I tend to flash frequently, but certainly >= 7 days. I think the issue on the mwlwifi github is related to the latest BLOB, which is not in this. Are you running with the firmware push that came out post this commit?

**Comment by lucize** [comment]
I'm running the master, today master has crashed wery fast, ~2h, but the problems (wifi crash/router reboot) started like ~6 days ago if I remember sometime after the wireless backport update

**Comment by anomeome** [comment]
Right, but this PR is about the last mwlwifi push to master being picked into _hopefully_ the next stable. To my knowledge there are no reports of failure running this on current stable. You apparently have a new issue regarding master, so probably the conversation needs to happen elsewhere, and what you are describing sounds like it should maybe be entered in [FS](https://bugs.lede-project.org/)

**Comment by lucize** [comment]
just wanted to be sure the stable is ok, so I don't switch to it in vain

**Comment by NainKult** [comment]
Fixed by 38cc071 , can be closed now.

**Comment by hnyman** [comment]
> Fixed by 38cc071 , can be closed now.

hmm...
This PR is about 17.01 branch. No changes there, yet.

**Comment by NainKult** [comment]
Yep, my bad, i tough it was committed to the 17.01 branch as well. However, I'm not certain they will merge to stable _just for debugging mwlwifi_. That's the reason why snapshots exists, to avoid merging unknown and mostly untested code to the stable branch, especially when users report crashes with it.

At least 38cc071 address this:
> pointing people at an image done by unknown / random sources / user 

Take my previous remark as a careless bump of this PR ;)

**Comment by lucize** [comment]
I expect this update https://github.com/kaloz/mwlwifi/commit/d5c5b05c538ad678929f1ed2891dde25a6fdd3eb to be more stable, the hostapd was cleared of the away stations after ~3 hours, this didn't happened before

```
Tue Nov 28 12:51:28 2017 daemon.info hostapd: wlan0: STA 40:40:a7:xx:xx:xx WPA: group key handshake failed (RSN) after 4 tries
Tue Nov 28 12:51:28 2017 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED 40:40:a7:xx:xx:xx
Tue Nov 28 12:51:28 2017 daemon.info hostapd: wlan0: STA a4:e4:b8:xx:xx:xx WPA: group key handshake failed (RSN) after 4 tries
Tue Nov 28 12:51:28 2017 daemon.notice hostapd: wlan0: AP-STA-DISCONNECTED a4:e4:b8:xx:xx:xx
Tue Nov 28 12:51:30 2017 kern.info kernel: [86489.299022] ieee80211 phy0: staid 2 deleted
Tue Nov 28 12:51:30 2017 kern.info kernel: [86489.352005] ieee80211 phy0: staid 1 deleted
Tue Nov 28 12:51:33 2017 daemon.info hostapd: wlan0: STA 40:40:a7:xx:xx:xx IEEE 802.11: deauthenticated due to local deauth request
Tue Nov 28 12:51:33 2017 daemon.info hostapd: wlan0: STA a4:e4:b8:xx:xx:xx IEEE 802.11: deauthenticated due to local deauth request

```

**Comment by lucize** [comment]
this https://github.com/lede-project/source/pull/1552 should be more optimal

**Comment by hnyman** [comment]
I will close this, as there are newer versions of the driver

**Pull request closed without merging**
