### PR TITLE
ar71xx: add spi nand flash driver and support gl-ar300m device with nand flash

### PR DESCRIPTION
**Pull request by zhao-gang**
The spi nand flash driver is from qsdk on codeaurora. https://source.codeaurora.org/quic/qsdk/oss/system/openwrt/tree/target/linux/ar71xx/files/drivers/mtd/nand/ath79_spinand.c?h=release/coconut_ioe4531_2.0

Running tested on gl-ar300m device with Giga Device / HeYangTek spi nand flash, although It may need more cleaning work.

### CODE REVIEW

**Comment by blogic** [comment]
normally i would ask if the spi-nand stuff has been sent upstream, but it originates from qulacomm, so most likely the answer will be "never"

**Comment by pepe2k** [comment]
This was already discussed and rejected ~year ago:
https://patchwork.ozlabs.org/patch/493667/

**Comment by blogic** [comment]
@zhao-gang can you fold my previous review into the driver ?

**Comment by zhao-gang** [comment]
@blogic Sure. When it's finished I will update the issue so you can review it again. :-)

**Comment by alzhao** [comment]
Why it is a problem from qualcomm? In the license, it says GPL. 
So seems this patch will be accepted soon after @blogic 's comments is in-cooperated.

**Comment by blogic** [comment]
actually there is a driver in the kernel staging section
please use that instead

**Comment by blogic** [comment]
@zhao-gang did you try using the patch from the staging tree ?

**Comment by zhao-gang** [comment]
@blogic Unfortunately I no longer have the time / resources to work on this. :-( Hope someone else can pick it up.

**Pull request closed without merging**
