### PR TITLE
sunxi: add Olimex A20-OLinuXino-LIME2

### PR DESCRIPTION
**Pull request by lucize**
add Olimex A20-OLinuXino-LIME2

Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

### CODE REVIEW

**Comment by hauke** [comment]
Why are you removing the regulators from the device tree file?

**Comment by lucize** [comment]
It's backported from 4.6 as I saw, but is not completely, it will not start with the regulators, at least, the hdmi display.

**Comment by hauke** [comment]
@lucize Is it this commit you want to backport here?
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b43776d65a33b460925604a27fb9360af08c55ce
Then you should add it also with the lines which are getting added and with the commit comment.

**Comment by lucize** [comment]
tried it before posting the PR, I think the axp209 driver is not complete, or something else is missing

adding the regulators on 4.4 will not boot at all, tried with plain 4.9/4.12(rc) and there was no hdmi output but it started, maybe updating the pachset for 4.9 will make it work, I'm not an expert in this area so I didn't tried harder because everything seems to work ok without those values

**Comment by hauke** [comment]
Could you please rebase your changes on top of current master branch.

**Comment by lucize** [comment]
done!

**Comment by hauke** [comment]
Thank you for the patch it was merged into master

**Pull request closed without merging**
