### PR TITLE
bcm53xx: Add initial support for PHICOMM K3

### PR DESCRIPTION
**Pull request by Hill-98**
This router has BCM4709C0, 128MB NAND flash (MX30LF1G18AC-TI),
and 512MB memory, with 3 x LAN and 1 x WAN. WL chips are
BCM4366C0 x 2. The router has a small LCD and 3 capactive keys
driven by a PIC microcontroller, which is in turn wired to
UART1 of main board, No LED.

Wireless can work properly, but need additional wireless firmware, you
can download from here: https://drive.google.com/drive/folders/0ByNlqhxfFBAreUdGTTVDS1NlWlE
See README.txt for how to use it

Flash:
1. Enter CFE
2. CFE Brush Excess LEDE, you can get it from here: https://drive.google.com/file/d/0ByNlqhxfFBArb2owR05VUlVpN0E
3. Well, now you can brush into the trx file for the LEDE.

Signed-off-by: ZhongLuFan <lufanzhong@gmail.com>

### CODE REVIEW

**Comment by ptpt52** [comment]
nice!
but which one of the firmware should be used?

**Comment by robimarko** [comment]
You need to also add installation instructions to your commit message

**Comment by Hill-98** [comment]
Well, I have joined the method.

**Comment by robimarko** [comment]
Please include full instructions,dont just link other sites.
Who knows will they be online later

**Comment by Hill-98** [comment]
Sorry, I do not know how this bin file is made, it is made by Tian Hao <haotia@gmail.com>.

**Comment by hauke** [comment]
This looks like a duplicate of #1158.

**Comment by Hill-98** [comment]
I re-produced the patch file, #1158  patch file will be wrong, it is too long.

**Comment by hauke** [comment]
Could you please add the description on how to flash into the commit comment and not only into the pull request comment. You can do this with "git commit --amend". Please also use your real name and not a nick.

**Comment by Hill-98** [comment]
Okay, I'm fine.

**Comment by ptpt52** [comment]
you may need to slash all commits into one
git rebase -i <commit base id>

**Comment by robimarko** [comment]
Why did you close this PR?
Just squash commits into one

**Comment by alviezhang** [comment]
@Hill-98 Hi, brother. I really want this PR could be accepted. If you got any problem, I hope I could help you.

Here is your commits into single commit using rebase:
https://github.com/alviezhang/LEDE-source/commit/ef7dbbc30453e2fe9169ae90ff5e9b4d9d2dcb95

**Pull request closed without merging**
