### PR TITLE
lldpd: fix reload

### PR DESCRIPTION
**Pull request by commodo**
I thought I upstreame these a while back.
I only found the first one:
https://patchwork.ozlabs.org/patch/563075/

In the meantime, we've been using them internally [since the initial upstream].

These patches address some issues that I did not consider when I did the initial reload logic.

Signed-off-by: Alexandru Ardelean ardeleanalex@gmail.com

### CODE REVIEW

**Comment by jow-** [comment]
Minor stylistic nitpick, afterwards Acked-by from me.

Please use the `<<-EOF` syntax to allow indenting the here-doc termination tag as well.

Example:

    foo() {
        cat <<-EOF
            foo
            bar
            baz
        EOF
    }

**Comment by commodo** [comment]
re-spinned ; if you want i can test these changes ; but only on Monday ; 
not sure if i can make it in the weekend

**Comment by jow-** [comment]
Merged into my staging tree: http://git.lede-project.org/7353741, http://git.lede-project.org/0c0e612

**Comment by commodo** [comment]
i can confirm now that the style change works fine in our internal setup; [ran a few tests with the change ]
thanks

**Pull request closed without merging**
