### PR TITLE
libs/libevent2: Update to 2.1.8

### PR DESCRIPTION
**Pull request by diizzyy**
Update libevent2 to 2.1.8

Many thanks to Jo-Philipp Wich and Jonas Gorski for helping me out.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Run-tested on mips64

Supersedes #848 (runtime tested on ramips and ipq8***)

**Comment by wongsyrone** [comment]
> OpenSSL and pthreads are linked to main lib in additional to the extra libs

link to openssl blindly is not the correct way to handle this.
You just need this commit: https://github.com/libevent/libevent/commit/5d18d87916728df67640bd225967c6d6df4a54f8

According to its commit message,

> (do not link ssl into every library)

**Comment by diizzyy** [comment]
It's not linking blindly, https://github.com/diizzyy/source/blob/patch-27/package/libs/libevent2/Makefile#L123

**Comment by wongsyrone** [comment]
Does CONFIG_PACKAGE_libevent2-openssl default to false?

**Comment by diizzyy** [comment]
Yes, it does.

**Comment by wongsyrone** [comment]
Have you tested these two situations?

1. compile and run test libevent2-openssl when CONFIG_PACKAGE_libevent2-openssl is false
2. the same to libevent2-pthreads

You have to be very cautious when dealing with dependencies.

**Comment by diizzyy** [comment]
I'm not sure I'm following you here.

If you select libevent2-openssl, libopenssl gets enabled:
https://github.com/diizzyy/source/blob/patch-27/package/libs/libevent2/Makefile#L53
https://github.com/diizzyy/source/blob/patch-27/package/libs/libevent2/Makefile#L123

...likewise if you do the same with pthreads.
Each time openssl and/or pthreads selection changes the package system triggers a re-configure+rebuild as main lib and the extension gets linked to the external lib(s).
https://github.com/diizzyy/source/blob/patch-27/package/libs/libevent2/Makefile#L25

**Comment by wongsyrone** [comment]
It works. But I still don't understand why not choose the easy way, backport a single commit, fewer modifications especially the dependency part, and you're done.

**Comment by wongsyrone** [comment]
If you only take musl-libc into account, there no need to add the dependency to libpthread, it is embedded into libc.

**Comment by diizzyy** [comment]
True but we still have other libraries and I'd rather have it in for consistency and correctness.

**Comment by wongsyrone** [comment]
> If you enable libevent2-openssl it doesn't work on its own and the main lib libevent-2.1.so.* gets also linked to OpenSSL.

Do you mean libevent2-extra, -core, etc?

**Comment by diizzyy** [comment]
tbh I only checked the main lib (libevent2) (not core, extra etc).

**Comment by wongsyrone** [comment]
You can check it again with upstream commit 5d18d87 included

**Comment by diizzyy** [comment]
That only affects -core which isn't the issue (that's what it says at least). The general guidelines is to stick with releases and upgrade/backport when needed. I fail to see that commit falling into the major issue-category.

**Comment by diizzyy** [comment]
@blogic @jow- 
Something you can have a look at?

**Comment by liudf0716** [comment]
@dizzy I don't think adding openssl and pthread dependment to all libevent library is a good idea. In fact, I have asked @azat about this question: why all libevent library need openssl, the answer was that it was a bug,here is the [issues](https://github.com/libevent/libevent/issues/473).

I have submitted a [PR](https://github.com/lede-project/source/pull/848#issuecomment-300411697) to  solve the problem, I don't know why u still submit another PR for it.

**Comment by diizzyy** [comment]
That wasn't clear at the time and in that case we should just wait for a fixed release.

**Comment by liudf0716** [comment]
@dizzyy for that bug, @azat,  who is maintainer of libevent,  has provided a solution, what  @wongsyrone
has done was officially recommended solution. for the bug was caused by one example, so I just commented the example to solve  it,　I thought that solution was also Ok.

**Comment by diizzyy** [comment]
Let's close this PR and wait for a proper release instead...

**Pull request closed without merging**
