### PR TITLE
busybox: v1.25.0 upstream patches

### PR DESCRIPTION
**Pull request by kdarbyshirebryant**
Include upstream patches for gzip, ip & ntpd.

Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>

### CODE REVIEW

**Comment by blogic** [comment]
i am sure that the upstream version of the patches is properly annotated. please use those patches.

**Comment by kdarbyshirebryant** [comment]
You'd like to think that wouldn't you but these are the complete unedited patches from upstream. Looky https://busybox.net/downloads/fixes-1.25.0/

**Comment by hnyman** [comment]
The commit messages can be found from the original commits in master:

* https://git.busybox.net/busybox/commit/networking/ntpd.c?id=150dc7a2b483b8338a3e185c478b4b23ee884e71
* https://git.busybox.net/busybox/commit/networking/libiproute/iproute.c?id=34ecc3b7aefdd6c31e8691bd5485037bbabedbd4
* https://git.busybox.net/busybox/commit/archival/gzip.c?id=71cfbce655bcfa6d3e0154d441a33d3bfd1dca57

**Comment by kdarbyshirebryant** [comment]
Thanks Hannu!  I looked but did not see. Updated.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
