### PR TITLE
dosfstools: update to v4.0

### PR DESCRIPTION
**Pull request by Noltari**
I will test this for brcm2708 but it would be nice if others could test it on omap, sunxi and mxs.

### CODE REVIEW

**Comment by blogic** [comment]
@Noltari did you test it ?

**Comment by Noltari** [comment]
Yeah I tested it for brcm2708.
Without the additional patch I had to backport from the dosfstools repository it was failing for brcm2708, that's why I would like someone to test it for the other targets using it.

**Comment by blogic** [comment]
@Noltari could you actively contact people to test it please, they probably did not se the request for testing

**Comment by Noltari** [comment]
@blogic I tested it myself the image was created without issues

**Pull request closed without merging**
