### PR TITLE
ramips: add support for Kimax U35WF

### PR DESCRIPTION
**Pull request by arvati**
This patch adds support for the Kimax U35WF.

SoC: MediaTek MT7620N
RAM: 64 MiB
Flash: 16 MiB
LAN: 1x 100M
Installation:
It is possible to install OpenWRT/LEDE from the web GUI on older stock firmwares (seems like an modified openwrt firmware).

It include packages to access USB pendrive and SATA drives and work with EXT4, FAT, NTFS and BTRFS filesystems

Signed-off-by: Ademar Arvati <arvati@hotmail.com>

### CODE REVIEW

**Comment by pepe2k** [comment]
Your pull request looks really wrong, please drop all additional commits with logs, hacks, etc. and keep only one (the first one) commit.

Also, make sure your patch/pull request meets all requirements from **[Submitting patches](https://lede-project.org/submitting-patches)**. At this moment it doesn't.

Cheers,
Piotr

**Comment by blogic** [comment]
@arvati do you plan to send a cleaned version of the series otherwise i would like to reject/close this PR

**Comment by arvati** [comment]
I will send an clean one but I am afraid it will be on another pr, since I am not able to change this one.

**Comment by pepe2k** [comment]
@arvati, this should help you next time:

Please make all requested changes in your local repository clone and then use `git commit --amend` to add them to your commit. Use `git push --force` to overwrite your GitHub repository/branch, which will afterwards update your pull request here automatically.

**Comment by alazyworkaholic** [comment]
@arvati 
Thanks a lot for making your release available, but could you finalize this commit? I've been using your image for a few months and it made my U35WF usable, but I can't install some things like nfs-kernel-server. I'd appreciate it very much if your code could be included! Thanks!

**Comment by arvati** [comment]
@alazyworkaholic sure, pleasure to help. I am a little busy with others projects but will clean up some things and post again as soon as possible. Meanwhile I could help on nfs-kernel-server trouble. I could share needed packages to you.

**Comment by alazyworkaholic** [comment]
@arvati 
A nfs-kernel-server package would help with a few specific problems, but an 'official' LEDE release with U35WF support would be better. I'd like to learn how to make lots of packages besides this one (fdupes, samba with multi-user support, etc.), and when I ask for help on IRC it's better to be using an official release. I hope this device can be supported for the next release.

**Pull request closed without merging**
