### PR TITLE
let perf link against libunwind

### PR DESCRIPTION
**Pull request by stsydow**
Let perf link against libunwind to get better backtraces.

### CODE REVIEW

**Comment by blogic** [comment]
the commit is missing a valid Signed-oof-by line. can you please provide it so we can merge the patch

**Comment by stsydow** [comment]
Ok there it is.
I put it in my commit template.

**Comment by stsydow** [comment]
Please wait. It doesnt work yet.

**Comment by jow-** [comment]
@stsydow - do you like to keep this PR open or will you propose another one if you sorted out the changes?

**Comment by stsydow** [comment]
So this changeset does not break anything but perfs feature and library detection does not enable libunwind. There have been changes in April to improve backtraces for mips, so I hope it will work with a newer Kernel. 
Sorry for the missing details. I was in a hurry when I discovered the problem.
I would also submit i again or we can open an issue an do it after the next release.

**Comment by blogic** [comment]
just open a new PR when it is tetsted/working properly please

**Pull request closed without merging**
