### PR TITLE
This is the WIP stuff for the DGN3500

### PR DESCRIPTION
**Pull request by danielg4**
@blogic

### CODE REVIEW

**Comment by blogic** [comment]
@danielg4 patches 2/4 and 3/4 are missing the description explaining the bug that they are fixing.

**Comment by danielg4** [comment]
2/4 does not address a bug, merely a logic error, possibly affecting only ath5k boards where under certain conditions, a nonexistent macaddr would be assumed correct.
3/4 puts br2684ctl init after ADSL init instead of before, so that the ESI is set at the right time, and for consistency with the PTM driver.

**Comment by blogic** [comment]
put a proper description into the patches so that they can be merged. you know how to created patches, i have seen you do it before. the patches need to be in the expected format so that they can be merged.

**Comment by blogic** [comment]
i merged 1/4 and 3/4 into my staging tree. please opena  new PR when the other patches are ready.

**Pull request closed without merging**
