### PR TITLE
toolchain/gdb: update to version 7.12.1

### PR DESCRIPTION
**Pull request by bladeoner**
Update gdb to version 7.12.1.

Tested with ar71xx.

GDB 7.12.1 brings the following fixes and enhancements over GDB 7.12:

   * PR tdep/20682 (aarch64 regression: gdb.cp/nextoverthrow.exp)
   * PR server/20733 (Failed to build aarch64_be-linux-gnu GDBserver)
   * PR tdep/20953 (GDB crashes after "set architecture rl78")
   * PR tdep/20954 (GDB crashes if "set architecture rx")
   * PR tdep/20955 (GDB internal error in cris-tdep.c)
   * PR build/20712 (gdb 7.12+ doesn't build as C++ on Solaris)
   * PR breakpoint/20653 (string_to_explicit_location has some weird code)
   * PR build/20753 (MinGW compilation errors due to strcasecmp)
   * PR gdb/20977 (GDB exception handling is broken on i686-w64-mingw32)
   * PR python/21048 (backtrace is broken on i686)
   * PR sim/20808 (mips sim build fails due to undefined SD/CPU variables)
   * PR sim/20809 (mips sim build fails for r3900 cpus)
   * PR gdb/20939 (GDB aborts

Signed-off-by: Etienne Haarsma <bladeoner112@gmail.com>

### CODE REVIEW

**Comment by diizzyy** [comment]
Are any of these updates tested?

**Comment by hnyman** [comment]
worksforme with ar71xx and ipq806x

**Comment by bladeoner** [comment]
Yes I tested it with ar71xx.

**Comment by nbd168** [comment]
Merged to my staging tree, thanks.

**Pull request closed without merging**
