### PR TITLE
Update automake to v1.15.1

### PR DESCRIPTION
**Pull request by langerth**
The new version includes the fix for new perl versions, so remove the related patch.

Signed-off-by: Thomas Langer <thomas.langer.71@gmail.com>

### CODE REVIEW

**Comment by hauke** [comment]
Please use the same email address in the Signed-off-by line and in the author line.
Please update to title to something like: "automake: Update to version 1.15.1"

**Comment by langerth** [comment]
> Please use the same email address in the Signed-off-by line and in the author line.
> Please update to title to something like: "automake: Update to version 1.15.1"

Requested changes done

**Comment by hauke** [comment]
Thank you for the patch, it was merged.

**Comment by chunkeey** [comment]
> make[4]: Entering directory '/mnt/build/lede/sl/build_dir/host/flex-2.6.4'
 cd . && /usr/bin/env bash /mnt/build/lede/sl/build_dir/host/flex-2.6.4/build-aux/missing automake-1.15 --foreign Makefile
configure.ac:31: error: version mismatch.  This is Automake 1.15.1,
configure.ac:31: but the definition used by this AM_INIT_AUTOMAKE
configure.ac:31: comes from Automake 1.15.  You should recreate
configure.ac:31: aclocal.m4 with aclocal and run automake again.
configure.ac:40: warning: The 'AM_PROG_MKDIR_P' macro is deprecated, and its use is discouraged.
configure.ac:40: You should use the Autoconf-provided 'AC_PROG_MKDIR_P' macro instead,
configure.ac:40: and use '$(MKDIR_P)' instead of '$(mkdir_p)'in your Makefile.am files.
WARNING: 'automake-1.15' is probably too old.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
make[4]: *** [Makefile:465: Makefile.in] Error 63
make[4]: Leaving directory '/mnt/build/lede/sl/build_dir/host/flex-2.6.4'
make[3]: *** [Makefile:28: /mnt/build/lede/sl/build_dir/host/flex-2.6.4/.built] Error 2
make[3]: Leaving directory '/mnt/build/lede/sl/tools/flex'
make[2]: *** [tools/Makefile:150: tools/flex/compile] Error 2
make[2]: Leaving directory '/mnt/build/lede/sl'
make[1]: *** [tools/Makefile:146: /mnt/build/lede/sl/staging_dir/target-arm_cortex-a9+neon_musl_eabi/stamp/.tools_compile_yynyyyyynyyyyynyynnyyyynyyyyyyyyyyyyyyynyynynnyyynny] Error 2
make[1]: Leaving directory '/mnt/build/lede/sl'
make: *** [/mnt/build/lede/sl/include/toplevel.mk:209: world] Error 2

**Comment by hkuchampudi** [comment]
I am experiencing a similar issue.

Currently, I worked around my issue by 
1. Replacing `AM_INIT_AUTOMAKE` in `build_dir/host/flex-2.6.4/configure.ac` with version 1.15
2. Deleted `aclocal.m4` in `build_dir/host/flex-2.6.4`
3. Ran `aclocal` and `autoconf` within `build_dir/host/flex-2.6.4`
4. Finally, I ran `./configure`, `make`, and `make install` within `build_dir/host/flex-2.6.4`

After making these changes, I restarted the build process and LEDE compiled successfully for me.

**Pull request closed without merging**
