### PR TITLE
    ramips: rt305x: update device tree source files

### PR DESCRIPTION
**Pull request by pinney**
Use the GPIO dt-bindings macros and add compatible strings in the
       rt305x device tree source files.
    
       Signed-off-by: L. D. Pinney <ldpinney@gmail.com>

### CODE REVIEW

**Comment by pinney** [comment]
This one doesn't include the rt305x-legacy targets.
It can be added to this or done later.

**Comment by blogic** [comment]
looks good but this will break board detection inside  target/linux/ramips/base-files/lib/ramips.sh

**Comment by mkresin** [comment]
Nah, it shouldn't break anything. Board detection on ramips is done via model name from device tree and none of the model names is touched by this PR.

**Comment by blogic** [comment]
true, LGTM in that case

**Comment by mkresin** [comment]
Merged to my staging tree. I added the compat strings/GPIO macros for the legacy boards, some missing regular boards and the usual minor changes/fixes.

@pinney would you please have a look at the commits in my staging tree to ensure that I did not introduced a regression or have done something silly.

**Comment by pinney** [comment]
Looks OK

**Pull request closed without merging**
