### PR TITLE
tools/sparse: Update to snapshot 2017-03-31

### PR DESCRIPTION
**Pull request by diizzyy**
Update sparse to snapshot 2017-03-31
Switch to HTTPS

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by blogic** [comment]
blows up in my test builds

    LINK     test-lexing
libsparse.a(builtin.o): In function `expand_bswap':
/home/blogic/source/build_dir/host/sparse-2017-03-31-14964df5/builtin.c:190: undefined reference to `__builtin_bswap16'
collect2: error: ld returned 1 exit status
make[4]: *** [test-lexing] Error 1
make[4]: Leaving directory `/home/blogic/source/build_dir/host/sparse-2017-03-31-14964df5'
make[3]: *** [/home/blogic/source/build_dir/host/sparse-2017-03-31-14964df5/.built] Error 2
make[3]: Leaving directory `/home/blogic/source/tools/sparse'
make[2]: *** [tools/sparse/compile] Error 2
make[2]: Leaving directory `/home/blogic/source'
make[1]: *** [/home/blogic/source/staging_dir/target-arm_arm926ej-s_musl_eabi/stamp/.tools_compile_yynyyyyynyyyyynyynnyyyynyyyyyyyyyyyyyyynyynyynyyynny] Error 2
make[1]: Leaving directory `/home/blogic/source'
make: *** [world] Error 2

**Comment by diizzyy** [comment]
Interesting....

´´´
     CC       test-lexing.o
     CC       target.o
     CC       parse.o
     CC       tokenize.o
     CC       pre-process.o
     CC       symbol.o
     CC       lib.o
     CC       scope.o
     CC       expression.o
     CC       show-parse.o
     CC       evaluate.o
     CC       expand.o
     CC       inline.o
     CC       linearize.o
     CC       char.o
     CC       sort.o
     CC       allocate.o
     CC       compat-linux.o
     CC       ptrlist.o
     CC       builtin.o
     CC       flow.o
     CC       cse.o
     CC       simplify.o
     CC       memops.o
     CC       liveness.o
     CC       storage.o
     CC       unssa.o
     CC       dissect.o
     AR       libsparse.a
     LINK     test-lexing
     CC       test-parsing.o
     LINK     test-parsing
     CC       obfuscate.o
     LINK     obfuscate
     CC       compile.o
     CC       compile-i386.o
     LINK     compile
     CC       graph.o
     LINK     graph
     CC       sparse.o
     LINK     sparse
     CC       test-linearize.o
     LINK     test-linearize
     CC       example.o
     LINK     example
     CC       test-unssa.o
     LINK     test-unssa
     CC       test-dissect.o
     LINK     test-dissect
     CC       ctags.o
     LINK     ctags
     GEN      sparse.pc
make[3]: Leaving directory '/home/diizzy/production-2017-05-14-16mbit/source/build_dir/host/sparse-2017-03-31-14964df5'
touch /home/diizzy/production-2017-05-14-16mbit/source/build_dir/host/sparse-2017-03-31-14964df5/.built
install -m0755 /home/diizzy/production-2017-05-14-16mbit/source/build_dir/host/sparse-2017-03-31-14964df5/sparse /home/diizzy/production-2017-05-14-16mbit/source/staging_dir/host/bin
mkdir -p /home/diizzy/production-2017-05-14-16mbit/source/staging_dir/host/stamp
touch /home/diizzy/production-2017-05-14-16mbit/source/build_dir/host/sparse-2017-03-31-14964df5/.built
touch /home/diizzy/production-2017-05-14-16mbit/source/staging_dir/host/stamp/.sparse_installed
make[2]: Leaving directory '/home/diizzy/production-2017-05-14-16mbit/source/tools/sparse'
make[1]: Leaving directory '/home/diizzy/production-2017-05-14-16mbit/source'
´´´´
(Tested on kirkwood and ramips)

I'll have a look into it.

**Comment by diizzyy** [comment]
This fails because of very old version of GCC (4.7). I've discussed this briefly with @jow- that buildbots should share the same version and that switching to 4.9 (which tictex uses) is probably a good idea to avoid unnecessary work when following upstream.

**Comment by hauke** [comment]
This was merged by John some days ago.

**Pull request closed without merging**
