### PR TITLE
 ipq806x: Add "set preinit interface"

### PR DESCRIPTION
**Pull request by heinzek**
Failsafe mode up eth0 interface. 
Signed-off-by: Henryk Heisig <hyniu@o2.pl>

### CODE REVIEW

**Comment by jow-** [comment]
LGTM. @blogic ?

**Comment by blogic** [comment]
the file was not executable so it cant have worked properly. i fixed this and merged the patch into my staging tree
@heinzek please test if an image built from my tree works

thanks !

**Comment by heinzek** [comment]
@blogic Works well

```
[    5.634035] init: - preinit -
Press the [f] key and hit [enter] to enter failsafe mode
Press the [1], [2], [3] or [4] key and hit [enter] to select the debug level
f
- failsafe -
Generating key, this may take a while...
Public key portion is:
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQCEO7HJ71AvcK/BE+K6zs+PqHT20UCK1w52th1eZ6nSjA9CBlKgSuJC39GXktItDthRH1oYWD0AONxLdCgZq+es2JEVueHgOycDUxUjh26nNkqB0ivz+snu8lH/suXEr94ZkP+iGmub9+UzEm9WS45IhFEk8XNIO/YGPwlltSzRtQ== root@(none)
Fingerprint: md5 3d:8e:2d:b6:2d:8a:78:4e:fa:d7:4d:3d:2f:f0:49:5f


BusyBox v1.24.2 () built-in shell (ash)

ash: can't access tty; job control turned off
     _________
    /        /\      _    ___ ___  ___
   /  LE    /  \    | |  | __|   \| __|
  /    DE  /    \   | |__| _|| |) | _|
 /________/  LE  \  |____|___|___/|___|                      lede-project.org
 \        \   DE /
  \    LE  \    /  -----------------------------------------------------------
   \  DE    \  /    Reboot (HEAD, r562)
    \________\/    -----------------------------------------------------------

================= FAILSAFE MODE active ================
special commands:
* firstboot          reset settings to factory defaults
* mount_root     mount root-partition with config files

after mount_root:
* passwd                         change root's password
* /etc/config               directory with config files

for more help see:
http://wiki.openwrt.org/doc/howto/generic.failsafe
=======================================================

root@(none):/# [    7.723235] ipq806x-gmac-dwmac 37200000.ethernet eth0: Link is Up - 1Gbps/Full - flow control off

root@(none):/# ifconfig
eth0      Link encap:Ethernet  HWaddr EC:08:6B:2C:A0:4D
          inet addr:192.168.1.1  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: fe80::ee08:6bff:fe2c:a04d/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:73 errors:0 dropped:0 overruns:0 frame:0
          TX packets:9 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:8721 (8.5 KiB)  TX bytes:1691 (1.6 KiB)
          Interrupt:255

root@(none):/#
```
Now i can connect using ssh

**Comment by blogic** [comment]
thanks for testing !

**Pull request closed without merging**
