### PR TITLE
mvebu: WRT3200ACM add bluetooth support 

### PR DESCRIPTION
**Pull request by heinzek**
Update firmware mrvl/sd8887_uapsta.bin and add support for Marvell bluetooth with SDIO interface.
Set bluetooth module by default package in wrt3200acm.

```
[   13.545120] Bluetooth: Core ver 2.22
[   13.548754] NET: Registered protocol family 31
[   13.553247] Bluetooth: HCI device and connection manager initialized
[   13.559638] Bluetooth: HCI socket layer initialized
[   13.564564] Bluetooth: L2CAP socket layer initialized
[   13.569645] Bluetooth: SCO socket layer initialized
[   13.574986] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   13.580321] Bluetooth: BNEP filters: protocol multicast
[   13.585592] Bluetooth: BNEP socket layer initialized
[   13.591739] Bluetooth: vendor=0x2df, device=0x9136, class=255, fn=2
[   14.381876] Bluetooth: FW download over, size 695532 bytes
[   15.021330] sdio platform data not available
[   15.026306] usbcore: registered new interface driver btusb
[   15.032527] Bluetooth: HCI UART driver ver 2.3
[   15.036990] Bluetooth: HCI UART protocol H4 registered
[   15.042159] Bluetooth: HCI UART protocol BCSP registered
[   15.047992] Bluetooth: HIDP (Human Interface Emulation) ver 1.2
[   15.053955] Bluetooth: HIDP socket layer initialized

```

```
root@LEDE:~# hciconfig -a
hci0:   Type: BR/EDR  Bus: SDIO
        BD Address: 60:38:E0:XX:XX:AC  ACL MTU: 1021:7  SCO MTU: 120:6
        DOWN
        RX bytes:846 acl:0 sco:0 events:34 errors:0
        TX bytes:566 acl:0 sco:0 commands:34 errors:0
        Features: 0xff 0xfe 0x8f 0xfe 0xdb 0xff 0x7b 0x87
        Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
        Link policy: RSWITCH HOLD SNIFF
        Link mode: SLAVE ACCEPT

```

### CODE REVIEW

**Comment by diizzyy** [comment]
Since you're pulling the exact same firmware perhaps we could piggyback on using Gentoo's distfiles instead and avoid git + having our own tarball?
https://mirror.csclub.uwaterloo.ca/gentoo-distfiles/distfiles/linux-firmware-20170622.tar.gz (etc)
https://github.com/lede-project/source/pull/1133

**Comment by hauke** [comment]
Could you please put btmrvl and btmrvl_sdio into one single package and not just add them to the bluetooth package like it is done with ath3k.

**Comment by heinzek** [comment]
> Could you please put btmrvl and btmrvl_sdio into one single package and not just add them to the bluetooth package like it is done with ath3k.

Done

**Comment by heinzek** [comment]
Ping

**Comment by hauke** [comment]
Thank you for the patch, it was merged with small modifications.

**Pull request closed without merging**
