### PR TITLE
treewide: Remove CyaSSL (wolfSSL) from tree

### PR DESCRIPTION
**Pull request by diizzyy**
Remove wolfSSL (formely CyaSSL) from the tree. No maintainer and it's always
out of date which is bad from a security point of view. Having that in mind
it also indicates that there are very few/no users of this at all given the
above.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@hauke 
You're pretty much the only one how who touches this at all, are you ok dropping this or do you want to take maintainership? It seems like this package has been on life support for the past years now...

**Comment by commodo** [comment]
My 2c here: seems that there's wolfssl and mbedtls that try to be embedded
alternatives to OpeSSL, and are popular.

It seems that mbedtls is a bit more preferred in LEDE as a default, at
least recently.

But, I'd also try to see about the packages feed.
There may be some users of this lib there.
Maybe contacting those maintainers would be a good idea.

Personally, I don't feel strongly about any of the 2 libs (wolfssl or
mbedtls).
But I do prefer to choose one or the other, and not keep both.

**Comment by diizzyy** [comment]
Since upstream isn't really maintained I doubt the package maintainers aren't really bothered with it either but let's ping those too...

@gabri94 (admin/openwisp-config)
@karlp (libs/libwebsockets)
@kaloz @rajanvaja @rvaja (net/coova-chilli) (seems a unmaintained?)
@mhaas (net/wifidog) (seems heavily out of date/unmaintained)
@dangowrt (net/gnurl)

**Comment by borkra** [comment]
Just curious. Why do you believe wolfSSL is not maintained. It looks like they have releases every 3 months, last one on August 4, 2017....

https://www.wolfssl.com/wolfSSL/Docs-wolfssl-changelog.html

**Comment by diizzyy** [comment]
@borkra 
I'm referring to the lede/openwrt repo
https://github.com/lede-project/source/commits/master/package/libs/cyassl

**Comment by pprindeville** [comment]
Few things are worse than out-of-date, unmaintained security software.  It gives you a false sense of security.

libustream-cyassl
libcurl
coova-chilli
libwebsockets-cyassl
openwisp-config-cyassl
wifidog-tls

all depend on this.  Only wifidog-tls seems to not build against any other SSL library.

@diizzy: Can you also nuke openwisp-config-polarssl now that polarssl is retired?

**Comment by borkra** [comment]
It's not that old... I do not see any security issues with the existing software release. The later releases were devoted to introduction of TLS 1.3, but nobody uses in the real life yet. So which security problem concerns you so much?

**Comment by pprindeville** [comment]
> @mhaas (net/wifidog) (seems heavily out of date/unmaintained)

@diizzy: I just looked at wifidog/wifidog-gateway and there are still commits going into it (last one 2 months ago), even if the last release was 2 years ago.

**Comment by pprindeville** [comment]
> Just curious. Why do you believe wolfSSL is not maintained?

Okay, perhaps "untested" or "unvetted" would have been a better choice of words.  Given that there are relatively few packages that build against it, wouldn't that imply (assuming that this extrapolates more widely) it isn't used in that many packages... and therefore not as well "shaken down"?

**Comment by jow-** [comment]
NAK on removing it.

**Comment by borkra** [comment]
@pprindeville, wolfSSL, is the widely used library in the microcontroller world. It is out of the box SSL provider for all Microchip microcontrollers and FreeRTOS among others. Windows PC apps used it a lot too. Their move into Linux is the new development, but as far as the library concern, it is far from unproven... At least my take on it.

**Comment by dangowrt** [comment]
https://github.com/travelping/freewtp/tree/master/openwrt
is an out-of-tree project which is actively maintained and makes use
of libcyassl.

**Comment by pprindeville** [comment]
> Their move into Linux is the new development, but as far as the library concern, it is far from unproven... At least my take on it.

Okay, thanks for explaining that.

**Comment by diizzyy** [comment]
@jow- 
Out of curiosity, why keep it as it's always out of date and has been for the last ~2 years more or less? It's not like we're doing anyone a favor by shipping old SSL libs and given the history no one wants to actively maintain it.

@dangowrt 
Since they don't step up to maintain it upstream (as in LEDE/OpenWRT) they're better off having it in their own repo, unless we think including old SSL libs is a good thing.

**Comment by pprindeville** [comment]
> I'm not trying to step on anyone's toes here but history shows that we tend to keep more and more things that get old/unmaintained/badly maintained and we tend to keep things in tree "just because".

I'm not going to disagree with that.  But I don't want things being axed capriciously either.

Maybe we should have an explicit SLA/contract with the maintainers about how we expect things to be maintained (at a minimum) for things to stay in our repo?

**Comment by karlp** [comment]
I've already asked libwebsockets about whether their support for it even works.  I'm more than happy to drop libwebsockets-cyassl, less work for me.  I have no opinion on wolfssl itself

**Comment by hauke** [comment]
I just did some updates to close some know security problems in LEDE, I have no particualr intrest in wolfssl. 
Kaleb Himes from wolfssl seamed to be interested in wolfssl in LEDE, see:
http://lists.infradead.org/pipermail/lede-dev/2016-June/001074.html

@kaleb-himes  would you or some college like to maintain wolfssl in LEDE in the future?

**Comment by commodo** [comment]
i'll also raise my hand here, as a secondary/backup maintainer ;
if no-one wants to take maintainer-ship here [in any given timeout deemed reasonable] I'll take it;
it shouldn't take too much of time to handle it

**Comment by borkra** [comment]
@diizzyy, wolfSSL provides OpenSSL compatibility layer, this is what most packages are using. So support is maintaining ability of linking package source against wolfSSL library instead of OpenSSL one. It's rather minor.

Microcontrollers was referred to, only to relay that wolfSSL has a long usage history on the neighboring market to defer "unproven" argument.

**Comment by karlp** [comment]
@borkra in theory, yes, but that openssl compatibiltity layer is..... only sort of compatible, and requires a pile of extra hacks and mangled include paths.  It's _far_ from "just include the compat headers and you can use wolfssl"  (I've struggled against this "openssl compatible" trying to get libwebsockets-cyassl to work, and after speaking with libwebsockets about it, I'm preparing a patch just dropping that variant too)

**Comment by diizzyy** [comment]
@borkra 
I also tried experimenting with the compatibility layer and I can echo what karlp said in general, it's by far not a drop-in replacement.

**Comment by kaleb-himes** [comment]
@diizzyy 
@borkra 
@karlp 
@commodo 
@hauke 
@pprindeville 
@dangowrt 
@jow- 

Hi I just noticed the activity here, thanks for including me on this @hauke 

> I just did some updates to close some know security problems in LEDE, I have no particualr intrest > in wolfssl.
> Kaleb Himes from wolfssl seamed to be interested in wolfssl in LEDE, see:
> http://lists.infradead.org/pipermail/lede-dev/2016-June/001074.html
> 
> @kaleb-himes would you or some college like to maintain wolfssl in LEDE in the future?

> @borkra
> I also tried experimenting with the compatibility layer and I can echo what karlp said in general, it's > by far not a drop-in replacement.

Yes wolfSSL tries to maintain compatibility for a significant portion of the OpenSSL API but it is far from complete. We have a few pull requests in the works at the moment

https://github.com/wolfSSL/wolfssl/pull/724
https://github.com/wolfSSL/wolfssl/pull/764
https://github.com/wolfSSL/wolfssl/pull/945
https://github.com/wolfSSL/wolfssl/pull/979

And perhaps some more to come. Could you send us a list of the API's that are missing for the drop-in? Also please be aware the product "CyaSSL" has been renamed to "wolfSSL" and all development is being done in the https://github.com/wolfSSL/wolfssl repo!

Feel free to reach out to us at support@wolfssl.com for any specific questions as this project progresses!

**Comment by diizzyy** [comment]
@kaleb-himes 
I guess you're not interesting in maintaining your own port in LEDE then?

**Comment by kaleb-himes** [comment]
@diizzyy 

Could you send us a list of items you have found in testing that needs fixed?


Best Regards,

The wolfSSL Team

**Comment by diizzyy** [comment]
@kaleb-himes 
It was quite a few months back and I don't really recall exactly what I tried, sorry that I can't be of more help. I don't really have the time or tbh interest as openssl and mbedtls works just fine for my needs.

**Comment by liudf0716** [comment]
@mhaas (net/wifidog) (seems heavily out of date/unmaintained)
@Diizzy: I just looked at wifidog/wifidog-gateway and there are still commits going into it (last one 2 months ago), even if the last release was 2 years ago.
@pprindeville I think apfree wifidog is good replacement for wifidog-gateway, apfree wifidog is maintained by our kunteng  team which lead by me, here is the url:
https://github.com/liudf0716/apfree_wifidog

**Comment by mhaas** [comment]
net/wifidog maintainer here. I'm also a contributor to wifidog upstream. The upstream project is not dead yet, just dormant - I still do take a look at PRs and merge them iff they are acceptable.

As for CyaSSL/wolfSSL: I had choosen CyaSSL back then as it was (AFAIK) the smallest SSL library in the repo. If you guys decide to remove CyaSSL - and you have good reasons - then the build for wifidog-tls will have to be removed.

I personally do not have the time right now to port WifiDog to mbedtls, but it's not out of the question.

**Comment by diizzyy** [comment]
So in conclusion, we don't have anyone who actually wants to maintain wolfSSL and none of the "active" package maintainers seems to have any objects or am I missing something?

**Comment by commodo** [comment]
Ummm, I volunteered to take care of it, if nobody [more suited] steps up/wants to :)
[ That's kind of what I wanted to say back there ( https://github.com/lede-project/source/pull/1290#issuecomment-322988600 ) ]
And if nobody minds me maintaining it [ of course ]

**Comment by diizzyy** [comment]
Feel free to make a pull request and test it :-)

**Comment by commodo** [comment]
ack ; will make time for it [ today or this week ] ; i have a few things piled up

**Comment by commodo** [comment]
notifying people here about PR https://github.com/lede-project/source/pull/1319

**Comment by diizzyy** [comment]
Closing this as commodo has offered to maintain the wolfssl package.

**Pull request closed without merging**
