### PR TITLE
[PATCH] [package] jfsutils - add new package

### PR DESCRIPTION
**Pull request by infabo**
This patch adds journaled file system (JFS) utilities support.

Signed-off-by: Ingo Fabbri <der_ulmen@yahoo.de>

### CODE REVIEW

**Comment by infabo** [comment]
e2fsprogs and xfsprogs is in the official repo. kmod-fs-jfs is in the official repo. So jfsutils should be there too, as it provides jfs_fsck, jfs_tune and jfs_mkfs.

**Comment by infabo** [comment]
But if anyone thinks this package rather belongs to a seperate package repo instead of this one: is there an official LEDE package repo (like the openwrt package repo)? If yes, where to find and how to contribute?

**Comment by blogic** [comment]
I dont see a problem with merging this package. i'll merge it in the morning if there is no further feedback.

**Comment by diizzyy** [comment]
I don't any issues with this general but I do know we're looking at some growing pains about the package repo and I'm not sure how useful it is to have jfs utilities and/or or support at all in OpenWRT/LEDE.

**Comment by nbd168** [comment]
I think it's better to submit this to the packages repo. JFS is rather exotic after all

**Comment by bobafetthotmail** [comment]
@infabo in case you want to submit it to packages repo, this is it (shared with OpenWRT) https://github.com/openwrt/packages

**Comment by blogic** [comment]
ok, packages repo it is

**Comment by infabo** [comment]
OK, I'm going to submit over there.

Just one more thing: Then maybe xfsprogs should be dropped/moved too, because XFS is au par with JFS when talking about exoticness. ;)
Final cents: JFS is known to be very low on CPU-usage. And devices running OpenWRT most likely will not have much CPU-muscles in 95% of devices. 💃

**Comment by infabo** [comment]
@bobafetthotmail Should the PR be submitted to the lede.17.01 branch or to master branch? Will it be merged into the lede-17.01 branch too if I PR to master?

**Comment by diizzyy** [comment]
@infabo Master branch

**Comment by bobafetthotmail** [comment]
@infabo  if you ask nicely they can probably add it to the lede 17.01 branch too. It's not like this is a major sweeping change anyway.

**Comment by infabo** [comment]
Thanks guys for your assistance. Glad to see, there is so much feedback by contributors in such a short time. Know many other opensource-projects, where PRs are just ignored for weeks/months. 👍

**Pull request closed without merging**
