### PR TITLE
mvebu: add default sata trigger

### PR DESCRIPTION
**Pull request by Ansuel**
Change dts file to add default sata trigger to sata led

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by mkresin** [comment]
Would you please add the trigger for the other mvebu boards as well! Please fix the commit title and add a commit message.

Note: Depends on #914

**Comment by Ansuel** [comment]
@mkresin  Tested right now... and is working right (shelby)

**Comment by Ansuel** [comment]
@mkresin GOOD NEWS

> Hi Ansuel,
> 
>  On mar., févr. 28 2017, Ansuel Smith <ansuelsmth@gmail.com> wrote:
> 
> > In others board we have the sata led set to funcion
> > with the sata led trigger by default.
> > This patch makes the same for these board that have sata
> > led but get disabled by not associating it to any trigger.
> >
> > Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>
> 
> Applied on mvebu/dt (I also fixed the typo on func_t_ion and added the
> acked-by from Jason)
> 
> Thanks,
> 
> Gregory

We need to wait kernel update i think...

**Comment by mkresin** [comment]
merged into [my staging tree](https://git.lede-project.org/?p=lede/mkresin/staging.git;a=summary). I've added you upstream accepted commit as well. Would you please ACK the changes I've done!

**Pull request closed without merging**
