### PR TITLE
ipq806x: update ipq8065 and Netgear R7800 device trees

### PR DESCRIPTION
**Pull request by dissent1**
Huge device tree update brings:
-add QCOM QFPROM support
-add GSBI1, GSBI5, GSBI6 and GSBI7 nodes
-add lcc and lpass nodes
-update cpu nodes
-update smb208 subnodes layout and remove custom patch
-update rpm clk subnodes layout in the same accordance
-fix pinmux interrupt
-add spi pins
-move mdio and rgmii pinctrl from gmac and mdio into pinmux node
-add i2c4 pinctrl into rpm node
-add pin details into several nodes
-update gmac1 and gmac2 parameters
-update mdio phy0 and phy4 registers by ddwrt devs findings
-fix i2c4 pin drive-strengh
-remove pcie pins as it's already present in ipq8065 DT

This PR replaces https://github.com/lede-project/source/pull/284

@blogic @bendavid @ianchi @heinzek

### CODE REVIEW

**Comment by dissent1** [comment]
Updated:
- additional compatibility in GMAC in ipq8065 DT according to documentation
- additional irq parameter in gmac in R7800 DT

**Comment by blogic** [comment]
@dissent1 ready to go or will there be more changes ?

**Comment by dissent1** [comment]
I'm done for now. There will be some led fixes as well and maybe some more regulators, but later.
I was hoping for a feedback actually, but well, if there is none it's ok to go I guess.
The only doubt I have is correctness of changing the layout of rpm clocks. Could you please assess it, as i couldn't find any board DT that defined such clocks this way.

**Comment by blogic** [comment]
merged, Thanks !

**Comment by dissent1** [comment]
Ready for round 2, please review :)

**Comment by dissent1** [comment]
Setting correct CXO/PXO/WDT clocks provides approx 8% performance boost. Removing all other clocks and leaving only CXO/PXO/WDT provides approx 8.5% steadily, so it might be better.
I'll remove those clocks leaving only CXO/PXO/WDT until further investigation.
I'll do it in a separate commit to put the trace.

**Comment by dissent1** [comment]
Sorry for spamming, but no it's just coincidence...
I'm just trying to figure out bad page state bug FS#175 that appears right after watchdog init.

**Comment by dissent1** [comment]
Seems that those clocks changes should be applied along with gcc driver update to upstream, I'll try to see what I can do or will split changes into 2: ready and wip.

**Comment by dissent1** [comment]
@bendavid @heinzek 
Introduced a patch from upstream kernel that fixes base clocks for ipq806x. All cpu frequencies have to be adjusted, now it's a multiple of 27, for example: 1.404 ghz instead of 1.400, the lowest now is 391.5 instead of 384.
@blogic

**Comment by dissent1** [comment]
Split commits into 2:
1. GCC driver update with relative update to ipq806x device trees for all devices - this one is wip.
2. Leds and sata fixes for netgear R7800 - this one is ready.

Could you please merge the commit N2.

**Comment by heinzek** [comment]
@dissent1 Check my patch https://github.com/lede-project/source/pull/359/commits/93323c20857da7c850527a624e003b11079d091b Led section is moved form chosen to alias.

**Comment by dissent1** [comment]
Thanks! Updated.

**Comment by dissent1** [comment]
Updated commit with porting recent patches into lede, now clocks are updated to upstream, so as clk, opp and cpufreq drivers. Some patches that are not upstream are replaced with updated versions. 
CPU frequency is now scaling correctly with ondemand governor and each core scales seperately from each other.

Please test and review, this affects all ipq806x boards.

@blogic @heinzek @ianchi @bendavid

**Comment by dissent1** [comment]
I've got an update coming with more ported patches and completely fixed bad page state kernel bug at last that should be safe to push :)

**Comment by dissent1** [comment]
Seems that updating clocks to upstream kernel is a bit early because there's some mess in drivers, old clocks are hard-coded. Leaving it for future pull.

I'm done for now.

There is a couple of patches in the commit that are of no use for now, but I plan to adjust it a bit in future. I can remove it if needed.

**Comment by KanjiMonster** [comment]
Please [fix your git config so your commits have you correctly as the author]((https://help.github.com/articles/setting-your-username-in-git/), currently they say

 `Author: dissent1 <be.dissent+github@gmail.com>`

but they should probably say

`Author: Pavel Kubelun <be.dissent@gmail.com>`.

> There is a couple of patches in the commit that are of no use for now, but I plan to adjust it a bit in future. I can remove it if needed.

Please do so. Also it would be good to split the second commit into multiple commits if possible for better reviewing the changes (e.g. one per subsystem or so), and easier bisecting in case they break something.

And please update the patch numbering, use 0xx for patches that were accepted upstream and are backports from newer kernels, 1xx if submitted, but not yet accepted.

**Comment by dissent1** [comment]
Okay, thanks for reply, will do in a couple of days.

Could you please accept the 1st commit meanwhile, it fixes LEDs and eSATA port 
https://github.com/lede-project/source/pull/341/commits/baa7158170ab8e4b3611e5d06c65c7a115f17856

**Comment by dissent1** [comment]
Updated

**Comment by dissent1** [comment]
Sorry, updated authorship

**Comment by dissent1** [comment]
@blogic @KanjiMonster 
If there's something wrong with commits just tell me and I'll fix it. It's consistent and fixes most known remaining issues with R7800 and ipq806x.

**Comment by dissent1** [comment]
Haven't noticed your comment to split commits, must have been in hurry.
Made it.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
