### PR TITLE
base-files: implement default_preinst()

### PR DESCRIPTION
**Pull request by chris5560**
guarantee that running service is stopped before upgrading
reported at http://forum.lede-project.org/t/ddns-scripts-upgrade-issue/456/1

Signed-off-by: Christian Schoenebeck <<christian.schoenebeck@gmail.com>>

### CODE REVIEW

**Comment by blogic** [comment]
@jow-  LGTM

**Comment by KanjiMonster** [comment]
On upgrade the prerm is run since 88a14bfd1da55bbddf5a86b3c452f1d8b1c46a60 which should already take care of stopping services on upgrade. Does this not work for you?

**Comment by chris5560** [comment]
I cross checked with a dummy Makefile.
During update/upgrade postrm and prerm not called by opkg.

**Comment by KanjiMonster** [comment]
> I cross checked with a dummy Makefile.

Did you make sure the version was different? Currently opkg doesn't treat reinstalling the same version/package as an upgrade, only if the version differs it calls prerm.

**Comment by chris5560** [comment]
yep!

**Comment by KanjiMonster** [comment]
> yep!

How did you verify it won't call prerm/postrm? Can you share your package?

**Comment by KanjiMonster** [comment]
I'm trying to reproduce your issue, and there seems to be something wrong with the ddns-scripts init script, it does not background as expected:

```
root@lede:/# /etc/init.d/ddns start
 101840       : ************ ************** ************** **************
 101840  note : PID '1829' started at 2016-12-12 10:18
 101840       : ddns version  : 2.7.6
 101840       : uci configuration:
ddns.myddns_ipv4.domain='yourhost.example.com'
ddns.myddns_ipv4.enabled='1'
ddns.myddns_ipv4.interface='wan'
ddns.myddns_ipv4.ip_network='wan'
ddns.myddns_ipv4.ip_source='network'
ddns.myddns_ipv4.lookup_host='yourhost.example.com'
ddns.myddns_ipv4.password='your_password'
ddns.myddns_ipv4.service_name='dyn.com'
ddns.myddns_ipv4.username='your_username'
ddns.myddns_ipv4=service
 101840       : verbose mode  : 1 - run normal, console mode
 101841       : check interval: 600 seconds
 101841       : force interval: 259200 seconds
 101841       : retry interval: 60 seconds
 101841       : retry counter : 0 times
 101841       : No old process
 101841       : last update: never
 101841       : Detect registered/public IP
 101841       : #> /usr/bin/nslookup yourhost.example.com  >/var/run/ddns/myddns_ipv4.dat 2>/var/run/ddns/myddns_ipv4.err
 101846 ERROR : BusyBox nslookup error: '1'
 101846       : nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'yourhost.example.com': Try again
 101846       : Detect registered/public IP
 101846       : #> /usr/bin/nslookup yourhost.example.com  >/var/run/ddns/myddns_ipv4.dat 2>/var/run/ddns/myddns_ipv4.err
 101851 ERROR : BusyBox nslookup error: '1'
 101851       : nslookup: can't resolve '(null)': Name does not resolve
nslookup: can't resolve 'yourhost.example.com': Try again
 101851  WARN : Get registered/public IP for 'yourhost.example.com' failed - retry 1/0 in 60 seconds
^C 101931  note : PID '1829' terminated by 'SIGINT' at 2016-12-12 10:19
```

(the ^C is from me pressing ctrl-c). All I did was add a 'option enabled 1' to one of the default services.

**Comment by chris5560** [comment]
The ddns-scripts problem is a different problem same as openwrt/packages#3645
patch prepared and needs to be published next.
Looking on prerm/preinst I used the attached Makefile and copy it to package/openwrt-packages/csdummy/
"openwrt-packages" is listed in .gitignore file of lede and openwrt project
It only creates hopefully 4 files in home directory (of root)
If you increase PKG_VERSION and upgrade (do not forget to remove files in home first) you only get preinst and postinst files in you home.



include $(TOPDIR)/rules.mk

PKG_NAME:=csdummy
PKG_VERSION:=0.0.0
PKG_RELEASE:=0
PKG_MAINTAINER:=Christian Schoenebeck <christian.schoenebeck@gmail.com>

include $(INCLUDE_DIR)/package.mk

define Package/csdummy
  SECTION:=user
  CATEGORY:=Extra packages
  DEFAULT:=y
  TITLE:=DUMMY Package Title (Shown in menuconfig)
  MENU:=1
#  DEPENDS:=+luci-base @(PACKAGE_luci-mod-admin-full||PACKAGE_luci-mod-freifunk||PACKAGE_luci-mod-freifunk-community)
endef

define Package/$(PKG_NAME)/description
	DUMMY Package Description (Shown in LuCI)
endef

define Package/$(PKG_NAME)/config
	help
		PACKAGE Help

#	source "$(SOURCE)/Config.in"
endef

define Build/Prepare
	### RUNNING: Build/Prepare
#	set >> $(PKG_NAME)_build_prepare.txt
endef

define Build/Configure
	### RUNNING: Build/Configure
#	set >> $(PKG_NAME)_build_configure.txt
endef

define Build/Compile
	### RUNNING: Build/Compile
#	set >> $(PKG_NAME)_build_compile.txt
endef

define Build/Install
	### RUNNING: Build/Install
#	set >> $(PKG_NAME)_build_install.txt
endef

define Build/InstallDev
	### RUNNING: Build/InstallDev
#	set >> $(PKG_NAME)_build_installdev.txt
endef

define Package/$(PKG_NAME)/preinst
	#!/bin/sh
	### RUNNING: Package/preinst
	set >> ~/csdummy_preinst.txt
endef

define Package/$(PKG_NAME)/install
	### START: Package/install
#	$(INSTALL_DIR) $(1)/
#	$(INSTALL_CONF) ./files/* $(1)/
	set >> ~/csdummy_install.txt
	### END: Package/install
endef

define Package/$(PKG_NAME)/postinst
	#!/bin/sh
	### RUNNING: Package/postinst
	set >> ~/csdummy_postinst.txt
endef

define Package/$(PKG_NAME)/prerm
	#!/bin/sh
	### RUNNING: Package/prerm
	set >> ~/csdummy_prerm.txt
endef

define Package/$(PKG_NAME)/postrm
	#!/bin/sh
	### RUNNING: Package/postrm
	set >> ~/csdummy_postrm.txt
endef

$(eval $(call BuildPackage,$(PKG_NAME)))

**Comment by KanjiMonster** [comment]
This is what I get with current LEDE (ignore the --force-space, this is a ramdisk image).
```
root@lede:~# ls
root@lede:~# opkg install /tmp/csdummy_0.0.0-0_mips_mips32.ipk --force-space
Installing csdummy (0.0.0-0) to root...
Configuring csdummy.
root@lede:~# ls
csdummy_postinst.txt  csdummy_preinst.txt
root@lede:~# rm *
root@lede:~# opkg install /tmp/csdummy_0.0.1-0_mips_mips32.ipk --force-space
Upgrading csdummy on root from 0.0.0-0 to 0.0.1-0...
Configuring csdummy.
root@lede:~# ls *
csdummy_postinst.txt  csdummy_preinst.txt
csdummy_postrm.txt    csdummy_prerm.txt
```

So it does create preinst, postinst as well as prerm and postrm for me on upgrade.

**Comment by chris5560** [comment]
Sorry it seems to be NOT a problem at LEDE itseems to be a problem at OpenWrt,
but I don't understand:

LEDE Reboot (CURRENT, r2449-7c47f43) opkg version 0.1.8 works fine
opkg_9c97d5ecd795709c8584e972bfdf3aee3a5b846d-15

OpenWrt DESIGNATED DRIVER (Bleeding Edge, 50017) ALSO opkg version 0.1.8 doesn't run prerm/postrm
opkg_9c97d5ecd795709c8584e972bfdf3aee3a5b846d-12

looks like OpenWrt needs updates. I'm only wondering why opkg version display is the same on both.

**Comment by chris5560** [comment]
One more point/question:
Why are OpenWrt/Lede-Project still using and patching around in a 3 years old source package.
Looking on projects page the current version is 0.3.3

**Comment by KanjiMonster** [comment]
> opkg_9c97d5ecd795709c8584e972bfdf3aee3a5b846d-15

is not the same as 

> opkg_9c97d5ecd795709c8584e972bfdf3aee3a5b846d-12

the local version is different (-15 vs -12) which implies more changes on the LEDE one (like running prerm on the old package on upgrade).

> Why are OpenWrt/Lede-Project still using and patching around in a 3 years old source package.
Looking on projects page the current version is 0.3.3

Because AFAIK "recent" changes in opkg pull in a dependencies that increase opkg's size a lot, so staying at the old version keeps the size of opkg reasonable.

**Comment by KanjiMonster** [comment]
Closing this PR as it the issue isn't present in LEDE.

**Pull request closed without merging**
