### PR TITLE
[patch v3] layerscape: add 64b/32b target for ls1043ardb device

### PR DESCRIPTION
**Pull request by fsl-jyt**
Add support for NXP layerscape ls1043ardb 64b/32b Dev board.

LS1043a is an SoC with 4x64-bit up to 1.6 GHz ARMv8 A53 cores.
ls1043ardb support features as: 2GB DDR4, 128MB NOR/512MB NAND, USB3.0, eSDHC,
I2C, GPIO, PCIe/Mini-PCIe, 6x1G/1x10G network port, etc.

64b/32b ls1043ardb target is using 4.4 kernel, and rcw/u-boot/fman images from
NXP QorIQ SDK release.

All of 4.4 kernel patches porting from SDK release or upstream.

QorIQ SDK ISOs can be downloaded from this location:
http://www.nxp.com/products/software-and-tools/run-time-software/linux-sdk/linux-sdk-for-qoriq-processors:SDKLINUX

Signed-off-by: Yutang Jiang <yutang.jiang@nxp.com>

### CODE REVIEW

**Comment by fsl-jyt** [comment]
V3 patch update summary:
1. Optimize and minimize the config
2. Using PACKAGES/kmod mechanism
3. Add i2c-imx in i2c.mk and sdhci-of-esdhc in other.mk
4. Align to the current LEDE kernel version 4.4.19

**Comment by fsl-jyt** [comment]
@KanjiMonster @blogic 
Hi Jonas and John,

Do you have any suggestions for revision?
The i2c-imx and sdhci-of-esdhc need to be as an independent patch?
I'm working on porting a new ls1012 platform support to LEDE/openwrt based on this patch. Looking forward to your more suggestions, thanks!

**Comment by blogic** [comment]
PR 323 is newer

**Comment by ignisf** [comment]
that's PR #323 (for reference)

**Pull request closed without merging**
