### PR TITLE
ath10k-firmware: removed broken submenu

### PR DESCRIPTION
**Pull request by bobafetthotmail**
this package references an undefined variable for its submenu. 
Remove this NOP variable assignment.

Signed-off-by: Alberto Bursi <alberto.bursi@outlook.it>

### CODE REVIEW

**Comment by bobafetthotmail** [comment]
fixed this commit too as requested for https://github.com/lede-project/source/pull/606 as the issues here were the same.

**Comment by blogic** [comment]
lines with more than 75 chars.

**Comment by bobafetthotmail** [comment]
done.

**Comment by blogic** [comment]
imho the text is way to prose. please cut the chatter and be precise

"this package references an undefined variable for its submenu. remove this NOP variable assignment."

**Comment by bobafetthotmail** [comment]
done.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
