### PR TITLE
ipq806x: Fixed spi unexpected irq bug

### PR DESCRIPTION
**Pull request by heinzek**
Fixed spi unexpected irq bug
Added usb-dwc3-of-simple for supporting DWC3 USB

Based on work: Ram Chandra Jangir <rjangi@codeaurora.org>
Signed-off-by: Henryk Heisig <hyniu@o2.pl>

### CODE REVIEW

**Comment by blogic** [comment]
i did the same about 2 hours ago and was just about to start testing it.

i also added DSA support to my update. if ok with you i will close this PR and push my tree tomorrow instead.

**Comment by blogic** [comment]
will push my tree in an hour, please test that tree instead of these patches

**Comment by heinzek** [comment]
spi unexpected irq bug is fixed, but now switch not work.

**Comment by blogic** [comment]
ok, i will push the spi fixes to trunk. my tree has a semi ready switch patch, so it is expected to not work.

**Pull request closed without merging**
