### PR TITLE
ar71xx: add support for Wallys DR531 and jjPlus JWAP230

### PR DESCRIPTION
**Pull request by pepe2k**
The following series adds support for **Wallys DR531** (QCA9531 based) and **jjPlus JWAP230** (QCA9558+QCA8337 based) under ar71xx target.

### CODE REVIEW

**Comment by jow-** [comment]
Hi @pepe2k - I staged your commits in my tree with the following changes:
 - dropped commit `ar71xx: update kernel config symbols` as it looks suspcious to me
 - add a line break to switch definition in `ar71xx: add support for jjPlus JWAP230`
 - fixed indentation level of `image/generic.mk` in `ar71xx: add support for jjPlus JWAP230`

Can you please test my tree at https://git.lede-project.org/?p=lede/jow/staging.git;a=summary and tell me if it is okay? Thanks!

**Comment by pepe2k** [comment]
Hello @jow-

> dropped commit ar71xx: update kernel config symbols as it looks suspcious to me

I always check if target/subtarget kernel config needs update before making other changes (here: enable `CONFIG_ATH79_MACH_DR531`).

Those config symbols exist in [target/linux/generic/config-4.4](https://github.com/lede-project/source/blob/master/target/linux/generic/config-4.4#L1246), so they are not needed in ar71xx kernel config and will be removed when you save configuration (after issuing `make kernel_menuconfig CONFIG_TARGET=target`, under ar71xx target).

As I can see, other targets also need similar config update:

```
lede-project-source/target/linux$ grep -rn "CONFIG_HAVE_KERNEL_GZIP" */config-4.4
ar71xx/config-4.4:280:CONFIG_HAVE_KERNEL_GZIP=y
at91/config-4.4:138:CONFIG_HAVE_KERNEL_GZIP=y
cns3xxx/config-4.4:138:CONFIG_HAVE_KERNEL_GZIP=y
generic/config-4.4:1248:CONFIG_HAVE_KERNEL_GZIP=y
imx6/config-4.4:191:CONFIG_HAVE_KERNEL_GZIP=y
ipq806x/config-4.4:199:CONFIG_HAVE_KERNEL_GZIP=y
ixp4xx/config-4.4:114:CONFIG_HAVE_KERNEL_GZIP=y
kirkwood/config-4.4:153:CONFIG_HAVE_KERNEL_GZIP=y
malta/config-4.4:121:CONFIG_HAVE_KERNEL_GZIP=y
mvebu/config-4.4:191:CONFIG_HAVE_KERNEL_GZIP=y
mxs/config-4.4:147:CONFIG_HAVE_KERNEL_GZIP=y
omap/config-4.4:262:CONFIG_HAVE_KERNEL_GZIP=y
oxnas/config-4.4:170:CONFIG_HAVE_KERNEL_GZIP=y
sunxi/config-4.4:228:CONFIG_HAVE_KERNEL_GZIP=y
x86/config-4.4:182:CONFIG_HAVE_KERNEL_GZIP=y
zynq/config-4.4:314:CONFIG_HAVE_KERNEL_GZIP=y
```

> Can you please test my tree at https://git.lede-project.org/?p=lede/jow/staging.git;a=summary and tell me if it is okay? Thanks!

Sure, I will make tests and let you know. Thanks for fixing what I missed.

Cheers!

**Comment by pepe2k** [comment]
Hello @jow-,

I made tests using your tree and everything seems to be OK.

Cheers!

**Comment by jow-** [comment]
Thanks for testing, @pepe2k - it landed in master now.

**Pull request closed without merging**
