### PR TITLE
package/boot: update uboot-kirkwood to 2017.03

### PR DESCRIPTION
**Pull request by p-wassi**
Maintainer: @lperkov 
Compile tested: kirkwood
Run tested: kirkwood/dockstar

Description:
Bump uboot-kirkwood to upstream release 2017.03
Logs available at https://pwassi.privatedns.org/lede/dockstar/

### CODE REVIEW

**Comment by diizzyy** [comment]
Nice, good work :-)

**Comment by blogic** [comment]
merged, Thanks !

**Comment by mkresin** [comment]
@p-wassi This PR causes build errors for at least the ```u-boot-nsa325```. The error can be seen on the [buildbots](http://phase1.builds.lede-project.org/builders/kirkwood%2Fgeneric/builds/89) and I was able to reproduce the compile error on my machine.

Would you please send a fix for the introduced build error!

**Comment by p-wassi** [comment]
Thanks, Mathias for pointing me to that problem. Sorry for the introduced build error.
It's fixed in a new (additional) PR here: https://github.com/lede-project/source/pull/1001

**Pull request closed without merging**
