### PR TITLE
[RFC] [WIP] Mainlining netdev led triggers

### PR DESCRIPTION
**Pull request by BWhitten**
This PR is a work in progress cleanup of the netdev led triggers with a view to upstreaming, as such the prefix is wrong atm (and wrong for LEDE).
I have tried to address the various issues raised on the old patch submissions to the mailing list [1] and again [2].
My aim will be to have a round of reviews and tweaks here then go ahead and engage on the netdev/kernel mailing list.

An overview:
- One sysfs entry per parameter raised by Greg KH, for link, tx, and rx.
- Cleaning up the error checking in registration and unwind.
- Some suggestions on reformatting the logic.
- Converted the mode to flags to use atomics and avoid locks.
- Moving trigger to trigger subdirectory in kernel.

What could be looked over
- Locking, needs double checking.

[1] https://lkml.org/lkml/2010/11/14/116
[2] https://lkml.org/lkml/2010/11/28/187

### CODE REVIEW

**Comment by blogic** [comment]
@BWhitten LGTM, thanks for investing the time. !

**Comment by BWhitten** [comment]
For reference the patch is on the linux-kernel, linux-leds, and netdev mailing lists for review: https://www.spinics.net/lists/kernel/msg2660008.html

**Comment by mkresin** [comment]
@BWhitten I guess it is fine to close the PR? Your v5 looks pretty nice and earlier version collected already some ACKs.

**Comment by BWhitten** [comment]
Yep, all good this can be closed.
When it goes in I'll get a backport patch up on PR.

**Pull request closed without merging**
