### PR TITLE
x86/64: enable Hyper-V support in the kernel config

### PR DESCRIPTION
**Pull request by tedaz**
x86/64: enable Hyper-V support in the x86_64 kernel config
Enabled Hyper-V network interface card driver, display adapter driver, storage driver, keyboard driver, mouse driver and Hyper-V utility in the kernel for subtarget x86/64.
Convert the img file to vhd by Ubuntu qemu-img, rather than by the buildroot's build-in qemu-img.
Tested on Windows Server 2008 r2 and 2012 r2 Gen1. Gen2 doesn't work.

### CODE REVIEW

**Comment by komawoyo** [comment]
Seeing that you got this to work. I'm trying to set up a Hyper-V (or any other VM) wireless router pc. Have you got any network cards/ usb wireless to work on LEDE in Hyper-V?

**Comment by tedaz** [comment]
@komawoyo As Hyper-V has no method to pass-through USB and/or PCI devices to virtual machines, I don't think OpenWRT/LEDE can help much on USB network adapter support. I'm using an AP connect to switch to provide wireless service.

**Comment by nbd168** [comment]
Please rebase your branch to the latest version and ensure that all commits have a proper Signed-off-by:

**Comment by tedaz** [comment]
@nbd168 Thanks for your message. The new pull request #628 is the rebased request with the latest version and signed-off.

**Pull request closed without merging**
