### PR TITLE
ipq806x: switch to upstream usb driver and backport fixes

### PR DESCRIPTION
**Pull request by dissent1**
Also removing fifo-resize property drom DT as it has been removed from the driver.

Patches between fixes are taken just to keep the driver in line with upstream version.

This might solve FS#177.

### CODE REVIEW

**Comment by mkresin** [comment]
Does this fix [FS#177](https://bugs.lede-project.org/index.php?do=details&task_id=177)?

**Comment by dissent1** [comment]
It's a typo there, it *may* fix that issue. Awaiting feedback from the guy,
who experiences it.

вс, 13 нояб. 2016 г. в 18:40, Mathias Kresin <notifications@github.com>:

**Comment by blogic** [comment]
@dissent1  should i merge this ?

**Comment by dissent1** [comment]
@blogic yes, please, it's a standalone commit not related to the mentioned issue.
But if it fixes the issue I'll report back in Flyspray.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
