### PR TITLE
dnsmasq: bump to 2.77rc3

### PR DESCRIPTION
**Pull request by kdarbyshirebryant**
Fix [FS#766] Intermittent SIGSEGV crash of dnsmasq-full

Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>

This one works, honest!  Definitely issues DHCPv4 & v6 leases ;-)

### CODE REVIEW

**Comment by wongsyrone** [comment]
Why rushing with upstream? Can we wait for a stable release? 2.77rc2 got merged just a few hours ago via #1099 .

**Comment by dedeckeh** [comment]
@wongsyrone dnsmasq-2.77rc2 got merged in  my staging tree but has not been pushed to trunk as it was simply not functional dhcpv4 wise (http://lists.thekelleys.org.uk/pipermail/dnsmasq-discuss/2017q2/011488.html)
Taking in release candidates offers a wider coverage of testing; something which dnsmasq certainly can use

**Comment by wongsyrone** [comment]
Okay. No problem.

**Comment by dedeckeh** [comment]
Merged into my staging tree (https://git.lede-project.org/?p=lede/dedeckeh/staging.git;a=commit;h=a5b85403f4e23dc061d644273d27a0e1d02cfd68); thanks

**Pull request closed without merging**
