### PR TITLE
ramips: merge ramips subtargets mt7628/mt7688

### PR DESCRIPTION
**Pull request by pinney**
The ramips subtargets of mt7628 and mt7688 dts files all #include "mt7628an.dtsi"

They are essentially a single subtarget.

This patch merges the ramips subtargets mt7628 and mt7688 into a single subtarget mt76x8.

Signed-off-by: L. D. Pinney <ldpinney@gmail.com>

### CODE REVIEW

**Comment by hauke** [comment]
Could you please explain in the commit message why merging this is ok.

**Comment by pinney** [comment]
The majority of code is shared by the subtargets mt7628 and mt7688.
For example all of the device tree source files reference mt7628an.dtsi.

As for what to say in the commit ... I'm open to suggestions.

**Comment by diizzyy** [comment]
This seems like a reasonable tradeoff to me.

**Comment by blogic** [comment]
lgtm. once @pinney fixed up the commit description we can merge it

**Comment by blogic** [comment]
merged, Thanks !

**Comment by pinney** [comment]
target/linux/ramips/image/mt76x8.mk ~ line 92 
"TARGET_DEVICES += mt7628" is missing

**Pull request closed without merging**
