### PR TITLE
Allow to build a minimal SDK/IB

### PR DESCRIPTION
**Pull request by dfc-d**
This is a rebase of an accidentally closed PR which is based on #113.  It allows one to build an SDK consists only of the packages necessary to build the SDK/IB combo suitable for building all other required packages and creating the target images.

### CODE REVIEW

**Comment by dfc-d** [comment]
I've been successfully using to create minimal SDKs, build packages using the SDK, and IB to create images.

**Comment by blogic** [comment]
@nbd168 comments ?

**Comment by nbd168** [comment]
Review of this is made hard by the fact that you mix a lot of different changes into a single commit.
For a lot of changes the reasons you had for making them are simply not obvious.

Things like regenerating the metadata if defaults change can be achieved simply by adding an extra dependency for metadata scan.

For selecting the device type, I'd prefer having a set of reasonable metapackages (which can be installed via opkg) instead of further increasing the use of the DEVICE_TYPE stuff, which never really worked well in practice anyway.

What this has to do with building a minimal SDK/IB is not obvious to me either. Please start splitting up your stuff into smaller, semantically distinct commits and pull requests.

**Comment by dfc-d** [comment]
The main focus of this patch (building the minimal package set needed to build the toolchain is incompatible with the DEVICE_TYPE removal patch and is deprecated by it.  There are some useful elements that can be managed as separate patches.

**Pull request closed without merging**
