### PR TITLE
linux: add kmod-i2c-i801

### PR DESCRIPTION
**Pull request by sch-m**
Signed-off-by: Martin Schiller <ms@dev.tdt.de>

### CODE REVIEW

**Comment by hauke** [comment]
Thank you for the patch, it was applied to master with small modifications.

**Comment by pprindeville** [comment]
This doesn’t address the dependency on i2c-smbus.

**Comment by sch-m** [comment]
I've overseen the smbus dependency and Hauke added the smbus module to to the kmod i2c-i801 package:

https://github.com/lede-project/source/blob/master/package/kernel/linux/modules/i2c.mk#L147

**Comment by pprindeville** [comment]
Not to beat a dead-horse, but the SMbus driver isn't specific to the i2c-i801.

The Cavium ThunderX SoC also requires it (there are a couple of firewall platforms which use the ThunderX_NT SoC).

I think there was some out-of-tree environmental monitoring for certain AMD SoC's which also used SMbus.

**Comment by sch-m** [comment]
Interestingly, the i2c-i801 also loads and works without the i2c-smbus driver.
This is why I have overseen this relationship.

But I also agree, that explicitly adding the i2c-smbus module would maybe be the cleaner way.

**Comment by pprindeville** [comment]
> But I also agree, that explicitly adding the i2c-smbus module would maybe be the cleaner way.

@sch-m Since you seem to be getting faster turn-around than I do, can you please make this separation?

**Pull request closed without merging**
