### PR TITLE
 uboot-ar71xx: backport fix for glibc version 2.26+

### PR DESCRIPTION
**Pull request by gitbugged**
Fixes  FS#1047 - u-boot-nbg460n_550n_550nh bails out on CONFIG_ENV_SIZE error 

Signed-off-by: Bob Brooks <gitbugged@cool.fr.nf>

### CODE REVIEW

**Comment by gitbugged** [comment]
I'm not sure this is the "best" fix for this issue, but I followed instructions on FS#1047, and this was the working end-result.

**Comment by eamaclean** [comment]
This has nothing to do with glibc, and just seems to break building uboot-ar71xx entirely.

This is a conflict with a library called ragel (which I'll bet you have), u-boot includes a file called config.h, and expects it to be in the search path, and ragel happens to provide such a file earlier in the path than u-boot's own.

I'm not entirely sure what the correct resolution for this is, other than defensive programming lessons for both parties..

**Comment by mkresin** [comment]
Yes, it is completely unrelated to glibc. I'm able to trigger the compile error if I add a file `/usr/include/config.h` on my system and your change doesn't look like the appropiate solution for the issue.

**Comment by mkresin** [comment]
@gitbugged any plans to come up with a proper solution?

As outlined, it is unrelated to glibc. Reverting 83783f296a18e6e481f23b2019575e45c437db4e is more like using a hammer than a proper fix. It will (re)introduce the issue of u-boot isn't build with the images by default which was fixed by the commit.

**Comment by gitbugged** [comment]
No idea how to fix this unfortunately. Closing.

**Pull request closed without merging**
