### PR TITLE
ar71xx: add support for TP-Link EAP245 v1

### PR DESCRIPTION
**Pull request by j-d-r**
I submit this patch to add support for TP-Link EAP245 v1 (http://uk.tp-link.com/products/details/EAP245.html).

Everything works fine, Ethernet, 2.4GHz, 5Ghz and LED.

Ethernet is really difficult to initialize, i ported code from TP-Link GPL code (http://static.tp-link.com/resources/gpl/EAP245_V1_GPL.tar.bz2) to current kernel. I've done a lot of changes to make it compliant to code style of other boards.

---

TP-Link EAP245 v1 is AC1750 Wireless Dual Band Gigabit Ceiling Mount
Access Point:

	CPU: QCA9563-AL3A MIPS 74kc v5.0 @775MHz with 2.4GHz wifi
	RAM: 128MiB M14D1G1664A-2.5B @650MHz
	Flash: 16MiB 25Q128CSIG SPI NOR
	Wifi 5Ghz: QCA9880-BR4A 5 GHz wifi ath10k
	Gigabit Eth: AR8033-AL1A 1 gigabit lan port

Factory firmwares are signed, signature is verified when upgrading by
software. The only way to update is to solder a serial port, u-boot is
opened.

Serial port can be soldered on PCB J3, pins are TXD, RXD, GND, VCC.
PCB line close to header are missing resistors R225 (TXD), R237 (RXD),
R230 (RXD voltage divider). R225 and R237 can be replaced by wires, and
R230 (voltage divider) must be let opended. WITHOUT RESISTOR, THERE IS
NO PROTECTION. USE 3.3V MAX, AND PLUG TXD TO SERIAL PORT RX FIRST.

U-Boot is opened, just send C-B to break.
TAKE CARE ALL U-BOOT ENVIRONMENT VARAIABLE ARE NOT CORRESPONDING TO THE
BOARD. Partitions in bootargs and tftp flash command are BROKEN.

To flash:
ath> setenv ipaddr XXX.XXX.XXX.XXX (optional 192.168.1.1 by default)
ath> setenv serverip XXX.XXX.XXX.XXX (optional 192.168.1.10 by default)
ath> erase 0x9f040000 +0xd80000
ath> tftp 0x80060000 lede-ar71xx-generic-eap245-v1-squashfs-sysupgrade.bin
ath> cp.b $fileaddr 0x9f040000 $filesize

Gigabit ethernet SGMII port is a mess to initialize. A lot of obscure
register writes must be done for calibration and bus enabling. Without
this ethernet PHY is detected but packets are never sent. This code is
taken from TP-Link kernel 3.3.8 GPL code, with a lot of cleanup done to
use standard way to write to QCA956X registers (PLL, RESET, GMAC_SGMII,
etc.). These registers, and most bitmasks are added to ar71xx_regs.h.

Signed-off-by: Julien Dusser <julien.dusser@free.fr>

### CODE REVIEW

**Comment by j-d-r** [comment]
TP-Link kernel code for ethernet is in fact a copy-paste from Qualcomm Atheros u-boot 1.1.4 (https://source.codeaurora.org/quic/qsdk/oss/boot/u-boot-1.1.4/tree/board/atheros/common/qca-eth-956x.c)

**Comment by j-d-r** [comment]
I've just corrected a bug that someone reported me. Ethernet is only working in gigabit.
The fix consists in using ag71xx-mdio instead of mdio-gpio and explicitly set gpio functions before registering mdio. mdio-gpio does not set dev->mii_dev->bus resulting in fixed ethernet mode.

I also removed initialization (from tp-link kernel and qca u-boot) code that seems useless. Some registers that i had to arch/mips/include/asm/mach-ath79/ar71xx_regs.h are no longer used but i keep them.

Old code kept in  eap245-v1-buggy-eth0 branch.

Tested on linux-4.9.

**Comment by j-d-r** [comment]
@hauke May I ask you a review ? I submitted this PR months ago.

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Comment by j-d-r** [comment]
Moved to openwrt/openwrt#599

**Pull request closed without merging**
