### PR TITLE
gre,vti: add empty install rules

### PR DESCRIPTION
**Pull request by commodo**
@dedeckeh for gre
@nbd168 for vti  ; the code was submitted from the email list, so I could not track the submitter's github account

I mostly tested this with `gre` and applied the same pattern to `vti`.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by dedeckeh** [comment]
@commodo Idea behind the @(PACKAGE_GRE) dependency was to show only the gre sub-items when gre package is selected by the user. Similar approach is used in the PPP package with sub-items ppp-mod-pppoe, ppp-mod-pppoa, etc ... I felt this would be more intuitive and a more condensed overview if GRE is not selected but this is a matter of personal taste I guess

**Comment by commodo** [comment]
@dedeckeh I assumed it was something like that.
hmm ; so i guess i can leave it like that, and do some more config symbol dependency magic

to give a bit of background: when I try to pull in just `+grev4`, it does not get enabled until I also select `+gre` ; but I can select `+gre` from a "platform" meta-package, or target, and use `+PACKAGE_gre:grev4` in the package dependencies

**Comment by commodo** [comment]
re-spinned without the dependency re-ordering commits ; just the empty install rules

**Comment by commodo** [comment]
@jow- @blogic @dedeckeh 
any input on this ?

**Comment by jow-** [comment]
@commodo - I'm okay with having empty install sections but can you re-spin the change without adding the new `PackageEmptyInstall` helper? Just put the empty install sections into the `gre` and `vti` Makefiles.

**Comment by commodo** [comment]
sure;
fine from me ; will re-spin

**Comment by jow-** [comment]
Merged into my tree - thanks!

**Pull request closed without merging**
