### PR TITLE
Iptables: bump to 1.6.1

### PR DESCRIPTION
**Pull request by Ansuel**
Less modification than old commit (#748) , switch to git repo removed musl patch and refreshed existing patch
(is just some bits bigger because with new version we need 2 package for xtables to work)

Compiled and tested on WRT1900ACS

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@diizzyy can you test this?

**Comment by diizzyy** [comment]
Within a week or so

Please change git:// to http:// and use xz instead of gz.

**Comment by Ansuel** [comment]
@diizzyy fixed

**Comment by Ansuel** [comment]
@diizzyy updated to last commit

**Comment by nbd168** [comment]
I don't see why libnetfilter-conntrack would be required, and libnfnetlink seems non-essential too, since it's used only by the nftables part.
Please try to get rid of this stuff and either switch to an iptables release, or explain why you want to use the latest git version.

**Comment by Ansuel** [comment]
iptables 1.6.1 26KB
iptables 1.4.21 23,1KB
@nbd168 (now i'm trying to compiling with no extra dep)

**Comment by Ansuel** [comment]
@nbd168 connlabel seems to be the problem 
I made some changes and added config.in if someone need to enabled it (don't actually know if we need it, i'm testing) 
I have some problem with the if condition with libxtables (it should include that package if the condition is yes but it doesn't select them.. why? )

**Comment by Ansuel** [comment]
Ok i'm testing it and is working just fine

**Comment by Ansuel** [comment]
@nbd168 this should be good right?

**Comment by Ansuel** [comment]
@diizzyy can you test this?

**Comment by diizzyy** [comment]
Sure, but why aren't we one 1.6.1 or whatever the release is at?

**Comment by Ansuel** [comment]
@diizzyy just to keep things well updated 
(release is at 1.6.1 anyway)

**Comment by Ansuel** [comment]
I changed to relase version (i keep git so we can xz compression if i'm not wrong)

**Comment by diizzyy** [comment]
Nice, compiling... :-)

**Comment by Ansuel** [comment]
@diizzyy did you tested that ?

**Comment by diizzyy** [comment]
My testbox has gone missing... :/ 
I'll try find something else that isn't in use ASAP.

**Comment by Ansuel** [comment]
@nbd168 ok, this is the final version
Compiling and working fine, it's 2 month that i have this and all is working good
I solved problem with extra depends and add 2 configuration so if someone need that feature, he can enabled it. What do you think ?

**Comment by nbd168** [comment]
Merged to my staging tree with a minor cleanup, thanks.

**Comment by kdarbyshirebryant** [comment]
The bcp38 package uses '-m state --state NEW' but unfortunately this iptables doesn't understand the '-m state' switch.

**Pull request closed without merging**
