### PR TITLE
iperf3: Update to 3.1.6

### PR DESCRIPTION
**Pull request by diizzyy**
Update to 3.1.6

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Preferred way instead of using git which is submitted here: http://patchwork.ozlabs.org/patch/715468/

**Comment by mkresin** [comment]
Why do you create a PR for a patch that is already in patchwork? Is something wrong with the patch in patchwork?

> Preferred way instead of using git 

Preferred by whom?

**Comment by diizzyy** [comment]
This has been discussed several times, release tarballs > SCM pulls unless it makes sense.
That patch switches from this behavior to downloading it off git repo instead which just adds overhead in this case.

**Comment by mkresin** [comment]
Ah, I got your comment wrong. What I read "Preferred way instead of using git" == github PR prefered over git send-mail.

Anyway, wouldn't it make more sense to reply to the patch on the mailing list, so that author gets aware of the issue with his patch? I mean, that is one of the major disadvantages of github. It's really hard for people to learn from the mistakes made by others.

**Comment by diizzyy** [comment]
Sure, I submitted it late last night and haven't got around to it yet. I'll do it ASAP.

**Comment by bladeoner** [comment]
@diizzyy please update this commit to v3.1.6 since it has been released.

Thanks in advance.

**Comment by nbd168** [comment]
Merged to my staging tree, thanks.

**Pull request closed without merging**
