### PR TITLE
mvebu: Enable UAS (UASP)

### PR DESCRIPTION
**Pull request by diizzyy**
As USB storage support is already enabled, add UAS (UASP) as well.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile tested: mvebu, Linksys WRT3200ACM, LEDE trunk
Run tested: mvebu, Linksys WRT3200ACM, LEDE trunk

**Comment by ptpt52** [comment]
This is already export in kmod-usb-storage-uas
You could enable it by 

> make menuconfig

no need to enable by default in kernel_config

**Comment by thagabe** [comment]
If mvebu has UASP then it should be auto-enabled by selecting Kernel >> Can-Storage >> Marvell-sata

**Comment by ptpt52** [comment]
well, if that is your wish. just do it like this:

```
diff --git a/target/linux/mvebu/image/Makefile b/target/linux/mvebu/image/Makefile
index f0c4b09..05f1e17 100644
--- a/target/linux/mvebu/image/Makefile
+++ b/target/linux/mvebu/image/Makefile
@@ -119,7 +119,9 @@ define Device/linksys-wrt3200acm
   $(call Device/linksys,WRT3200ACM (Rango))
   $(Device/armada-385-linksys)
   DEVICE_DTS := armada-385-linksys-rango
-  DEVICE_PACKAGES += kmod-btmrvl kmod-mwifiex-sdio
+  DEVICE_PACKAGES += kmod-btmrvl kmod-mwifiex-sdio \
+                                        kmod-ata-core kmod-ata-marvell-sata \
+                                        kmod-usb-storage-uas
 endef
 TARGET_DEVICES += linksys-wrt3200acm
 
```

**Comment by thagabe** [comment]
^ this looks like the right solution

**Comment by neheb** [comment]
NACK

The USB interface does not support UASP at all. I've tested with 6 different enclosures and none use UASP whereas they do on my laptop.

**Comment by diizzyy** [comment]
@ptpt52 @thagabe 
Both yes and no, the downside is that it doesn't work if you're booting off a USB device as the kernel needs to have the driver and not read it off a filesystem.

@neheb 
What device and chipsets did you use for testing?

**Comment by neheb** [comment]
Turris Omnia. it's based on a WRT1900ACS platform minus the WiFi. The upstream kernel driver does not use streams and as such cannot support UAS. I'd love to be proven wrong though.

There are a bunch of USB related debug messages in the kernel but I have no idea how to enable them. They should show why UAS doesn't work.

**Comment by thagabe** [comment]
Was this ever transferred to the new repo?

**Comment by bobafetthotmail** [comment]
no, but you can install the kmod-usb-storage-uas module. It seems none above confirmed that it is actually supported by their devices.

**Comment by thagabe** [comment]
Got it, thank

**Pull request closed without merging**
