### PR TITLE
busybox: update to version 1.26.2

### PR DESCRIPTION
**Pull request by bladeoner**
Busbox updated to version 1.26.2, thanks to Magnus Kroken for making the necessary changes.

Upstream patches removed:
002-libbb-send_to_from-do-not-require-that-to-should-hav.patch
102-trylink_mktemp_fix.patch
302-netlink-alignment.patch
03-ip-route-fix-high-table-ids.patch

Compiled and tested on ar71xx.

Signed-off-by: Etienne Haarsma <bladeoner112@gmail.com>

### CODE REVIEW

**Comment by bladeoner** [comment]
Also submitted here: http://patchwork.ozlabs.org/patch/711163/

**Comment by bladeoner** [comment]
Signed it off.

**Comment by bittorf** [comment]
i think we should wait for 1.26.2 - there are two bugfixes in the pipeline...

**Comment by stintel** [comment]
I don't agree we should wait for 1.26.2... As we're preparing for release, we either want this in ASAP so that we can find potential bugs sooner, or we wait until after branching. If those 2 patches are important we can add them anyway.

Aside from that: please squash all commits into a single one. Your first commit breaks compilation due to patches not applying, and the problem is only solved 4 commits later. This should be avoided.

**Comment by bittorf** [comment]
1.26.2 is out - please send a new pullrequest

**Comment by stintel** [comment]
No. Please update this PR instead.

**Comment by bladeoner** [comment]
@stintel the PR is updated to version 1.26.2.

**Comment by stintel** [comment]
Please squash the commits. There should be only one.

**Comment by stintel** [comment]
Now you have unrelated changes in your PR...
Please rebase on master first.

**Comment by bladeoner** [comment]
@stintel sorry that it took some time but I think it's done, please verify.

**Comment by stintel** [comment]
No worries, looks good now. I just wonder, why all the changes in the Config.in files? I'm not that familiar with busybox tbh, last time I bumped it (859d30d5211be15666ebf2f0dc780f89409fa28f), this wasn't necessary. But that was a minor version bump of course.

**Comment by bladeoner** [comment]
@stintel From 1.25.1 to 1.26.0 not a lot changed (some patches needed to be adjusted) but from 1.26.0 to 1.26.1 they changed the name of config references:
https://git.busybox.net/busybox/commit/?h=1_26_stable&id=28251dfa64a999c69605471863a2bb8692bfc7b3

I was able to upgrade but not get it stable I got some Ash errors.

But Magnus Kroken had it fixed and send it to the Patchwork.

I just tested and did a PR

**Comment by nbd168** [comment]
The busybox update is in my staging tree

**Pull request closed without merging**
