### PR TITLE
source: Switch to xz for packages and tools where possible

### PR DESCRIPTION
**Pull request by diizzyy**
* Change git packages to xz
* Update mirror checksums in packages where they are used
* Change a few source tarballs to xz if available upstream
* Remove unused lines in packages we're touching, requested by jow- and blogic
* We're relying more on xz-utils so add official mirror as primary source, master site as secondary.
* Add xz-utils to make prereq
* Add SHA256 checksums to multiple git tarball packages

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Tarballs to be uploaded can be found at this URL: http://projects.pyret.net/dump/lede/xz/

**Comment by diizzyy** [comment]
Continuation of #361

**Comment by diizzyy** [comment]
@blogic

**Comment by jow-** [comment]
Staged in my tree: https://git.lede-project.org/fc91de1 - https://git.lede-project.org/542371e - https://git.lede-project.org/ee88169

**Pull request closed without merging**
