### PR TITLE
Zyxel P2812HNUFx wireless patch 

### PR DESCRIPTION
**Pull request by Markismus**
The current build from LEDE did not provide WiFi, while an older OpenWrt fork by ScApi does provide WiFi. After being given a few pointers (https://github.com/ScApi/P2812HNUFx/issues/2#issuecomment-269076542), I was able to copy and test his additions on the newest LEDE build. WiFi works now.

### CODE REVIEW

**Comment by Borromini** [comment]
Hi!

I don't have the chops to comment on the actual code, but I see you're adding new files into etc/uci-defaults/, which is meant for 'custom' additions.

Board support now gets added to etc/board.d/, where you'll find `01_leds` and `02_network`. You should integrate your extra code into those existing scripts.

See https://lede-project.org/docs/guide-developer/adding_new_device for more info. A few things changed from (stable) OpenWrt to LEDE.

**Comment by Markismus** [comment]
I've ran over the scripts and there has been a lot of changes in them since ScApi's fork of Openwrt. So I've moved his '03_wireless-wps' to 'etc/board.d', deleted the 'uci-defaults' with the older scripts and ran 'make'. I'll test whether this works. If not, I'll replace the newer scripts with the working ones from ScApi.

**Comment by Markismus** [comment]
I have never been able to test the DSL aspect of the router-modem, since my IPS doesn't allow me to use a custom router. So this patch doesn't address this.

Still, this patch does add a eeprom binary file called `vdsl.bin`. And in ScApi's `etc/uci-defaults/01_network` there are a few lines--that I can't test-- about the modem. For anyone who runs into trouble with the modem, I'll give them here for reference:
```
set_adsl_modem() {
	local annex=$1
	local firmware=$2
	uci batch <<EOF
set network.dsl='adsl'
set network.dsl.annex='$annex'
set network.dsl.firmware='$firmware'
EOF
}

set_vdsl_modem() {
	local annex=$1
	local firmware=$2
	local tone=$3
	local xfer_mode=$4
	uci batch <<EOF
set network.dsl='vdsl'
set network.dsl.annex='$annex'
set network.dsl.firmware='$firmware'
set network.dsl.tone='$tone'
set network.dsl.xfer_mode='$xfer_mode'
EOF
}
```

**Comment by mkresin** [comment]
I'm sorry to say, but the whole approach is wrong.

First of all, most of the files in your PR are not related to the topic:

- the vdsl firmware is provided by ```package/firmware/lantiq/dsl-vrx200-firmware-xdsl```
- a wps button handler gets installed with ```package/network/services/hostapd```
- the ```10-rt2x00-eeprom``` hotplug script isn't required any more and was removed intentionally with commit 7fd5171a3445b1f0b3aaa45f6c43550758547f2c

If the EEPROM files are really required, you should create packages for the files. The way you are doing it now, the files are copied ot the images of all lantiq boards albeit they are not required for all boards.

The last and most important point is that the ralink EEPROM files contain beside hardware information (which band can be uses for example) also board individual wireless calibration data. For that reason the files are usually board individual and stored somewhere on flash. If you have a look 7fd5171a3445b1f0b3aaa45f6c43550758547f2c you will see that they get extracted from flash.

The question is where are the EEPROM+caldata on the flash of the Zyxel P2812HNUF1 and why are they not extracted from the flash. Please get in touch with ScApi or ask him to comment either on this PR or on the [related bug report](https://bugs.lede-project.org/index.php?do=details&task_id=469).

**Comment by Markismus** [comment]
ScApi is not replying very frequently, so asking him is unlikely to result in a quick resolve. I've posted in his fork about the PR.

Looking at the bug report and comparing to my messages, I see:
```
dmesg |grep "ieee80211"
[   12.388182] ieee80211 phy0: rt2x00lib_request_eeprom_file: Info - Loading EEPROM data from 'RT3062.eeprom'.
[   12.521039] ieee80211 phy0: rt2x00_set_rt: Info - RT chipset 3572, rev 0223 detected
[   12.527449] ieee80211 phy0: rt2x00_set_rf: Info - RF chipset 0008 detected
[   12.535399] ieee80211 phy0: Selected rate control algorithm 'minstrel_ht'
[  203.051888] ieee80211 phy0: rt2x00lib_request_firmware: Info - Loading firmware file 'rt2860.bin'
[  203.209212] ieee80211 phy0: rt2x00lib_request_firmware: Info - Firmware detected - version: 0.40
```

So it seems that the firmware is loaded from the flash.

**Comment by mkresin** [comment]
The bug report is about the very same problem. ```Loading EEPROM data from 'RT3062.eeprom'``` means that the RT3062.eeprom file is loaded from the filesystem. Most likely because the bug reported has copied the file from ScApis repository to his router.

**Comment by Markismus** [comment]
Yes, I can reproduce that. If I remove `\lib\firmware\RT3602.eeprom`, I get:
```
[   12.399554] ieee80211 phy0: rt2x00lib_request_eeprom_file: Info - Loading EEPROM data from 'RT3062.eeprom'.
[   12.410075] rt2800pci 0000:00:0e.0: Direct firmware load for RT3062.eeprom failed with error -2
[   12.417762] rt2800pci 0000:00:0e.0: Falling back to user helper
[   12.640275] firmware RT3062.eeprom: firmware_loading_store: map pages failed
[   12.646291] ieee80211 phy0: rt2x00lib_request_eeprom_file: Error - Failed to request EEPROM.
[   12.654586] rt2800pci: probe of 0000:00:0e.0 failed with error -11
```
However, these messages do not relate to a failure to extract the data from the flash. Looking at 10-rt2x00-eeprom, 11-ath10k-caldata and 12-ath10k-caldata, I don't see any function call to an _eeprom_extract() for P2812HNUF1. So where in the code should the eeprom extraction take place?

**Comment by Markismus** [comment]
Looking at the flash memory from Uboot:
```
mtdparts
mtdparts variable not set, see 'help mtdparts'
no partitions defined

defaults:
mtdids  : nand0=nand
mtdparts: mtdparts=nand:256k(uboot),128k(uboot_env),-@0x60000(rootfs);
```
, I remember writing the image from openwrt at 60000 in[step 4](https://wiki.openwrt.org/toh/zyxel/p2812hnu-f1). So where would the firmware partition be?

**Comment by mkresin** [comment]
> However, these messages do not relate to a failure to extract the data from the flash. Looking at 10-rt2x00-eeprom, 11-ath10k-caldata and 12-ath10k-caldata, I don't see any function call to an _eeprom_extract() for P2812HNUF1. So where in the code should the eeprom extraction take place?

That is the point. The extraction of the EEPROM was never added for the Zyxel P2812HNU-F1/F3. I've no idea where the EEPROM is stored on flash. Might be that you overwrote the EEPROM during the LEDE installation. That is why you should get in contact with ScApi. He provides the EEPROM files for download, and he send the initial Zyxel P2812HNU-F1/F3 support patch.

**Comment by mkresin** [comment]
I will close this due to inactivity. Please reopen the PR if you have the time to fix the outlined issues.

**Comment by ScApi** [comment]
P2812HNUFx never had cal data in flash, it was extracted from sources provided by Zyxel, whole flash dump was analysed by couple of people looking for it with no luck. As it is board specific the best way is to create  separate packages for F1 and F3, if I find some time and hardware then I will try to fix and clan these

**Pull request closed without merging**
