### PR TITLE
uClibc-ng: update to 1.0.21

### PR DESCRIPTION
**Pull request by bladeoner**
uClibc-ng: update to 1.0.21

Signed-off-by: Etienne Haarsma <bladeoner112@gmail.com>

### CODE REVIEW

**Comment by stintel** [comment]
Missing SoB, please read https://lede-project.org/docs/guide-developer/the-source-code#submitting_patches

**Comment by bladeoner** [comment]
@stintel sorry but applying patches is new for me, I read the article but what is the easiest way to correct this? And do I need to change it on the branch or on the pull request?

Thanks in advance.

This also applies for pull request: #679

**Comment by dedeckeh** [comment]
@bladeoner On the branch bladeoner-uuClibc-ng1.0.21 do the following

git commit --amend -signoff => Will add your signoff to the commit
git push -f => Will do a forced update of the commit and will update the PR at the same time

**Comment by bladeoner** [comment]
@dedeckeh thank you for explaining, I think I just signed it off, could you please verify?

**Comment by dedeckeh** [comment]
@bladeoner The author field of the patch and the SoB line need to be identical which is currently not the case

**Comment by bladeoner** [comment]
@dedeckeh I just changed the author field, please verify.

**Comment by dedeckeh** [comment]
@bladeoner You must signoff with your real name and the Author field and the SoB must be the same.

**Comment by bobafetthotmail** [comment]
@bladeoner look at the draft of the pull request template here https://github.com/lede-project/source/pull/592/commits/c7cfdff4fa40f53511b8c8a4bd2e60aa980dc6fd

**Comment by bladeoner** [comment]
@dedeckeh @bobafetthotmail sorry for the hold up, but the Author field, is that my first message?

I hope I did correct now...

**Comment by bobafetthotmail** [comment]
The author field of the commit is set by your local git by reading your local name and local email git settings. Set the local git to use right name and email (use same name and email you write in the Signed-off-by line)

   git config --global user.name "my name" 
   git config --global user.email "my@email.address"

then delete and make again the commit so it will have the right author field.

**Comment by bladeoner** [comment]
@bobafetthotmail I followed your instructions:
git config --global user.name "my name"
git config --global user.email "my@email.address"

then delete and make again the commit so it will have the right author field.

Can you please check if this is correct?
Thanks in advance.

**Comment by jow-** [comment]
Pulled into my staging tree: https://git.lede-project.org/d5db655

**Pull request closed without merging**
