### PR TITLE
ath10k-firmware: update qca9984 firmware

### PR DESCRIPTION
**Pull request by dissent1**
Bump qca9984 firmware.

Nothing noticeable. Running for almost a week without issues.

### CODE REVIEW

**Comment by nbd168** [comment]
Merged to my staging tree, thanks.

**Comment by hnyman** [comment]
With the newest few firmwares I have noticed garbage in the kernel log regarding the "board data", and that looks a bit suspicious.

One of the radios may display the "failed to fetch board data" line with garbage after "cafe". My guess is that the message string gets handled without a terminating 0. 

The garbage may change place from radio0 to radio1 if you reboot the device, so it is not related to a specific radio firmware / board data. That makes my think that the fault might be on the ath10k side, where possibly some function fetches the string to uninitialised memory buffer but does not ensure that it is terminated properly. (But I am not sure which component is responsible for those log lines)

```
[   22.896652] ath10k_pci 0001:01:00.0: failed to fetch board data for bus=pci,vendor=168c,device=0046,subsystem-vendor=168c,subsystem-device=cafe???C?p??=F?H??=F?>F from ath10k/QCA9984/hw1.0/board-2.bin

More context:

[   22.320695] ath10k_pci 0001:01:00.0: enabling device (0140 -> 0142)
[   22.320810] ath10k_pci 0001:01:00.0: enabling bus mastering
[   22.321320] ath10k_pci 0001:01:00.0: pci irq msi oper_irq_mode 2 irq_mode 0 reset_mode 0
[   22.460083] ath10k_pci 0001:01:00.0: Direct firmware load for ath10k/pre-cal-pci-0001:01:00.0.bin failed with error -2
[   22.460124] ath10k_pci 0001:01:00.0: Falling back to user helper
[   22.624103] firmware ath10k!pre-cal-pci-0001:01:00.0.bin: firmware_loading_store: map pages failed
[   22.624316] ath10k_pci 0001:01:00.0: Direct firmware load for ath10k/cal-pci-0001:01:00.0.bin failed with error -2
[   22.632138] ath10k_pci 0001:01:00.0: Falling back to user helper
[   22.879117] ath10k_pci 0001:01:00.0: qca9984/qca9994 hw1.0 target 0x01000000 chip_id 0x00000000 sub 168c:cafe
[   22.879176] ath10k_pci 0001:01:00.0: kconfig debug 0 debugfs 1 tracing 0 dfs 1 testmode 1
[   22.893856] ath10k_pci 0001:01:00.0: firmware ver 10.4-3.4-00072 api 5 features no-p2p,mfp,peer-flow-ctrl,btcoex-param,allows-mesh-bcast crc32 75ec955f
[   22.896652] ath10k_pci 0001:01:00.0: failed to fetch board data for bus=pci,vendor=168c,device=0046,subsystem-vendor=168c,subsystem-device=cafe???C?p??=F?H??=F?>F from ath10k/QCA9984/hw1.0/board-2.bin
[   22.909876] ath10k_pci 0001:01:00.0: board_file api 1 bmi_id N/A crc32 dd636801
[   24.270892] ath10k_pci 0001:01:00.0: htt-ver 2.2 wmi-op 6 htt-op 4 cal file max-sta 512 raw 0 hwcrypto 1
[   24.349443] ath: EEPROM regdomain: 0x0
[   24.349470] ath: EEPROM indicates default country code should be used
[   24.349486] ath: doing EEPROM country->regdmn map search
[   24.349510] ath: country maps to regdmn code: 0x3a
[   24.349528] ath: Country alpha2 being used: US
[   24.349544] ath: Regpair used: 0x3a
```

**Comment by hnyman** [comment]
Possibly the garbage is coming from compat-wireless, where function "ath10k_core_fetch_board_file" calls "ath10k_core_fetch_board_data_api_n" that uses the boardname, which is originally created by "ath10k_core_create_board_name".

I haven't looked closer into the deeper data structures, so it might be that "ar->id.subsystem_device" already contains garbage.

From compat-wireless-2017-01-31/drivers/net/wireless/ath/ath10k/core.c :

```
static int ath10k_core_create_board_name(struct ath10k *ar, char *name,
                                         size_t name_len)
{
        /* strlen(',variant=') + strlen(ar->id.bdf_ext) */
        char variant[9 + ATH10K_SMBIOS_BDF_EXT_STR_LENGTH];

        if (ar->id.bmi_ids_valid) {
                scnprintf(name, name_len,
                          "bus=%s,bmi-chip-id=%d,bmi-board-id=%d",
                          ath10k_bus_str(ar->hif.bus),
                          ar->id.bmi_chip_id,
                          ar->id.bmi_board_id);
                goto out;
        }

        if (ar->id.bdf_ext[0] != '\0')
                scnprintf(variant, sizeof(variant), ",variant=%s",
                          ar->id.bdf_ext);

        scnprintf(name, name_len,
                  "bus=%s,vendor=%04x,device=%04x,subsystem-vendor=%04x,subsystem-device=%04x%s",
                  ath10k_bus_str(ar->hif.bus),
                  ar->id.vendor, ar->id.device,
                  ar->id.subsystem_vendor, ar->id.subsystem_device, variant);
out:
        ath10k_dbg(ar, ATH10K_DBG_BOOT, "boot using board name '%s'\n", name);

        return 0;
}
```

**Comment by dissent1** [comment]
Newer board-2.bin (from branch 3.4) has been introduced with https://github.com/lede-project/source/commit/b650112b65f741aa3235ab7f648c66d587bd8217
If you revert it to previous state (branch 3.3) does that garbage stays on?

**Comment by hnyman** [comment]
I tested both 3.4-0074 and 3.3-102, but got garbage output with both.

```
3.4-0074

[   20.719467] ath10k_pci 0000:01:00.0: firmware ver 10.4-3.4-00074 api 5 features no-p2p,mfp,peer-flow-ctrl,btcoex-param,allows-mesh-bcast crc32 fa32e88e
[   20.737153] ath10k_pci 0000:01:00.0: failed to fetch board data for bus=pci,vendor=168c,device=0046,subsystem-vendor=168c,subsystem-device=cafe???C?w?B?=F?H??=F?>F from ath10k/QCA9984/hw1.0/board-2.bin
[   20.740010] ath10k_pci 0000:01:00.0: board_file api 1 bmi_id N/A crc32 dd636801

3.3-102

[   22.169306] ath10k_pci 0001:01:00.0: firmware ver 10.4-3.3-00102 api 5 features no-p2p,mfp,peer-flow-ctrl,btcoex-param crc32 6120b2da
[   22.175561] ath10k_pci 0001:01:00.0: failed to fetch board data for bus=pci,vendor=168c,device=0046,subsystem-vendor=168c,subsystem-device=cafe▒▒▒C▒▒▒▒▒▒=Fݴ▒H▒▒=F▒L>F from ath10k/QCA9984/hw1.0/board-2.bin
[   22.187385] ath10k_pci 0001:01:00.0: board_file api 1 bmi_id N/A crc32 dd636801
```

It is enough to edit the ath10k-firmware Makefile and do  ` make package/ath10k-firmware/{clean,compile} ` and then just opkg install the ath10k-firmware-qca9* packages, right?

**Comment by dissent1** [comment]
Seems you've reverted the firmware but not board file. It's board data related.
Download board-2.bin from here https://source.codeaurora.org/quic/qsdk/oss/firmware/ath10k-firmware/plain/ath10k/QCA9984/hw1.0/board-2.bin?id=16a4e6050ced778872e667db28d176a40b2f6110

and place it in the router into /lib/firmware/ath10k/qca9984/hw1.0/ over the existing one. Reboot and check dmesg.

**Pull request closed without merging**
