### PR TITLE
hostapd: ft_psk_generate_local support

### PR DESCRIPTION
**Pull request by c-e-p-x-u-o**
Support for ft_psk_generate_local wireless config.

Signed-off-by: Sergio <mailbox@sergio.spb.ru>

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello @c-e-p-x-u-o,

Please, read our [submitting patches rules](https://lede-project.org/submitting-patches), and make sure your pull request follows them. Your commit is missing a proper prefix, description and SoB line.

Cheers,
Piotr

**Comment by c-e-p-x-u-o** [comment]
Sorry. Is it better now?

**Comment by pepe2k** [comment]
> Sorry. Is it better now?

Nope :(

**Comment by c-e-p-x-u-o** [comment]
Could you help me, please.
Have I changed subject and description and it's still not correct. Or I haven't changed them at all?

**Comment by pepe2k** [comment]
> Could you help me, please.

You need to update your commit, not just the Pull Request. Please, refer to [git documentation for details about amending](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History).

Cheers,
Piotr

**Comment by c-e-p-x-u-o** [comment]
Can I do it from git hub web interface?

**Comment by pepe2k** [comment]
> Can I do it from git hub web interface?

I'm sorry but I don't use GitHub web interface, I have no idea.

Cheers,
Piotr

**Comment by hauke** [comment]
A similar change was merged in #1351 into master.

**Pull request closed without merging**
