### PR TITLE
curl: Switch default TLS library to mbedTLS

### PR DESCRIPTION
**Pull request by neheb**
luci-ssl has already made the switch since mainline support for PolarSSL is almost over (2016).

### CODE REVIEW

**Comment by hnyman** [comment]
I think that you should also increase PKG_RELEASE in Makefile.

**Comment by diizzyy** [comment]
mbedTLS 1.3 support should be dropped entirely, we don't want to have unmaintained code in the tree that's going to be a security issue.

**Comment by neheb** [comment]
Fixed. Will also do a pull request on px5g.

**Comment by diizzyy** [comment]
@neheb 
Already done :-)

**Comment by diizzyy** [comment]
@neheb 
Please remove all references (options) to use PolarSSL (mbed TLS 1.3).
The rest of the work is in #655

**Comment by neheb** [comment]
Adjusted commit message. I think that's it.

**Comment by hnyman** [comment]
This needs to be rebased, as @hauke updated curl to 7.52.1 with 1436e1548881a8e196eeb25c7c807e2c3d65caf1

**Comment by jow-** [comment]
Pulled into my staging tree: https://git.lede-project.org/4360320

**Comment by jow-** [comment]
Rebased and line-wrapped: https://git.lede-project.org/e021ae6

**Comment by hnyman** [comment]
> Rebased and line-wrapped: https://git.lede-project.org/e021ae6

@jow- 
minor thing, but the new patch likely needs to be refreshed due to the version bump
(based on line number difference in new/deleted patch: 712 vs. 724)

**Comment by jow-** [comment]
@hnyman - ack, refreshed.

**Pull request closed without merging**
