### PR TITLE
Add Support for Archer C58

### PR DESCRIPTION
**Pull request by prisma01**
ar71xx: add support to TP-Link Archer C58v1  …
TP-Link Archer C58v1 is a dual-band AC1350 router, based on Qualcomm/Atheros
QCA9561+QCA9886.
Work based on C59/C60 changeset (e39dc8d823c86559eedbbdcee5f5c14b827fed0f) by Henryk Heisig <hyniu@o2.pl>

C58 Specification:

- 775/650/258 MHz (CPU/DDR/AHB)
- 64 MB of RAM (DDR2)
- 8 MB of FLASH (SPI NOR)
- 3T3R 2.4 GHz
- 2T2R 5 GHz
- 5x 10/100 Mbps Ethernet
- 6x LED , 3x button
- UART header on PCB, RX, TX at TP4+5 (Backside)

Missing:
-5GHz support due to some troubles with QCA9886 firmware

Flash instruction:
1. Set PC to fixed ip address 192.168.0.66
2. Download lede-ar71xx-generic-archer-cXX-v1-squashfs-factory.bin
and rename it to tp_recovery.bin
3. Start a tftp server with the file tp_recovery.bin in its root directory
4. Turn off the router
5. Press and hold Reset button
6. Turn on router with the reset button pressed and wait ~15 seconds
7. Release the reset button and after a short time
the firmware should be transferred from the tftp server
8. Wait ~30 second to complete recovery.

Flash instruction under U-Boot, using UART:

1. tftp 0x81000000 lede-ar71xx-...-sysupgrade.bin
2. erase 0x9f020000 +$filesize
3. cp.b $fileaddr 0x9f020000 $filesize
4. reset

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello @prisma01,

Thank you for your first-time contribution! Unfortunately, something is wrong with your PR.

Please, squash all your commits into one and rebase it on current LEDE master branch. Use `git push --force` to overwrite your GitHub repository/branch, which will afterwards update your pull request here automatically.

Cheers,
Piotr

**Comment by prisma01** [comment]
I finally managed to squash all commits into one, but for automerging to lede/master something is still missing, apparently some conflicts arose over time. I will however never understand git properly, so i will not be able to rebase and solve conflicts. My effort is over here, i have my C58 supported. If someone wants this in lede, go ahead...

**Comment by kiashan** [comment]
I all, 
i need an image for archer c58 where can i find it or how can i build my own?
I see that the problem of archer with 5ghz are solved.
Thanks

**Comment by prisma01** [comment]
> i need an image for archer c58 where can i find it or how can i build my own? 
clone this repo: git clone https://github.com/prisma01/source.git and proceed according to:
https://lede-project.org/docs/guide-developer/quickstart-build-images
> I see that the problem of archer with 5ghz are solved.
What do you mean? For this fork this is definitely not true. Maybe some new firmware in lede? Can you give me the place of your information.

**Comment by pepe2k** [comment]
@prisma01, if you are not going to fix this PR (rebase on master, drop redundant commits), please close it.

Cheers,
Piotr

**Comment by prisma01** [comment]
I changed my mind. The conflict is apparently the commit of the acher c25. So this should be quite easy, if I'll manage to fight git :-). Give me some days...

**Comment by pepe2k** [comment]
> I changed my mind. The conflict is apparently the commit of the acher c25. So this should be quite easy, if I'll manage to fight git :-). Give me some days...

Sure, take your time.
Please leave here some comment when you update your PR.

Cheers,
Piotr

**Comment by kiashan** [comment]
@prisma01 
thanks!
I've copiled and tested but no 5ghz.
I see this
https://git.lede-project.org/?p=source.git;a=commit;h=e00cc98045ac204d127d98dc882232b6982df359
it's not the same firmware?!

**Comment by heinzek** [comment]
@kiashan can You test images from my commit. I dont have C58.
I add softver part in to factory image and I think is possible to write this firmware from TP-Link GUI

https://github.com/heinzek/source/commit/fe1c155e598d58d03b100648a41191085c73c444

**Comment by kiashan** [comment]
@heinzek
I'm cloning your git and compiling. 
In few hour or tomorrow i'll let you know.

**Comment by kiashan** [comment]
Yes, I can update from TP-LINK gui, but no 5ghz.
Your branch is after 17 may or it's the same of prisma01?!

**Comment by heinzek** [comment]
@kiashan my branch is updated to current master. 5GHz is missing because firmware to QCA9888/9886 not working.

**Comment by prisma01** [comment]
How do we get your rebase work to master now? Should i close this PR and you open a new one?

**Comment by rotanid** [comment]
@prisma01 he already opened a new PR, github linked it automatically just above your comment :)

**Comment by pepe2k** [comment]
Obsoleted by https://github.com/lede-project/source/pull/1171.

Cheers,
Piotr

**Pull request closed without merging**
