### PR TITLE
linux: added LED Morse code trigger

### PR DESCRIPTION
**Pull request by greenbreakfast**
Added LED morse code trigger kernel module to buildroot:
- Addition of kernel package ledtrig-morse to led kernel modules
- Addition of kernel patch to add ledtrig-morse kernel module
  - Adds morse trigger to LED trigger kconfig file
  - Changes led drivers makefile to support compilation of morse code trigger code
  - Adds Gabor Juhos' ledtrig-morse driver implementation

Signed-off-by: Lazar Demin <lazar@onion.io>

### CODE REVIEW

**Comment by blogic** [comment]
@greenbreakfast Please add "linux :" as a prefix. We are trying to reduce the amount of patches to the kernel. we can merge the morse trigger but you would need to take care of sending it upstream for inclusion. history shows, that otherwise it will jut bit rot in our tree :/

**Comment by jow-** [comment]
I think we can package this as external kmod, no need to patch it into the kernel.

**Comment by KanjiMonster** [comment]
I want to point out that we had it until ~5 month ago and @nbd168 deleted it in 577f873dafdf3914c79ee21869288f20d419a39f - so this is currently actually a partial revert.

**Comment by greenbreakfast** [comment]
Can we go ahead with the merge since it is a partial revert?

**Comment by nbd168** [comment]
No, I don't want to add back kernel patches for this rarely used feature, if it can be avoided.

**Comment by nbd168** [comment]
FYI, you can find a packaged version here: https://github.com/openwrt/openwrt/pull/331

**Pull request closed without merging**
