### PR TITLE
lede-17.01: ramips: backport support for the GnuBee Personal Cloud One

### PR DESCRIPTION
**Pull request by pinney**
backport commit 77645ffcd9ad767be02ea6d5cfe042928a3565d1 to lede-17.01

Signed-off-by: L. D. Pinney <ldpinney@gmail.com>

### CODE REVIEW

**Comment by blogic** [comment]
please remove the merge commits

**Comment by mkresin** [comment]
And remove the permission change of target/linux/ramips/base-files/etc/board.d/01_leds. See [FS#979](https://bugs.lede-project.org/index.php?do=details&task_id=979) and f3b4e50ceec0a709e09621da518329c0111a225b

**Comment by pinney** [comment]
@blogic Rolled back the merge commits
@mkresin set 01_leds to 755

**Comment by pepe2k** [comment]
LGTM

@mkresin, any other comments or can we merge it?

Cheers,
Piotr

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Comment by pinney** [comment]
I'm certain the workload is up because of the remerge ... but this one still seems OK to merge.

**Pull request closed without merging**
