### PR TITLE
generic: refreshed some stuff

### PR DESCRIPTION
**Pull request by kdarbyshirebryant**
Changed some stuff

Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>

### CODE REVIEW

**Comment by commodo** [comment]
This patch seems to do too much in one go.

I'm also seeing a kernel version bump

**Comment by kdarbyshirebryant** [comment]
You want me to split out each change into individual commit?  OK, no prob.

**Comment by bobafetthotmail** [comment]
I think "refreshed some stuff" is a bit useless, titles and descriptions should explain what was done, at least. 
See the patch submitting guidelines https://lede-project.org/submitting-patches

**Comment by kdarbyshirebryant** [comment]
What you mean like this one? https://git.lede-project.org/?p=source.git;a=commit;h=83e4ed3497d40dc7da9d2d2c2febbf6272815c51

**Comment by commodo** [comment]
That patch looks like some old maintainer/contributor being lazy.

I have no strong opinion on a debate about that.

I just try to do my best about my work.
In the sense that "my work is my calling card" ; and "what do I want my
work to say about me as a person ?" type of thinking :)

**Pull request closed without merging**
