### PR TITLE
curl: Update to 7.53.1

### PR DESCRIPTION
**Pull request by diizzyy**
Update curl to 7.35.1
Remove 001-curl-https-openssl-fix.patch as it's merged upstream
Update mirror list, add main site as last resort
Source: https://github.com/curl/curl-www/blob/master/latest.pl

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile-tested on Octeon (MIPS64)

**Comment by blogic** [comment]
there are 2 commits in the branch ?

**Comment by diizzyy** [comment]
Only one? I just refreshed the pull req fixing URLs.

**Comment by diizzyy** [comment]
Run-tested on Octeon (MIPS64)

**Comment by diizzyy** [comment]
@hauke 
Please fix the mirror list too

**Comment by riptidewave93** [comment]
@diizzyy Seems like your patch was superseded in https://github.com/lede-project/source/commit/c481774298246c2bc2d2c66fa736ce2d4cae69d1.

**Comment by diizzyy** [comment]
@riptidewave93 
So it seems, unfortunately the mirror list is broken so I'll leave it open for the committer to pull those changes.

**Pull request closed without merging**
