### PR TITLE
tools: add package autoconf-archive

### PR DESCRIPTION
**Pull request by kelvincheung**
Add package autoconf-archive to support autoconf macros.

Signed-off-by: Keguang Zhang <keguang.zhang@spreadtrum.com>

### CODE REVIEW

**Comment by wongsyrone** [comment]
why not update to latest version: autoconf-archive-2017.03.21.tar.xz

**Comment by kelvincheung** [comment]
@wongsyrone 
I think autoconf-archive should go with autoconf.
At present autoconf remains 2.69, which is not the latest version either.

**Comment by wongsyrone** [comment]
It's just a collection of freely re-usable Autoconf macros, latest autoconf can handle it.

**Comment by diizzyy** [comment]
Why should this be added?

**Comment by hauke** [comment]
@kelvincheung Please describe why this is needed like @diizzyy  said

**Comment by kelvincheung** [comment]
@diizzyy @hauke 
Sorry for the slow response.
This patch is to support the building of packages that uses autoconf macros such as ODP.
Actually I am going to submit patches of ODP to the feeds repository next.
So autoconf-archive is the prerequisite.

**Comment by diizzyy** [comment]
ODP being?

**Comment by kelvincheung** [comment]
@diizzyy 
I mean [OpenDataPlane](https://www.opendataplane.org/).

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Pull request closed without merging**
