### PR TITLE
mwlwifi: update to version 10.3.4.0 / 2017-11-29

### PR DESCRIPTION
**Pull request by anomeome**
Lastest stamped version
Compile / test on target mvebu / rango

Signed-off-by: Kabuli Chana <newtownBuild@gmail.com>

### CODE REVIEW

**Comment by diizzyy** [comment]
LGTM

**Comment by lucize** [comment]
the one seems to be stable, didn't had a crash, but is still early

**Comment by lucize** [comment]
@hauke this one should go in ASAP, stable too, no more crash on 5Ghz with this !

**Comment by throbulator** [comment]
I can also confirm this fixes the recent crashes for WRT3200ACM.

Tested with current trunk and latest stable.

**Comment by diizzyy** [comment]
@anomeome 
Please bump this to the latest commit in upstream

**Comment by rs-se** [comment]
I also confirm no issues, we need this new driver ASAP.

**Comment by nbd168** [comment]
Merged to my staging tree, thanks.

**Pull request closed without merging**
