### PR TITLE
hostapd: Disable OBSS scan when fixed_freq is set

### PR DESCRIPTION
**Pull request by edwardkc**

### CODE REVIEW

**Comment by wongsyrone** [comment]
Do you send this to upstream?

**Comment by edwardkc** [comment]
Yes

**Comment by mkresin** [comment]
I can not find your patch in the [hostapd patchwork](https://patchwork.ozlabs.org/project/hostap/list/?state=%2A&archive=both). Woudl you please provide a link!

**Comment by edwardkc** [comment]
I only put the patch in lede upstream, but do not put it on hostapd patch.

**Comment by mkresin** [comment]
The upstream wongsyrone talked about is the hostapd project. Please send the patch to hostapd first.

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Pull request closed without merging**
