### PR TITLE
Xfsprofs: Update to 4.9.0

### PR DESCRIPTION
**Pull request by Ansuel**
Bump to last version and rework some patch

Compiled with success

With the help of Ralph Sennhauser <ralph.sennhauser@gmail.com>

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by blogic** [comment]
it looks like the compile options were changed and some patches dropped. please fully describe/explain what changes were made and why.

**Comment by nbd168** [comment]
I think the `$(MAKE) -C $(PKG_BUILD_DIR) configure` call should be done in Build/Configure, not Build/Prepare

**Comment by nbd168** [comment]
This is obviously untested. Now it doesn't run the regular configure anymore, the PKG_HASH doesn't match (it's for the wrong file), and even after fixing that it runs into build errors.

**Comment by Ansuel** [comment]
@nbd168  I know, i am fixing it... anyway i think it's better to close this 
My bad

**Pull request closed without merging**
