### PR TITLE
ramips : add support for PandoraBox D1

### PR DESCRIPTION
**Pull request by hbl0307106015**
This pull request is about adding support for PandoraBox D1 (MT7688AN based) under ramips target.

### CODE REVIEW

**Comment by blogic** [comment]
both commits are missing the Signed-off-by line.

**Comment by hbl0307106015** [comment]
@blogic   Signed-off-by lines are added. Thank you.

**Comment by blogic** [comment]
please use your real name in the Signed-off-by line and not a nickname.

**Comment by hbl0307106015** [comment]
@blogic  replaced with my real name.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
