### PR TITLE
samba4x: add new package

### PR DESCRIPTION
**Pull request by hbl0307106015**
This pull request adds the initial support for latest stable samba project. Since the samba36 does really fit to embedded system which flash size is limited, I think making samba4x and samba36 coexist is a better chioce. By the way, new samba4x seems to require at least 32MB flash size :-).

Maintainer: nbd
Compile tested: x86_64, x86_64 relevant machine, LEDE latest
Compile tested via C Library: both musl and glibc. :-)

Signed-off-by: BangLang Huang banglang.huang@foxmail.com

### CODE REVIEW

**Comment by diizzyy** [comment]
There's a branch here which makes it more embedded friendly
https://github.com/wongsyrone/lede-1/tree/master/package/external/samba44related/samba44

**Comment by hbl0307106015** [comment]
@diizzyy  In comparation with the branch you referenced, I prefer to use internal heimdal module rather than external. It seems that using internal module is more stable and acceptable, like NTFS-3g using internal fuse library as default.
On the other hand, I just want to make samba to be OOTB (out of the box).   :-) .

**Comment by diizzyy** [comment]
Well, it slims down Samba to ~5-6mbyte compared to yours which is 4-5x more?

**Comment by hbl0307106015** [comment]
@diizzyy  Yes, I tried my best.  Is there any suggestions or tips ?

**Comment by lucize** [comment]
You could add an option to use the external or the internal module and make the smallest one the default

**Comment by diizzyy** [comment]
@hbl0307106015 
While I think the other package is much more suitable I don't like the huge amount of patching and there's something wonky with heimdal too as it will fail during rebuilds I think it's a good way to move forward and perhaps adapt a few things such as the multicall binary stuff.

**Comment by buliaoyin** [comment]
The lastest samba4 beta version added --disable-python built option, maybe this option would revive the package size?

**Comment by hbl0307106015** [comment]
@buliaoyin thank you, this is a good news, it would be better if the option released with 4.7.0-stable version.

**Comment by hauke** [comment]
Samba 4.7 should get release on September 21 2017
How big is the samba 4.X package now and how big would it be with the patches which @diizzyy linked?

**Comment by diizzyy** [comment]
Samba 4.4.14 - 4.9M on ar71xx and 5M on mvebu

ar71xx: 5073284 bytes
mvebu: 5184299 bytes

**Comment by wongsyrone** [comment]
Good to see you guys are taking care of it. I'm not using it for a long time but I would like to help if any information is needed. Please check these two issues to get more info.

https://github.com/wongsyrone/lede-1/issues/25
https://github.com/wongsyrone/lede-1/issues/26

**Comment by hbl0307106015** [comment]
banglang@banglang-PC:~/work/lede/x86$ ls -lh bin/packages/x86_64/base/samba4x-server_4.6.7-1_x86_64.ipk 
-rw-r--r-- 1 banglang banglang **6.6M** Sep 21 16:38 bin/packages/x86_64/base/samba4x-server_4.6.7-1_x86_64.ipk

**Comment by hbl0307106015** [comment]
@lucize  All the options which marked 'default=yes' and 'enable' are turned to 'no' and 'disable'. So this is the smallest package I could make.

**Comment by diizzyy** [comment]
@hbl0307106015 
On a fresh checkout of trunk it fails :-/

```
Checking for custom code                                                          : Could not find the python development headers
```

Adding 
```TARGET_CFLAGS+=-I$(STAGING_DIR)/usr/include/python2.7 $(TARGET_CFLAGS) ```
Fixes that issue

However:
```
[ 244/3645] Linking default/source4/heimdal_build/compile_et
/usr/bin/ld: default/lib/replace/replace_1.o: Relocations in generic ELF (EM: 40)
default/lib/replace/replace_1.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
/usr/bin/ld: default/lib/replace/replace_1.o: Relocations in generic ELF (EM: 40)
default/lib/replace/replace_1.o: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
```
And it fails

**Comment by hbl0307106015** [comment]
@diizzyy Python module is disabled now, try it again,
Let's bump to samba 4.7.0 stable :-)...

**Comment by wongsyrone** [comment]
Just some random guesses since I don't have my computer at hand.

> Python module is disabled now

The python module you referred might be those get called at runtime, the most important thing here is we want to modify waf, the build system in python, to get all it needs for cross compiling.

**Comment by hbl0307106015** [comment]
Maybe the issue is that I canceled the dependence on python-light (DEPENDS=+python-light). All right, I will recheck it from a fresh check out of LEDE.

**Comment by wongsyrone** [comment]
If you add python-light to DEPENDS, it means runtime dependency.

**Comment by wongsyrone** [comment]
> PKG_BUILD_DEPENDS:=python-light

This is build dependency, just to satisfy waf and we don't need it at runtime.

**Comment by hbl0307106015** [comment]
@wongsyrone thanks for your explanation :-). By the way, are u chinese as well ?

**Comment by diizzyy** [comment]
Fails at the exact some thing as before (arm)

**Comment by hbl0307106015** [comment]
@diizzyy how about after adding the line PKG_BUILD_DEPENDS = python-light ??

**Comment by diizzyy** [comment]
That's no it, Samba seems to compile for the wrong arch. Try arm yourself and you'll see the issue.

**Comment by KanjiMonster** [comment]
Python light is part of the external packages feed, not of LEDE itself. Base packages may not depend on packages from external feeds.

Therefore this pull request needs to be done against the OpenWrt packages feed.  In addition, I seriously doubt @nbd agreed being the maintainer. Please add yourself or find someone willing to be it.

**Comment by diizzyy** [comment]
Was going to address that once we all got it compiling but oh well ;-)

**Comment by hbl0307106015** [comment]
ls -lh bin/packages/mipsel_24kc/base/samba4x-server_4.7.0-1_mipsel_24kc.ipk 
-rw-r--r-- 1 banglang banglang **5.2M** Sep 22 17:55 bin/packages/mipsel_24kc/base/samba4x-server_4.7.0-1_mipsel_24kc.ipk

**Comment by diizzyy** [comment]
that's mips, not arm/mvebu

**Comment by hbl0307106015** [comment]
@diizzyy This is for you, :-)...
ls -lh bin/packages/arm_cortex-a9_vfpv3/base/samba4x-server_4.7.0-1_arm_cortex-a9_vfpv3.ipk 
-rw-r--r-- 1 banglang banglang **6.0M** Sep 22 20:09 bin/packages/arm_cortex-a9_vfpv3/base/samba4x-server_4.7.0-1_arm_cortex-a9_vfpv3.ipk

**Comment by hbl0307106015** [comment]
Hi @KanjiMonster , thanks for your reminding but I made it, the new samba4x package does not need external package(including python-light) feeds any more. So could you reopen this pull request ? :-)

**Comment by diizzyy** [comment]
No, python-light isn't in LEDE it's in the openwrt package repo. This is also true for tdb, gnutls for instance.

**Comment by Andy2244** [comment]
Oh nice, someone else is working on current samba 4.7 as well. Was running 4.6 with my patches (based on wongsyrone 4.x), but will try your version as well.

**Comment by hbl0307106015** [comment]
@diizzyy Sorry for my poor English :-( ...  I just wanted to say the samba4x does not need python-light any more.

**Comment by Andy2244** [comment]
If anyone is interested here is my latest samba 4.7 feed, based on @hbl0307106015 and @wongsyrone versions.

My version adds some patches to reduce nvram wear and does a full installation, so we can use vfs modules and nearly all extra samba cmd tools, since its just a few 100kb larger, than manually selecting the bins/libs.
I also still use wongsyrone external Heimdal, since hbl0307106015 big internal heimdal cross-compile patch, was to large to review properly and the external Heimdal version worked fine for me since 2 years.

I also adapted the init script to allow more samba share options, like the vfs modules, not all are exposed to the luci-ui. wongsyrone version also lowers the process priority of smbd, nmbd, which i think is usefully, so i still use this init logic.

[myfeed.zip](https://github.com/lede-project/source/files/1327317/myfeed.zip)

**Comment by avdarie** [comment]
Hi, 

Have you prevision when the package will update in official Lede package list ? Or will be only unfficial. I m interested to install in my Lamobo BananaPi R1. 

Thanks, 
Andrei Darie

**Comment by hbl0307106015** [comment]
@avdarie  here it is https://github.com/openwrt/packages/pull/4875, I pushed it to openwrt-packages repository.

**Comment by Andy2244** [comment]
cool thx to hbl0307106015 again, will see if i get time next week to add my patches/changes

**Pull request closed without merging**
