### PR TITLE
Backport latest mvebu commits from OpenWRT

### PR DESCRIPTION
**Pull request by Noltari**
Can anyone familiar with mvebu review these changes?

### CODE REVIEW

**Comment by wongsyrone** [comment]
According to https://github.com/kaloz/mwlwifi/blob/master/hostapd/README, the hostapd patch is for OpenWrt hostapd package 2016-01-15, while we have 2016-09-05, I'm not sure whether it has already been included in upstream.

I'm not sure about change in image/Makefile, other looks good.

**Comment by thagabe** [comment]
I'd recommend rolling back on the mwlwifi for now until issues have been ironed out... but hold off until someone reports issues (I'll test later)

**Comment by wongsyrone** [comment]
FYI, the firmware for new chip is missing from the previous commits, it seems Kaloz fixed this

ref: https://github.com/openwrt/openwrt/commit/67d3ba0c7c91c0a2fb0cbd768d3a75db2246de80

**Comment by Noltari** [comment]
@wongsyrone firmware fixed

**Comment by wongsyrone** [comment]
Another fix from Kaloz

https://github.com/openwrt/openwrt/commit/ce116bc6f997d8d6e6b976cacce5d4c60d705fc6

**Comment by Noltari** [comment]
@wongsyrone backported and rebased

**Comment by nbd168** [comment]
Please drop the hostapd commit. That change is already in the upstream version that LEDE uses and your commit is duplicating the code for it.

**Comment by wongsyrone** [comment]
After dropping hostapd change, I think it's time to merge this into master branch.

**Comment by Noltari** [comment]
@nbd168 done! I didn't check that... :_

**Comment by nbd168** [comment]
Added to my staging tree, thanks

**Pull request closed without merging**
