### PR TITLE
ipq806x: use generic dt-based board-detection and improved image filenames

### PR DESCRIPTION
**Pull request by luaraneda**
Use the generic board detection method:
- Board name: First compatible string from the device tree
- Board model: Model property from the device tree

Change occurrences of board name in userspace by the compatible
string, and removed target specific board detection script

Add the new board name to SUPPORTED_DEVICES, but keep the old
to support updating devices running old firmware versions.
Also, use <manufacturer>_<modelname> as image name.

The last commit it just a cosmetic change to sort boardname alphabetically, it
can be dropped if necessary.

- compile-tested: All ipq806x boards. Compared sysupgrade metadata
to ensure update is possible after the changes
- run-tested: Out of tree Asus AC58U

Signed-off-by: Luis Araneda <luaraneda@gmail.com>

### CODE REVIEW

**Comment by blogic** [comment]
looking good, i'll ask a few folks to test this on real HW

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Comment by luaraneda** [comment]
Ok. I will do it in a couple of hours.
See you on the other side :)

**Comment by pepe2k** [comment]
Superseded by https://github.com/openwrt/openwrt/pull/594.

**Pull request closed without merging**
