### PR TITLE
generic: backport upstream kernel performance patches

### PR DESCRIPTION
**Pull request by dissent1**
Backporting several upstream patches, further info is in commit/patch messages.

Compile and run tested on ipq8065.

### CODE REVIEW

**Comment by neheb** [comment]
Ack on the second. I have not tested the first.

**Comment by MartB** [comment]
Tested both on octeon, compiles and runs.

**Comment by lucize** [comment]
using this pull on x86_64 since 5 days ago, nothing unusual since then

**Comment by haruhitamako** [comment]
how to used it ?should i only patch e1cd083.patch and make. or anything should i choose?thank you

**Comment by lucize** [comment]
I see no options to be selected in the diff files so it should be straightforward

**Comment by haruhitamako** [comment]
oh! thanks

**Comment by stintel** [comment]
Going to pull this into my staging tree and run some tests with this. Since all patches were accepted upstream I do not see why we shouldn't backport them to our codebase. Thanks!

**Comment by stintel** [comment]
Pulled into my staging tree: https://git.lede-project.org/?p=lede/stintel/staging.git

**Pull request closed without merging**
