### PR TITLE
Rename files in package/utils/usbmode/data from xxxx:yyyy to xxxx-yyyy

### PR DESCRIPTION
**Pull request by btsimonh**
And modify makefile to rename them back to include colons on make.
This is to ensure that the Lede git repo can be cloned onto a Windows drive without failure.

### CODE REVIEW

**Comment by btsimonh** [comment]
@nbd - please test/approve/apply :).

**Comment by bobafetthotmail** [comment]
please add 
Signed-off-by: your real name <your email> 
in all your commit messages (not just here in the github pull request).

**Comment by btsimonh** [comment]
Actually, put a hold on applying these at all...  I'm investigating and documenting GIT file permissions attributes & the use of windows GIT tools... (see http://stackoverflow.com/questions/2517339/how-to-recover-the-file-permissions-to-what-git-thinks-the-file-should-be).

**Comment by thess** [comment]
Am I the only one who finds it hysterical that someone named @bobafetthotmail is asking someone else to use their real name? (Yes, I know this comment is probably inappropriate - sorry dude!)

**Comment by bobafetthotmail** [comment]
>Am I the only one who finds it hysterical that someone named @bobafetthotmail is asking someone else to use their real name? (Yes, I know this comment is probably inappropriate - sorry dude!)

(long stare at your post with a blank face)... I'm not getting the funny part.

I fixed the github profile to show my name, enough laughing for today.

**Comment by btsimonh** [comment]
:) and now I know who to ask when I need to actually do it for real... (hopefully soon)

**Comment by jow-** [comment]
@btsimonh - can we add `Signed-off-by: Simon Hailes <btsimonh@googlemail.com>` on your behalf or do you plan to redo the PR? The actual changes look okay.

**Comment by btsimonh** [comment]
I was considering how to document the dangers of using any windows drives with LEDE...  it's a bit of a minefield.  However, I got distracted.
But these two changes do result in the git clone not actually failing...  so yes, if you feel they are useful in the wider scope, please add the sign-off and apply.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
