### PR TITLE
mwlwifi: Update to latest source

### PR DESCRIPTION
**Pull request by anomeome**
Update mwlwifi dirver to latest version in repo.

Signed-off-by: Kabuli Chana <newtownBuild@gmail.com>

### CODE REVIEW

**Comment by thagabe** [comment]
I vote against this merge. I have experienced dropped 5GHz radio (mamba) on the latest source and I don't seem to be the only one, let's wait until the issue is ironed out.

**Comment by anomeome** [comment]
I have not witnessed any drops on 5GHz for either mamba or shelby, but I only have one 5GHz client (fruit device). Also, I have not seen any chatter on any of the forums I frequent, nor is there an open issue regarding 5GHz clients dropping connections. If you are experiencing drops, it would help if you would open an issue on the github with relevant information.

**Comment by thagabe** [comment]
@anomeome I am collecting the problem. I will say that I was running a newer kernel than the one LEDE supported at the time. I shall try again with 4.4.32 and see if I can recreate the issue.

**Comment by anomeome** [comment]
I have run 4.4.31, 4.4.32 and 4.4.33 with the latest mwlwifi and have not seen a drop. I am dropping back to 4.4.32 in order to test the mvneta patch that was pushed today, as I have experienced that slowdown. Will do some further testing with that kernel and the latest mwlwifi.

**Comment by thagabe** [comment]
kaloz/mwlwifi#122

**Comment by wongsyrone** [comment]
You can also try 4.4.34

**Comment by thagabe** [comment]
@wongsyrone I have pulled the .34 PR into my tree and has built successfully, I shall test again.

**Comment by thagabe** [comment]
kaloz/mwlwifi#122

**Comment by thagabe** [comment]
Wifi is good, must have been something else on my end! Merging this should be safe!

**Comment by wongsyrone** [comment]
Upstream has new commits to fix data sending issues.

**Comment by thagabe** [comment]
@wongsyrone lede-project/source#557

**Comment by anomeome** [comment]
@thagabe I had closed this, but then noticed that your PR was not actually current. So built, tested, reopened and updated this PR.

**Comment by anomeome** [comment]
Issue reported for rango [upstream](https://github.com/kaloz/mwlwifi/issues/124). In order to test that guy I'm gonna have to git me one of them thar free units they be giv'n'way.

**Comment by thagabe** [comment]
Looks good to commit. Closed my PR, let's merge this.

**Comment by thagabe** [comment]
seems to be having an issue when used with sqm fq_codel as indicated on the forum

**Comment by cybrnook** [comment]
I also built an image for my WRT1900ACSv1 off of latest trunk using this driver, and I had a pretty nice performance drop on my wifes PC on 5GHZ while having SQM "cake" and "piece of cake" enabled.

Compared to the 1011 driver, her PC went from a solid 107Mbps down (our max internet line) to a fluctuating 30 - 105 Mbps.....

Dropped back to 1011 driver, and all was well again.

**Comment by anomeome** [comment]
@cybrnook If seeing an issue with 10.3.2.0-20161124 version, please open an issue  with specifics [here](https://github.com/kaloz/mwlwifi/issues), to bring to attention of @yuhhaurlin.

**Comment by cybrnook** [comment]
@anomeome, when this eventually gets pushed through, maybe you want to change the commit point? When I build against the latest mwlwifi, I am using yuhhaurlin's latest commit where he fixed some typos. My Makefile uses these two reference points:
#PKG_VERSION:=10.3.2.0-20161013
PKG_VERSION:=10.3.2.0-20161124

#PKG_SOURCE_VERSION:=41db55d3872cad94763a5fa0c5f028fa1ab66f58
PKG_SOURCE_VERSION:=4d6d94784e4e5f2fb80c566412978c88ed982628

Just food for thought...

**Comment by anomeome** [comment]
@cybrnook, Thanks, I had not bothered doing anything about the more recent commits as they were all just Readme updates, and I thought with the [3200](https://github.com/kaloz/mwlwifi/issues/118) issue there may be a blob update to come. But with @Chadster766 comments today regarding things working with 4.8.15 kernel that may not be the case for that device, but now of course there is [this](https://github.com/kaloz/mwlwifi/issues/128) which may drive something :-)

**Comment by cybrnook** [comment]
Yeah...... I hope to get some time this weekend to flash back and forth to get some good troubleshooting/data collection. Wife is very busy with work today, so that of course takes priority on the wifi availability.

**Comment by cybrnook** [comment]
Outside of the "graphs/statistics" not working on this driver it seems (likely app related, not driver), I closed the performance ticket as performance was back on par with the .38 Kernel.

**Comment by robd3** [comment]
noise level reporting: should be fixed in todays driver version: 10.3.2.0-20161220

**Comment by thagabe** [comment]
#631

**Comment by nbd168** [comment]
#631 looks better than this one.

**Comment by anomeome** [comment]
Very useful feedback, the PR you had to fix up to the state of this PR looked better somehow, but no explanation as to the how it looked better, whatever "better" might mean. Good way to get people on-board. Thanks.

**Comment by blogic** [comment]
the other PR is better as 
* it only has 1 commit in the branch while yours is cluttered with merge commits
* it has a clean patch while yours has duplicate/redundant info in it

**Comment by anomeome** [comment]
so .diff yielding the correct patch is not good enough (i.e. no duplicate/redundant info)? I was under the impression that the PR would be squashed by the maintainer, is that not correct, and if not how is the correct way to do it from the submitter side? I do not think I am to close and open a new PR every-time a change happens upstream.

**Comment by jow-** [comment]
In some cases a maintainer might decide to squash commits and clean up things but when given the choice between a PR that needs fine tuning and one that can be applied as-is or between a PR that requires fixing and another PR that requires slightly less fixing, then the maintainer will opt for the one causing less work.

In this case the other PR won because:
 - it had a clean git history
 - it had a slightly more informative commit message (some contextual change log info and a testing remark)

You're right with the observation that closing and opening a new PR is not the way to update something. You can update a yet open PR by force-pushing updated changes to the branch you used to open the PR. Assuming a local Git clone, the usual work flow would be:

    # Clone your own forked tree on Github
    $ git clone https://github.com/anomeome/source.git
    $ cd source/
    # Make a feature branch just for the PR you want to make
    $ git checkout -b update-mwlwifi
    # Do your changes and commit them
    $ nano package/kernel/mwlwifi/Makefile 
    $ git add package/kernel/mwlwifi/Makefile 
    $ git commit --signoff
    # Push your feature branch to Github
    $ git push origin update-mwlwifi

Now navigate to https://github.com/anomeome/source and it should offer you a button to create a pull request. Now if someone wants a change from you, go into your local clone and amend your changes.

    # Move back into your cloned source
    $ cd source/
    # Checkout the feature branch
    $ git checkout update-mwlwifi
    # Edit your files again, incorperate the wanted changes
    $ nano package/kernel/mwlwifi/Makefile 
    # Amend your commit (means merge the latest changes with those already present in the commit)
    $ git add package/kernel/mwlwifi/Makefile 
    $ git commit --amend
    # Force-push your rewritten history back to Github
    $ git push origin update-mwlwifi --force

At this point your pull request commits are automatically updated.

**Comment by anomeome** [comment]
surely I don't have to use nano [/joke]. Thanks, I will try again with some other mundane change, just trying to get a handle on the process, especially git which is a different beast than what I am used to.

**Comment by thagabe** [comment]
@jow- @nbd168 also stated on my PR that we should test if it builds then update PKG_MIRROR_HASH (something I didn't know about until he pointed it out). 
```
$ nano package/kernel/mwlwifi/Makefile 
.
.
.
$ make package/mwlwifi/clean V=s
$ make package/mwlwifi/prepare V=s
$ make package/mwlwifi/build V=s
$ make package/mwlwifi/check FIXUP=1
.
.
.
$ git add package/kernel/mwlwifi/Makefile 
```

**Comment by anomeome** [comment]
If you put .diff on the URL and look at the patch generated by my PR you will see that I had updated the PKG_MIRROR_HASH. Which is why I posed the question, if  having to fix up your PR but not mine, why was the choice made to push yours.

**Comment by thagabe** [comment]
Good point, no idea haha

**Comment by nbd168** [comment]
@anomeome, I only accept pull requests that I can pick properly without having to do lots of hand-editing on the commit message and merging of multiple commits myself.

**Comment by robd3** [comment]
there is a new version, new try! :-)

----- Nachricht beantworten -----
Von: "Kabuli Chana" <notifications@github.com>
An: "lede-project/source" <source@noreply.github.com>
Cc: "robd3" <Robert.Danzmayr@gmx.at>, "Comment" <comment@noreply.github.com>
Betreff: [lede-project/source] mwlwifi: Update to latest source (#526)
Datum: Mi., Dez. 21, 2016 18:53

surely I don't have to use nano [/joke]. Thanks, I will try again with some other mundane change, just trying to get a handle on the process, especially git which is a different beast than what I am used to.

&mdash;You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.










{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/lede-project/source","title":"lede-project/source","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/lede-project/source"}},"updates":{"snippets":[{"icon":"PERSON","message":"@anomeome in #526: surely I don't have to use nano [/joke]. Thanks, I will try again with some other mundane change, just trying to get a handle on the process, especially git which is a different beast than what I am used to."}],"action":{"name":"View Pull Request","url":"https://github.com/lede-project/source/pull/526#issuecomment-268593703"}}}

**Pull request closed without merging**
