### PR TITLE
arm64(sunxi H5):add support for NanoPi NEO2

### PR DESCRIPTION
**Pull request by laipeng668**
## ** NanoPi NEO2**

**Introduction**
The NanoPI NEO2 is a newly released super tiny ARM board by FriendlyElec. It uses Allwinner’s 64-bit H5 quad-core SoC (ARM Cortex-A53). It has internal hexa-core Mail450 GPU, 512M DDR3 RAM. A UbuntuCore and Armbian image files are ready for it.
The NanoPi NEO2 inherits NEO's form factor and has compatible interfaces and ports with NEO. In addition in such a small dimension it has Gbps Ethernet and one USB host port. These features make it especially suitable for applications that require high data throughput , speedy data transmission and high performance. Hobbyists and makers will just love it.

**Hardware Spec**
CPU: Allwinner H5, Quad-core 64-bit high-performance Cortex A53
DDR3 RAM: 512MB
Connectivity: 10/100/1000M Ethernet, RTL8211E-VB-CG chip
USB Host: USB Type A x 1 and USB pin header x 2
MicroSD Slot: MicroSD x 1 for system boot and storage
LED: Power LED x 1, System LED(Blue) x 1
GPIO1: 2.54mm pitch 24 pin-header, compatible with Raspberry Pi's GPIO pin1 - pin 24. It includes UART, SPI, I2C, IO etc
GPIO2: 2.54mm pitch 12 pin-header. It includes USB, IR receiver, I2S, IO etc
Serial Debug Port: 2.54mm pitch 4pin-header
Audio In/Out: 2.0mm pitch 5 pin-header
MicroUSB: Power input(5V/2A) and OTG
PCB Dimension: 40 x 40mm
Working Temperature: -30℃ to 70℃
Weight: 13g(WITHOUT Pin-headers)
OS/Software: u-boot,Ubuntu Core

**More detailed info:**  http://wiki.friendlyarm.com/wiki/index.php/NanoPi_NEO2#Introduction

Thanks in advance.

### CODE REVIEW

**Comment by hauke** [comment]
This pull request is broken.
Please create a pull request against the master branch and not against the lede-17.01 branch, we do not accept any new features in the lede-17.101 branch.
I have some patches adding A64 and kernel 4.9 support to the sunxi target: https://git.lede-project.org/?p=lede/hauke/staging.git;a=shortlog;h=refs/heads/sunxi

**Comment by laipeng668** [comment]
Thank you for your reply!
I just hope LEDE can support for NanoPi NEO2.
I'm so shame I can't provide any new features for LEDE.
If it's too hard to support for NanoPi NEO2,please close this pull request.
Thanks again!

**Comment by mkresin** [comment]
This PR is still broken. It contains > 250 commits in the meantime and has merge conflicts. Please do a `git pull --rebase` to get rid of the merge commits.

**Comment by hauke** [comment]
Please create a pull request for the master branch and not for the lede-17.01 branch. New features are only accepted for the master branch, the stable 17.01 branch only accepts security and bug fixes.

I created some patches to update the sunxi target to kernel 4.9 and add A64 support, this will probably get into the master branch soon, see: https://patchwork.ozlabs.org/bundle/Hauke/sunxi-4.9/

**Comment by hauke** [comment]
Please reopen a pull request against the master branch.

**Comment by hauke** [comment]
Could you please rebase your changes on top of current master branch and reopen this pull request.

**Comment by TimelessNL** [comment]
May I ask what the current status of the NEO2 is? It seems like an interesting platform. Especially since it has a first party NAS case: [1-bay NAS Dock](http://wiki.friendlyarm.com/wiki/index.php/1-bay_NAS_Dock_v1.2_for_NanoPi_NEO/NEO2)

**Pull request closed without merging**
