### PR TITLE
Netfilter package: general update

### PR DESCRIPTION
**Pull request by Ansuel**
Various update package and sync with git repo
Removed included patch

I switch to git (and not follow the release versions) because some package are very old and i think they will never be updated...

Compiled and tested on WRT1900ACS

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
@jow- @sbyx @blogic

**Comment by Ansuel** [comment]
@diizzyy can you test this?

**Comment by Ansuel** [comment]
Update to today commit

**Comment by nbd168** [comment]
Are there any particular features/bugfixes that you need from these packages? I have some doubts about simply updating all of them to git versions

**Comment by Ansuel** [comment]
@nbd168 Not so much... some are quite old and they contain bugfix 
What are your doubts about upgrading them? 
It's just to keep all up to date, same size so why not?

**Comment by jow-** [comment]
I'd be fine with the nftables update, for the other components I would prefer released versions as long as there is no particular reason to reference some git version.

**Comment by Ansuel** [comment]
@jow- libnftnl what about this bump ? 
and the removing of the patch with the bump of libnfnetlink

**Comment by jow-** [comment]
nftables + libnft - Git version okay imho, but please switch to http://, not git://
for libnfnetlink - is there an upstream commit resolving the header conflict? If yes I'd prefer to replace the patch with a variant exported from git with format-patch.

**Comment by Ansuel** [comment]
For libnfnetlink can't find the patch but when i upgraded it, the patch failed...
I checked the file that the patch modify and i discover that the 2 include where there... so patch useless

**Comment by diizzyy** [comment]
@Ansuel 
Not within a week or so, lack of time :/

**Comment by Ansuel** [comment]
@diizzyy done

**Comment by Ansuel** [comment]
Package updated

**Comment by Ansuel** [comment]
@diizzyy updated 

tested and compiled well

**Comment by Ansuel** [comment]
Think this way we can include only specific commit and leave what is "not approved" here ahahaha
@diizzyy @jow- @nbd168

**Comment by LipkeGu** [comment]
Will this also fix

```
Thu Apr 27 17:08:32 2017 kern.info kernel: [    1.500012] bridge: automatic filtering via arp/ip/ip6tables has been deprecated. Update your scripts to load br_netfilter if you need this.
```

**Comment by diizzyy** [comment]
Please close this and use releases when possible.
Also, this should probably separate requests.

**Pull request closed without merging**
