### PR TITLE
ca-certificates: move to openwrt/packages/net

### PR DESCRIPTION
**Pull request by chris5560**
ca-certificates not base build relevant, so move to openwrt/packages/net
!!! Depends on corresponding pulls at
- openwrt/openwrt#273
- openwrt/packages#3656

Signed-off-by: Christian Schoenebeck <<christian.schoenebeck@gmail.com>>

### CODE REVIEW

**Comment by blogic** [comment]
they should be present. wget and curl use them.

**Comment by chris5560** [comment]
From my knowledge no hardware/base build doing a preselection.
- wget-ssl is already part of openwrt/packages
- move of curl to openwrt/packages is pending
- uclient-fetch also does not select any ssl library by default.

From my understanding lede-project wants to concentrate on the real base build,
so everything else should be moved out.

**Comment by blogic** [comment]
On 14/12/2016 20:20, Christian Schoenebeck wrote:
> From my knowledge no hardware/base build doing a preselection.
> - wget-ssl is already part of openwrt/packages
> - move of curl to openwrt/packages is pending
> - uclient-fetch also does not select any ssl library by default.
> 
> From my understanding lede-project wants to concentrate on the real base
> build,
> so everything else should be moved out.
> 
> 

no one ever suggested that stuff needs to be moved out of the tree. i
really would like to keep certs in trunk, they are useful and should
stay there.

NAK from me on this patch.

**Comment by nbd168** [comment]
ustream-ssl uses it, and uclient-fetch (which uses ustream-ssl) is even included in the base image.
There you have your base tree use of ca-certficates

**Pull request closed without merging**
