### PR TITLE
layerscape: add LS1043A Rev1.1 support

### PR DESCRIPTION
**Pull request by yangbolu1991**
Backport kernel patches for LS1043A Rev1.1 support from upstream,
patchwork, and SDK. And update to latest u-boot to support LS1043A
Rev1.1.

Signed-off-by: Yangbo Lu <yangbo.lu@nxp.com>

### CODE REVIEW

**Comment by yangbolu1991** [comment]
All the patches introduced by u-boot and kernel are MSI driver/dts related.
They may affect ls1012a/ls1043a/ls1043a rev1.1/ls1046a RDB e1000e card working potentially.
So I verified e1000e card on all of these platforms. All of them worked fine. 
Attached logs. Thanks.
[ls1012ardb-e1000e-64b-32b-log.txt](https://github.com/lede-project/source/files/792317/ls1012ardb-e1000e-64b-32b-log.txt)
[ls1043ardb-e1000e-64b-32b-log.txt](https://github.com/lede-project/source/files/792316/ls1043ardb-e1000e-64b-32b-log.txt)
[ls1043ardb-rev1.1-e1000e-64b-32b-log.txt](https://github.com/lede-project/source/files/792319/ls1043ardb-rev1.1-e1000e-64b-32b-log.txt)
[ls1046ardb-e1000e-64b-32b-log.txt](https://github.com/lede-project/source/files/792318/ls1046ardb-e1000e-64b-32b-log.txt)

**Comment by yangbolu1991** [comment]
Also attached log of ls1043ardb(rev1.1) basic features test
[ls1043ardb-rev1.1-basic-features-test-64b-32b-log.txt](https://github.com/lede-project/source/files/792554/ls1043ardb-rev1.1-basic-features-test-64b-32b-log.txt)

**Comment by fsl-jyt** [comment]
Good work！

**Comment by chunkeey** [comment]
I have a more general question with the 32b layerscape target.
You see, the LEDE's blob/master/target/linux/layerscape/32b/target.mk uses
CPU_TYPE:=cortex-a9

however from what I can tell, all the boards have atleast a A53 cores (if not A57 or A72).
So, what's the reason behind this desicion? Wouldn't it make sense to set the CPU_TYPE
and CPU_SUBTYPE to something like this?

CPU_TYPE:=cortex-a53
CPU_SUBTYPE:=neon-vfpv4

(Especially, the NEON/VFPV4 - if supported, but it looks like it is - could make a difference
for some of the applications)

**Comment by blogic** [comment]
merged, Thanks !

@fsl-jyt  @yangbolu1991  we are updating the tree to v4.9 could you send a patch to update layerscape to v4.9 kernel please ?

**Comment by yangbolu1991** [comment]
@blogic We are working on upgrading the kernel version now. Our kernel v4.9 tree will be ready on June, and then we will send patches to LEDE. Is it late for LEDE? Thanks :)

**Comment by yangbolu1991** [comment]
@chunkeey Thanks a lot for pointing out this. I will have a check on our platforms. If the CPU_TYPE is not correct for some platforms, we need a plan to fix that. I will let you know the result. Thanks :)

**Pull request closed without merging**
