### PR TITLE
ar71xx: add support for gl-ar300m

### PR DESCRIPTION
**Pull request by zhao-gang**
This patch add initial support for GL-AR300M router.

Product page: http://www.gl-inet.com/ar300m/

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello @zhao-gang,

Your commit is missing prefix in the subject (ar71xx: ...).
Plus, instead of patch for kernel, you should add kernel related stuff directly inside:

- target/linux/ar71xx/files/arch/mips/ath79/machtypes.h
- target/linux/ar71xx/files/arch/mips/ath79/Makefile
- target/linux/ar71xx/files/arch/mips/ath79/Kconfig.openwrt

You can refer to my [commit](https://github.com/lede-project/source/commit/e767980eb897fbefc320f97b65944ce690ed1726).

Cheers!

**Comment by zhao-gang** [comment]
Hi, @pepe2k ,

Thanks for your review. I have made the changes you mentioned above, please tell me if I missed something.

**Comment by pepe2k** [comment]
Hello @zhao-gang,

Thanks for the changes. For me, everything looks OK now.

Cheers!

**Comment by jow-** [comment]
Pulled into my staging tree: https://git.lede-project.org/?p=lede/jow/staging.git;a=commit;h=697c543fa18bcb2c42d79f468b052d5df9f0f535

**Pull request closed without merging**
