### PR TITLE
ramips: Fix sdhci kernel panics on MT7621

### PR DESCRIPTION
**Pull request by ndoo**

### CODE REVIEW

**Comment by mkresin** [comment]
Hey ndoo,

I can see that you already contributed to LEDE. So you should known how a commit look like:

- missing signed off by line in your commit message
- missing prefix in your commit message
- bad commit title (what has been done)
- missing commit message (why it has to be done)

To change the address styling issues, please run the following git commands in your local git to change the existing commit:

```
git commit --amend
```

and use

```
git push --force
```

To overwrite your github repository. The Pull Requests updates automatically.

**Comment by ndoo** [comment]
This is entirely my bad for a lapse in judgement when typing the commit message. Pushed new commit.

**Comment by mkresin** [comment]
Your "signed off by" line is still missing...

**Comment by ndoo** [comment]
Pushed

**Comment by mkresin** [comment]
You have to keep the signed-off-by line of the original author. It isn't your work! The commit message should look like the following in the end:

```
ramips: enable work-arounds to fix sdhci on mt7621

Enable work-arounds present in the code commented-out but needed to
write to sdcard on mt7621 which currently causes kernel to oops when
engaging in serious writing to sdcard.

With this change applied, there are still occasional warnings thrown
by the mmc driver, however, at least it no longer crashes the system
and even large writes (full-card dump/erase/write/compare) don't show
any corruption.

Signed-off-by: Daniel Golle <daniel at makrotopia.org>
[rebase to LEDE]
Signed-off-by: Andrew Yong <me@ndoo.sg>
```

**Comment by ndoo** [comment]
@mkresin It’s a bit complicated because I have made some changes to the original patch, what do you suggest?

**Comment by ndoo** [comment]
So I have made the recommended changes - please review. Thank you for the guidance.

**Comment by blogic** [comment]
merged, Thanks !

**Comment by neheb** [comment]
:). This made my dsy

**Comment by mkresin** [comment]
@ndoo You commit broke the mt7688 build:

```
  CC [M]  drivers/mmc/core/sd_ops.o
drivers/mmc/host/mtk-mmc/sd.c: In function 'msdc_ops_request':
drivers/mmc/host/mtk-mmc/sd.c:2146:48: error: 'CONFIG_SOC_MT7621' undeclared (first use in this function)
         if(host->hw->flags & MSDC_REMOVABLE && CONFIG_SOC_MT7621 && mrq->data && mrq->data->error) {
                                                ^
drivers/mmc/host/mtk-mmc/sd.c:2146:48: note: each undeclared identifier is reported only once for each function it appears in
make[8]: *** [drivers/mmc/host/mtk-mmc/sd.o] Error 1
make[7]: *** [drivers/mmc/host/mtk-mmc] Error 2
```

Please fix it!

Have a look for a functions that tells which SoC you are on.

**Comment by ndoo** [comment]
Looking at it now. I know what mistake i've made on this.

**Pull request closed without merging**
