### PR TITLE
[URFC] Patch samba vfs acl config options

### PR DESCRIPTION
**Pull request by dfc-d**
NOTE: This patch series has just been split up and is not yet tested; it is purely a request for comments before doing the heavy lifting of testing and debugging.

This patch series

1) Adds mDNS advertisements for Samba
2) Moves Samba under Network|Filesystems menu for menuconfig
3) Add ACL and XATTR support configuration option
4) Adds netatalk compatibility support configuration option

Any comments on improvements prior to submitting would be welcome.

### CODE REVIEW

**Comment by blogic** [comment]
lgtm, patc h3 would need a close look when posted after testing

**Comment by nbd168** [comment]
netatalk support should not be enabled automatically if the netatalk package is selected. That will cause extra bloat on the samba package when built from the buildbot.

**Comment by blogic** [comment]
nbd requested changes and there was no response after 3 week. please reopen when there is an update.

**Comment by dfc-d** [comment]
I thought I had pushed those changes, but apparently not, will do that soon.

**Comment by dfc-d** [comment]
Actually for this and the other one, I have the comments I was lookin for now, I'll only reopen once they're actually tested and ready now

**Pull request closed without merging**
