### PR TITLE
Align layerscape source code with NXP LSDK

### PR DESCRIPTION
**Pull request by yangbolu1991**
This is a v4 version patch-set of below closed pull request.
https://github.com/lede-project/source/pull/1221

Below are the changes.
layerscape: update packages with LSDK git trees
- Updated u-boot/rcw/fm-ucode to tag LSDK-17.06.

layerscape: update linux to LSDK linux
- Splited it into 5 patches.

### CODE REVIEW

**Comment by blogic** [comment]
"layerscape: update linux 4.4 config" adds way to many config symbols for unrealted SoCs and drivers. there should also be no =m fields. the rest looks good at first glance

**Comment by yangbolu1991** [comment]
@blogic Thanks a lot for your comments, John.
I updated patch "layerscape: update linux 4.4 config" and dropped many unrelated config.
There also weren't =m field now.
Please help to reveiw. Thanks.

**Comment by hauke** [comment]
I would prefer if you could port the target to kernel 4.9, many of you patches are only backports from kernel 4.9 so it would be easier for us and you to maintain.

**Comment by yangbolu1991** [comment]
It's true we will have LSDK1709 release supporting both 4.4 and 4.9. Internal source codes are ready now and will be pushed to github on October. Actually LSDK will have a release every three monthes.
I will send LEDE patches to support 4.9 once source codes are pushed to LSDK github.

May I know whether LEDE will maintain both 4.4 and 4.9, or only maintain 4.9?
I checked our linux 4.9, there are still 661 patches. They're all related to layerscape IP modules.
I can merge each IP module patches into one just like this patch-set did to reduce patch number.
Regarding to this patch-set, do you think we should drop it waiting for 4.9 support, or it still need some changes to improve.

Thanks a lot :)

**Comment by hauke** [comment]
In the main releases we only support one kernel, the next one is planned to be kernel 4.9, and master prepares to get there.  I would prefer if the layerscape target would only support kernel 4.9.

**Comment by yangbolu1991** [comment]
@hauke 
Got it with thanks. No problem.
Then I will send 4.9 support patches once LSDK1709 source code are pushed to github.
Most patches of this patch-set are still available with minor changes at that time and only change is to support linux 4.9.
Let's keep this pull request for history and I will update it.

Thank you :)

**Comment by yangbolu1991** [comment]
@hauke @blogic 
Our LSDK had pushed source code to github, and linux 4.9 was supported.
So I generated v5 LEDE patch-set to support linux 4.9. Below are the changes.
Please help to reveiw. Thank you very much.

- Dropped below two patches.
        layerscape: update linux 4.4 patches
        layerscape: update linux 4.4 config
- Added below two new patches.
        layerscape: drop linux 4.4 support
        layerscape: add linux 4.9 support
- Updated packages version to the latest in patch 'layerscape: update packages with LSDK git trees'.

**Comment by blogic** [comment]
@yangbolu1991 thanks, i'll have a look later today

**Comment by yangbolu1991** [comment]
@blogic 
Thanks a lot, John.
Attached my verification logs.
[lede-layerscape-4.9-logs.zip](https://github.com/lede-project/source/files/1340217/lede-layerscape-4.9-logs.zip)

**Comment by hauke** [comment]
This looks good to me even if it adds a lot of code in the kernel patches.
@blogic will you merge it after you reviewed it.

**Comment by blogic** [comment]
merged, Thanks !

**Comment by yangbolu1991** [comment]
@blogic @hauke 
Thanks a lot for your help. But I haven't seen the patches on master...

**Comment by blogic** [comment]
@yangbolu1991 pushed last night, full builds fail with an error however, could you have a look at the error please ?
http://phase1.builds.lede-project.org/builders/layerscape%2F32b/builds/411/steps/kmods/logs/stdio

**Comment by yangbolu1991** [comment]
@blogic 
May I know the steps to reproduce this issue? I saw below directory I hadn't seen before in your log.
/home/buildbot/slave-lede-local/layerscape_32b/build

I tried to build master branch on commit of my patch for layerscape targets,  didn't find issue. Also tried the build command you used under source/, and didn't find issue.

**Comment by hauke** [comment]
I fixed the first problem @blogic mentioned in 29a6c4fcfb56c24aadcd3d7b5cc004c9d3f465e2 

Now I see these problems:
http://phase1.builds.lede-project.org/builders/layerscape%2F32b/builds/415/steps/kmods/logs/stdio
http://phase1.builds.lede-project.org/builders/layerscape%2F64b/builds/409/steps/kmods/logs/stdio

I get them with the following configuration:
hauke@hauke-desktop:~/openwrt/lede$ ./scripts/diffconfig.sh
CONFIG_TARGET_layerscape=y
CONFIG_TARGET_layerscape_armv8_32b=y
CONFIG_TARGET_layerscape_armv8_32b_Default=y
CONFIG_ALL_KMODS=y
CONFIG_ALL_NONSHARED=y
(just take this as .config and then run make defconfig)

**Comment by yangbolu1991** [comment]
Hi Hauke and John,

I found the reason of the build error. I had created a pull request. See,
https://github.com/lede-project/source/pull/1406

Thank you very much.

**Pull request closed without merging**
