### PR TITLE
package/network/services/lldpd: Update to 0.9.5

### PR DESCRIPTION
**Pull request by diizzyy**
Updates lldpd to 0.9.5

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile and basic runtime test on ar71xx

**Comment by diizzyy** [comment]
It's a sha256 hash

sha256sum lldpd-0.9.5.tar.gz
e9585c52f14808f03f6b6c3a9163c95b542a47b18abe002992b155d143a1a247  lldpd-0.9.5.tar.gz

Do you get something else?

**Comment by stintel** [comment]
I guess I missed the part where PKG_MD5SUM started taking SHA256 hashes. Something I absolutely don't like, but that discussion is not relevant for this PR.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
