### PR TITLE
ar71xx: Compex WPJ563 support

### PR DESCRIPTION
**Pull request by mehlis**
Specification:
- SoC: Qualcomm Atheros QCA9563 (775 MHz, MIPS 74Kc)
- RAM: 128 MiB
- Storage: 16MB NOR flash
- Wireless: Built into QCA9563 (Dragonfly), PHY modes b/g/n, 3x3 MIMO
- Ethernet: 2x1G

Tested and working:
- ethernet / switch / lan / wan
- 2.4GHz SoC wifi
- PCIe
- leds
- buzzer

Ramload:
- tftpboot 0x84000000 lede-ar71xx-generic-wpj563-16M-initramfs-uImage.bin
- bootm 0x84000000

Install:
- tftpboot 0x80500000 lede-ar71xx-generic-wpj563-16M-squashfs-sysupgrade.bin
- erase 0x9f030000 +$filesize
- erase 0x9f680000 +1
- cp.b $fileaddr 0x9f030000 $filesize

Signed-off-by: Christian Mehlis <christian@m3hlis.de>

Thanks for your contribution to the LEDE project!

To help keep the codebase consistent and readable,
and to help people review your contribution,
we ask you to follow the rules you find in the wiki at this link
https://lede-project.org/submitting-patches

Please remove this message before posting the pull request.

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello @mehlis,

Based on fast review, your PR looks OK but is there any reason to keep support for this board in legacy image building code? We really want to get rid of that legacy stuff instead of adding more code there.

From what I can see, you should be able to easily include support for image for this board in image/generic.mk (and in fact, we could then move out from legacy image code all others Compex boards).

Also, please disable related kernel config also in mikrotik/config-default.

> Install:
> [...]
>     erase 0x9f680000 +1

Why and what for is this needed?

Cheers,
Piotr

**Comment by mehlis** [comment]
Hi @pepe2k 

> but is there any reason to keep support for this board in legacy image building code?
No, I'll try to port all Compex boards to the new system.

> Also, please disable related kernel config also in mikrotik/config-default.
ok, I'll do.

> Why and what for is this needed?
Compex uboot defines:
bootcmd=bootm 0x9f680000 || bootm 0x9f030000
So it first tries to boot the higher address. I think the 16 mb flash are intended to be used as 8+8mb for a fallback image. In my hardware only the lower address has a bootable image. But to make sure future hardware will boot lede too, I erase one block, so uboot will skip this address.

Regards,
Christian

**Comment by pepe2k** [comment]
HI @mehlis,

> > but is there any reason to keep support for this board in legacy image building code?

> No, I'll try to port all Compex boards to the new system.

That would be great, just please split that in one change per commit.

> Compex uboot defines:
> bootcmd=bootm 0x9f680000 || bootm 0x9f030000

OK, I understand it now.

> So it first tries to boot the higher address. I think the 16 mb flash are intended to be used as 8+8mb for a fallback image. In my hardware only the lower address has a bootable image. But to make sure future hardware will boot lede too, I erase one block, so uboot will skip this address.

Does the vendor firmware provides a working `fw_setenv` command (which actually does change the U-Boot environment, if it's really writable/stored in separate flash sector)? If yes, you can just fix `bootcmd` value (`fw_setenv bootcmd "bootm 0x9f030000 || bootm 0x9f680000"`) instead of doing that erase.

Anyway, please include also this kernel load addresses related information in commit message.

Thanks!
Piotr

**Comment by mehlis** [comment]
Hi @pepe2k,

I hope I addressed all comments.
I'll do a separate PR for moving all modern Compex boards to non legacy build targets.

Regards,
Christian

**Comment by obsy** [comment]
Please drop "CONSOLE := ttyS0,115200" line. See: https://github.com/lede-project/source/commit/95c333a3b5568a9043afe52de3a5ea8b6a39127f

**Comment by blogic** [comment]
dont worry, i'll drop it while merging.

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
