### PR TITLE
ar71xx: generate BR region-code factory image for TP-Link TL-WR940N

### PR DESCRIPTION
**Pull request by heinzek**
First commit add BR region code to mktplinkfw tool.
Second commit add factory image with BR region code for TP-Link TL-WR940N V4

### CODE REVIEW

**Comment by mportela** [comment]
i’ve tested here and the factory-br image works in the tplink Web update interface. Using tplink 940n V5 BR

**Comment by mkresin** [comment]
We have a similar PR#1574 sets Code 2 for region BR. Since this one is confirmed working, I suspect that PR#1574 is wrong.

**Comment by mportela** [comment]
@mkresin no this PR is realy correct, the code for BR is 0, as i get explanation from the author "Matthias Schiffer" by email:
```
Adding another line {"BR", 0} should be sufficient (the second field 0/1 is
for another type of region specification that added the region as a third
field after hwid and hwrev in the firmware header, but as far as I know
this has only be used in the US, and the field is 0 for both old
"universal" firmwares as well as all non-US regions I've seen so far).
```

**Comment by blogic** [comment]
merged, Thanks !

**Comment by mportela** [comment]
@blogic sorry for my ignorance but did not see these commits in the lede: master .. or did they go to another branch first?

**Pull request closed without merging**
