### PR TITLE
Add support for Pogoplug v4 / Mobile

### PR DESCRIPTION
**Pull request by braian87b**
Add support for Pogoplug v4 / Mobile

### CODE REVIEW

**Comment by neheb** [comment]
Get rid of that last commit

**Comment by bobafetthotmail** [comment]
Thanks for adding support for this device! I will use this on my Pogoplugs. 

Please fix the commit messages, each commit message need a "Signed Off By your name <email>" line, must have hardware specifications, and instructions on how to install the new firmware/uboot.

See this page in the wiki on what you must have in the commits and how to fix the current PR https://lede-project.org/submitting-patches

**Comment by braian87b** [comment]
@neheb Sorry I screw it up and I don't know how to un-do that thing, I've never done this before... :( I deleted the fork now to see if that undoes the shit... the Original Repository with Pogo V4 support is at https://github.com/lzto/lede-source, please if you could fork by yourself and submit a pull request again, or edit that file by hand, I edited by hand because it shows me a conflict, thanks!

**Comment by braian87b** [comment]
Please delete the pull request we will try to prepare properly, If someone can help, it would be useful, I never done this before.

**Comment by neheb** [comment]
Doesn't seem like anything is deleted. A few tips.

git rebase -i HEAD~3 let's you adjust the last 3 commits. Just deleting the last line was enough.

Then

git push --force to push your changes.

**Comment by braian87b** [comment]
Great, that is the problem then I was trying to figure it out how to do it on github instead of trying on my computer (I didn't clone this repo yet, since I forked it just yesterday), I will try it, now, thanks!

**Comment by bobafetthotmail** [comment]
Github web interface is total garbage, for any real usage you need to clone locally and use git commandline, then push your changes to github.

If you want this to be merged, please do what I asked above too.

**Comment by braian87b** [comment]
Damn ,please remove/delete the pull request, since I deleted the repo and forked it again now it shows an error that says "unknown repository"...

**Comment by braian87b** [comment]
Ok, I it is here again: https://github.com/lede-project/source/pull/1611

**Pull request closed without merging**
