### PR TITLE
mwlwifi: update version to 10.3.4.0-20170713

### PR DESCRIPTION
**Pull request by anomeome**
Update to current mwlwifi

Signed-off-by: Kabuli Chana <newtownBuild@gmail.com>

### CODE REVIEW

**Comment by tapper82** [comment]
It's now bin updated again to driver version 10.3.4.0-20170713.
https://github.com/kaloz/mwlwifi/commit/4f6006807d29a846fd452f66a77c1fb60bc1a72c

**Comment by wongsyrone** [comment]
There is an issue waiting to be fixed: https://github.com/kaloz/mwlwifi/issues/191

**Comment by anomeome** [comment]
Appears resolved, if it actually was an issue.

**Comment by starcms** [comment]
Issue was resolved in version 10.3.4.0-20170713.  Ok to merge.

**Comment by starcms** [comment]
Actually #191 was not an issue to begin with; just someone who didn't know what they were talking about.  10-3.4.0-201711 worked fine except for an occasional kernel crash shown in the logs. That issue was discussed here https://github.com/kaloz/mwlwifi/issues/186 and it has been definitively fixed in the latest commit included in 10.3.4.0-20170713

**Comment by tapper82** [comment]
Pleas bump driver.

**Comment by diizzyy** [comment]
Please use the same version string as upstream ie "10.3.4.0-20170713", your commit msg should also reflect on what version you're updating to.

**Comment by wongsyrone** [comment]
new commit: https://github.com/kaloz/mwlwifi/commit/612df7ce8d02a45e78d24f2a5ab981ae6fc1594f

**Comment by tapper82** [comment]
Any news on this?

**Comment by tapper82** [comment]
Thanks

**Pull request closed without merging**
