### PR TITLE
ar71xx: add software transmit timestamp support

### PR DESCRIPTION
**Pull request by sdwalker**
Add software transmit timestamp and ethtool (-T) timestamp support

Signed-off-by: Stephen Walker <stephendwalker+github@gmail.com>

### CODE REVIEW

**Comment by lynxis** [comment]
hi @sdwalker do you did a benchmark? Does it do any bandwidth or cpu impact?

**Comment by sdwalker** [comment]
No benchmarks were done.

**Comment by nbd168** [comment]
What do you plan on using this for?

**Comment by sdwalker** [comment]
Plan was software PTP using ptp4l from the linuxptp package.

**Comment by blogic** [comment]
it would be good to get benchmarks. it looks like every skb will get cloned if you enable this. i would expect quite a performance hit.

**Comment by nbd168** [comment]
I expect performace to still be okay. The clones are only done for packets where there's an attached socket and there's timestamping requested for the socket, so the only hit on normal operation would come from some simple checks. Routing performace will most likely remain unaffected.

**Comment by nbd168** [comment]
Added to my staging tree

**Pull request closed without merging**
