### PR TITLE
target: brcm2708: bump kernel to version 4.14

### PR DESCRIPTION
**Pull request by commodo**
Tested 2709 & 2710 sub-targets on an RPi3 board.

Dropped patches from 4.9, pulled all patches from https://github.com/raspberrypi/linux/tree/rpi-4.14.y based on top of kernel 4.14.6.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
hmm, i'm thinking maybe i should remove the upstream commits

**Comment by commodo** [comment]
@Noltari 
ping

**Comment by commodo** [comment]
i know it's the holidays ; will ping again later
no need to look at this now ;

**Comment by lucize** [comment]
so I tried the patch, got some errors about files not found to be patched (but downloaded the raw config file from git)
target/linux/brcm2708/bcm2708/config-4.14
target/linux/brcm2708/bcm2709/config-4.14
target/linux/brcm2708/bcm2710/config-4.14

tested and working on bcm2708 on pi1 b model

Happy new year !

**Comment by commodo** [comment]
hmm ; i'll retry ; i may have missed something when i removed some patches ; 
i pushed this right before leaving the office

**Comment by commodo** [comment]
Happy New Year ! (in the new year)

in my case this built fine ;
admittedly if any errors or warnings appeared, they did not stop the build for me

**Comment by commodo** [comment]
Closing here;
will move to OpenWrt repo: https://github.com/openwrt/openwrt

w00h00

**Pull request closed without merging**
