### PR TITLE
libnftnl: update to 1.0.8

### PR DESCRIPTION
**Pull request by pprindeville**
Also, drop unsupported configure options.

Don't use git retrieve but released tarball instead.

### CODE REVIEW

**Comment by pprindeville** [comment]
@hauke Ask and you shall receive...

**Comment by hauke** [comment]
Can someone please runtime test this.

**Comment by pprindeville** [comment]
Moved to https://github.com/openwrt/openwrt/pull/600.

**Comment by pprindeville** [comment]
Moved to https://github.com/openwrt/openwrt/pull/600.

**Pull request closed without merging**
