### PR TITLE
tools/flex: update to 2.6.3

### PR DESCRIPTION
**Pull request by hnyman**
* update flex to 2.6.3
* download .tar.gz (as upstream has dropped .xz)
* refresh patches

Compile-tested with ipx806x, firmware build successfully.

### CODE REVIEW

**Comment by diizzyy** [comment]
I think you managed to get some stray commits included.

**Comment by hnyman** [comment]
> I think you managed to get some stray commits included.

Very very interesting. 

I think that somebody has force-pushed the LEDE master yesterday. I have managed to fetch the LEDE master while those two "stray" commits existed in the master before they were removed or overwritten.

Those two commits from @lynxis are not my commits, but I see them in my local clean "only do PRs for github" repo as the current (as of yesterday) references for LEDE master upstream HEAD, authored and committed by Lynxis on Friday 28 April. They have been fetched from upstream LEDE master. In upstream they have been now replaced by a new commit from @dedeckeh 

Currently those two commits do not exist any more in upstream. 
But they are visible e.g. in my Github fork master which was updated yesterday when doing this PR: https://github.com/hnyman/source 

Lynxis, are those two commits valid? Should they still be in the LEDE master? 
 * Do you think that you have committed them there yesterday and they should still be there?

commit 01c411ae0e8d004867766e8edb2e11ca4f40dd8a
Author:     Alexander Couzens <lynxis@fe80.eu>
AuthorDate: Fri Apr 28 14:34:46 2017 +0200
Commit:     Alexander Couzens <lynxis@fe80.eu>
CommitDate: Fri Apr 28 14:46:35 2017 +0200
    uboot-omap: rename patch to 101-disable-thumb-omap3.patch

commit 17837d02edb38d4da93df5a9c3545b5779a0a003
Author:     Alexander Couzens <lynxis@fe80.eu>
AuthorDate: Fri Apr 28 14:27:45 2017 +0200
Commit:     Alexander Couzens <lynxis@fe80.eu>
CommitDate: Fri Apr 28 14:45:44 2017 +0200
    uboot-omap: enable thumb for overo


some git details:

```
perus@ub1704:/OwrtLEDE/github/lede$ git branch -va
  cmake280                              a52a283ddd tools/cmake: update to 3.8.0
  flex263                               7d5d9db5ac tools/flex: update to 2.6.3
  lede-17.01                            ae0e167f2b busybox: revert accidential version bump
* master                                01c411ae0e uboot-omap: rename patch to 101-disable-thumb-omap3.patch
  remotes/origin/HEAD                   -> origin/master
  remotes/origin/cmake380               a52a283ddd tools/cmake: update to 3.8.0
  remotes/origin/flex263                7d5d9db5ac tools/flex: update to 2.6.3
  remotes/origin/lede-17.01             ae0e167f2b busybox: revert accidential version bump
  remotes/origin/master                 01c411ae0e uboot-omap: rename patch to 101-disable-thumb-omap3.patch
  remotes/origin/mvebu-cpufreq-kernel49 0ab4712d63 mvebu: add cpu frequency scaling driver
  remotes/upstream/lede-17.01           ae0e167f2b busybox: revert accidential version bump
  remotes/upstream/master               01c411ae0e uboot-omap: rename patch to 101-disable-thumb-omap3.patch
```

Current upstream history, which has a new commit from @dedeckeh  after the previous one that is common to the history that I have:
```
commit c45ef702ff3d4fd79b788823719cda356b9088c5
Author: Hans Dedecker <dedeckeh@gmail.com>
   odhcpd: update to git HEAD version (FS#656,FS#595)

commit 9412fc294995ae2543fabf84d2ce39a80bfb3bd6
Author: Hans Dedecker <dedeckeh@gmail.com>
   dnsmasq: support dhcp_option config as a list
```

History in my local repo (and Github fork):
```
commit 01c411ae0e8d004867766e8edb2e11ca4f40dd8a
Author: Alexander Couzens <lynxis@fe80.eu>
    uboot-omap: rename patch to 101-disable-thumb-omap3.patch

commit 17837d02edb38d4da93df5a9c3545b5779a0a003
Author: Alexander Couzens <lynxis@fe80.eu>
   uboot-omap: enable thumb for overo

commit 9412fc294995ae2543fabf84d2ce39a80bfb3bd6
Author: Hans Dedecker <dedeckeh@gmail.com>
   dnsmasq: support dhcp_option config as a list

```

**Comment by mkresin** [comment]
@hnyman would you please send a mail to lede-dev regarding the force push issue. this should never happen and most likely was done accidentally.

**Comment by commodo** [comment]
Maybe master could be made protected to prevent accidental force push.

The -f flag is something I also have a habit of using for WIP branches.
And I'm also guilty of messing up a master branch at work, because git push strategy was default-set to matching (in an older git).

https://help.github.com/articles/configuring-protected-branches/

**Comment by hnyman** [comment]
> Maybe master could be made protected to prevent accidental force push.

@jow- has protected all branches in luci and packages feed repos against force push using those Github features, as those two repos are "natively Github-based". That was done in 2015 after a force push was noticed there. See the "lock symbols" e.g. in https://github.com/openwrt/luci/branches

But I don't think that the same is possible for LEDE master as the is natively at git.lede-project-org and I think that most (all?) devs do commits there, not in Github. I have no knowledge about the pre force-push protection features at the git server software used there.

**Comment by commodo** [comment]
Well, as I understand it, protected branches allow fast-forward push, but not force push.

That may mean that only Github may not allow force push, and the official git repo may allow it, causing out-of-sync.

I suspect that git hooks could be used to protect the official repo.

**Comment by hnyman** [comment]
Rebased, as the mailing discussion has clarified the force push issue.

**Comment by nbd168** [comment]
Merged to my staging tree, thanks.

**Pull request closed without merging**
