### PR TITLE
iputils: Remove from tree

### PR DESCRIPTION
**Pull request by diizzyy**
iputils hasn't been updated in years, development has slowed down
considerably and we already have the majority of its functionality in
tree already.

iputils-arping ~ arp-scan (openwrt package repo)
iputils-clockdiff ~ ntpd/ntpdate (openwrt package repo)
iputils-ping* --> busybox
iputils-ftpd --> dnsmasq, atftp (openwrt package repo)
iputils-tracepath* --> None
iputils-traceroute* --> busybox

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@jow- 

We might want to consider replacing busybox's traceroute with this one: https://sourceforge.net/projects/traceroute/ as it adds the missing iptuils-tracepath functionality if deemed necessary.

**Comment by NeoRaider** [comment]
I think we should rather update to a newer iputils version, having the option to install a full-featured ping command is important IMO. There has been some interesting development lately that made it into Debian and Arch (and other distros) a while ago; in particular, ping and ping6 have been merged into a single ping command.

**Comment by diizzyy** [comment]
@NeoRaider 
What does busybox ping lack, out of curiosity?

**Comment by diizzyy** [comment]
..and if we're going to keep it: https://github.com/iputils/iputils

**Comment by NeoRaider** [comment]
@diizzyy: There are some options that I find very useful, although I rarely need them:
* -m (packet mark) for debugging mark-based policy routing
* -N (network information query)
* -f (flood ping)

**Comment by hauke** [comment]
NACK for removing iputils.

As it looks like the big distributions migrated to https://github.com/iputils/iputils we should also do this. Patches are welcome.

**Comment by blogic** [comment]
staged a commit locally that switches to the new upstream.

**Comment by zorun** [comment]
@blogic it looks like you forgot to change `PKG_SOURCE_URL` in your latest trunk commit?

**Pull request closed without merging**
