### PR TITLE
[lede-17.01] Backport MTD patches for stateless 4B opcodes to fix reboot issues

### PR DESCRIPTION
**Pull request by zorun**
This is essentially a respin of #620 for lede-17.01, hopefully fixing all the issues raised there.

### CODE REVIEW

**Comment by mkresin** [comment]
[As already stated](https://github.com/lede-project/source/pull/620#issuecomment-295404155), I don't like the idea of backporting such a massive change to the stable branch. Especially since it will effectively fix the issue only for one specific board (Archer C2600 v1.1 with MX25U25635F).

**Comment by oaaeruak** [comment]
As far as i know the next stable release that would be released this year would contain kernel 4.9 for all differnt devices. Are the patches you want to backport included in kernel 4.9?

**Comment by zorun** [comment]
Yes, this has already been fixed in master by Mathias in 226e194335c0d9a92402fbab772eac4f38786e45 (it was much easier to backport to 4.9 than to 4.4).

I wanted to use lede 17.01 for a project, but backporting stuff is increasingly difficult, so I guess we will have to use a version based on trunk for now...

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Pull request closed without merging**
