### PR TITLE
kernel: correctly refresh patches for ipq806x

### PR DESCRIPTION
**Pull request by kdarbyshirebryant**
ipq806x patches were refreshed with incorrect quilt options & do not
conform to standard format.  This patch corrects those formatting
errors.

Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>

### CODE REVIEW

**Comment by kdarbyshirebryant** [comment]
Looks like Hannu has done the same thing...with a much better commit message.  I'll close this.

**Comment by hnyman** [comment]
Sorry, I completely missed this. My excuse is just that I checked the PR list yesterday, before you created this. And did not re-check today when I created this (from my own Github fork). :-(

**Comment by kdarbyshirebryant** [comment]
Ha ha, no problem - it's good for me to know I produced an identical fix...which suggests everything is configured right...which is good news for the future.

**Comment by hnyman** [comment]
Btw, which ipq806x device you have? Just curious, because I have R7800 and have struggled with SQM "simple" performance problems (probably due to weak performance of HTB qdisc in dual-core IPQ8065). You might be interested in the discussion in https://github.com/tohojo/sqm-scripts/issues/48

And a side note for you: I tried backporting some of the HTB patches from Linux 4.8 and noticed that they will break cake compilation...

**Comment by kdarbyshirebryant** [comment]
I don't have an ipq806, I was in 'janitorial' mode :-)  

re: cake - my guess is 'cos the api changes courtesy the backport but the LINUX VERSION if defs don't track 'cos it's still 4.4.

**Comment by hnyman** [comment]
You are right. I now checked cake source and chromi has indeed written a 4.8 support patch for cake. I will patch things in my own build.

**Pull request closed without merging**
