### PR TITLE
tools/cmake: update to version 3.7.2

### PR DESCRIPTION
**Pull request by bladeoner**
Tested with ar71xx.

Signed-off-by: Etienne Haarsma <bladeoner112@gmail.com>

### CODE REVIEW

**Comment by diizzyy** [comment]
Are any of these updates tested?

**Comment by hnyman** [comment]
worksforme with ar71xx and ipq806x

**Comment by bladeoner** [comment]
Yes I tested it with ar71xx.

**Comment by diizzyy** [comment]
http://www.freshports.org/devel/cmake/
Same checksum

**Comment by bladeoner** [comment]
@diizzyy Thank you for checking.

**Comment by nbd168** [comment]
Merged to my staging tree, thanks.

**Pull request closed without merging**
