### PR TITLE
ar71xx: add support for Gainstrong MiniBox V3.2

### PR DESCRIPTION
**Pull request by p4u**
Adds MiniBox V3.2 ar71xx target (QCA99531 + QCA9887)
Info: http://oolite.cn/minibox-v3-2-qca9531-qca9887-module-pin-specification.html
Reference patch: http://oolite.cn/wp-content/uploads/2017/09/minibox_v3_cc15.05_20160325.patch
Installation: Upload firmware to uboot via HTTP at 192.168.1.1 (press button for 5 seconds)

Signed-off-by: Pau Escrich <p4u@dabax.net>

### CODE REVIEW

**Comment by p4u** [comment]
Obsoletes #1578

**Comment by mkresin** [comment]
Please, open a PR in the [OpenWrt repository](https://github.com/openwrt/openwrt/pulls).

With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed during the next days.

**Comment by p4u** [comment]
I agreed with @pepe2k in pull #1578 to merge this pull (if possible) on this repository.

**Comment by pepe2k** [comment]
Hi @p4u,

> I agreed with @pepe2k in pull #1578 to merge this pull (if possible) on this repository.

I think you misunderstood me. I asked you to squash commits in your previous PR, not open another one. We don't accept new PR in this repository and as both your PRs are now closed, please open new one in the [OpenWrt repository](https://github.com/openwrt/openwrt/pulls).

For future reference, to update your PR: make all requested changes in your local repository clone and then use `git commit --amend` to add them to your commit. Use `git push --force` to overwrite your GitHub repository/branch, which will afterwards update your pull request automatically.

Cheers,
Piotr

**Comment by p4u** [comment]
In my experience in GitHub, a `git push --force` breaks the already existing PR. But maybe it is based on a old experience and now it works fine.

Anyway I'll send the PR to the new OpenWRT repository.

Thanks.

**Comment by p4u** [comment]
Done at https://github.com/openwrt/openwrt/pull/645

**Comment by bobafetthotmail** [comment]
> In my experience in GitHub, a git push --force breaks the already existing PR.

That command just overwrites your github repo with the local repo, any issues you had was probably not related. Main source of screwups are merges and rebases imho.

**Comment by p4u** [comment]
Yep, I understand what push --force does. The problem I had was in a PR which was pointing to some specific commits that after pushing force desapeared. Then the github PR screw up and was still pointing to the old commits instead of the new ones (overided by push force).

Anyway it's good to know that it works fine in github now.

**Pull request closed without merging**
