### PR TITLE
toolchain/insight: Remove from tree

### PR DESCRIPTION
**Pull request by diizzyy**
Insight hasn't been touched since 2009 and I can't find any references at
least 6 years back of being used. Ubuntu and Debian removed insight years ago
from their repos so I think we can safely remove this too.

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by blogic** [comment]
@ffainelli you originally merged this. is it ok to drop it ?

**Comment by ffainelli** [comment]
Absolutely, let's remove it. Thanks!

**Comment by blogic** [comment]
@diizzyy fails to apply, please rebase

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
