### PR TITLE
kernel: bump to 4.4.65

### PR DESCRIPTION
**Pull request by kdarbyshirebryant**
Refresh patches on all 4.4 platforms.
Compile tested all supported 4.4. platforms.
Run tested ar71xx Archer C7 v2

Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>

### CODE REVIEW

**Comment by Borromini** [comment]
Hey Kevin,

Here I am again profiting off your hard work ;-)

I'm trying to apply your .65 bump to my local 17.01 branch (vanilla except for some `scripts/getver.sh` changes) but it breaks on a few patches:

    code/lede/17.01$ patch -Np1 -i ../patches/main/0001-Kernel-bump-LEDE-17.01-kernel-to-4.4.65.patch 
    patching file include/kernel-version.mk
    Hunk #1 FAILED at 3.
    1 out of 1 hunk FAILED -- saving rejects to file include/kernel-version.mk.rej
    patching file target/linux/ar71xx/patches-4.4/525-MIPS-ath79-enable-qca-usb-quirks.patch
    Reversed (or previously applied) patch detected!  Skipping patch.
    2 out of 2 hunks ignored -- saving rejects to file target/linux/ar71xx/patches-4.4/525-MIPS-ath79-enable-qca-usb-quirks.patch.rej
    patching file target/linux/ar71xx/patches-4.4/601-MIPS-ath79-add-more-register-defines.patch
    Reversed (or previously applied) patch detected!  Skipping patch.
    2 out of 2 hunks ignored -- saving rejects to file target/linux/ar71xx/patches-4.4/601-MIPS-ath79-add-more-register-defines.patch.rej
    patching file target/linux/ar71xx/patches-4.4/609-MIPS-ath79-ap136-fixes.patch
    Reversed (or previously applied) patch detected!  Skipping patch.
    3 out of 3 hunks ignored -- saving rejects to file target/linux/ar71xx/patches-4.4/609-MIPS-ath79-ap136-fixes.patch.rej

Git status:

    On branch lede-17.01-LTS
    Untracked files:
      (use "git add <file>..." to include in what will be committed)
    
    	.precheck
    
    nothing added to commit but untracked files present (use "git add" to track)

Can you check this?

**Comment by kdarbyshirebryant** [comment]
On 07/05/17 20:41, Borromini wrote:
> Hey Kevin,
>
> Here I am again profiting off your hard work ;-)
>
> I'm trying to apply your .65 bump to my local 17.01 branch (vanilla
> except for some |scripts/getver.sh| changes) but it breaks on a few patches:
>
> |code/lede/17.01$ patch -Np1 -i
> ../patches/main/0001-Kernel-bump-LEDE-17.01-kernel-to-4.4.65.patch
> patching file include/kernel-version.mk Hunk #1 FAILED at 3. 1 out of 1
> hunk FAILED -- saving rejects to file include/kernel-version.mk.rej
> patching file
> target/linux/ar71xx/patches-4.4/525-MIPS-ath79-enable-qca-usb-quirks.patch
> Reversed (or previously applied) patch detected! Skipping patch. 2 out
> of 2 hunks ignored -- saving rejects to file
> target/linux/ar71xx/patches-4.4/525-MIPS-ath79-enable-qca-usb-quirks.patch.rej
> patching file
> target/linux/ar71xx/patches-4.4/601-MIPS-ath79-add-more-register-defines.patch
> Reversed (or previously applied) patch detected! Skipping patch. 2 out
> of 2 hunks ignored -- saving rejects to file
> target/linux/ar71xx/patches-4.4/601-MIPS-ath79-add-more-register-defines.patch.rej
> patching file
> target/linux/ar71xx/patches-4.4/609-MIPS-ath79-ap136-fixes.patch
> Reversed (or previously applied) patch detected! Skipping patch. 3 out
> of 3 hunks ignored -- saving rejects to file
> target/linux/ar71xx/patches-4.4/609-MIPS-ath79-ap136-fixes.patch.rej |
>
> Git status:
>
> |On branch lede-17.01-LTS Untracked files: (use "git add <file>..." to
> include in what will be committed) .precheck nothing added to commit but
> untracked files present (use "git add" to track) |
>
> Can you check this?

This doesn't surprise me.  At some point the kernel & patches in 17.01 & 
trunk diverged and require different bumps :-(

**Comment by Borromini** [comment]
Bummer :-( I just looked at the 525 patch and that looks too complicated for me... Guess I'll wait till someone bumps 17.01 then. Thanks for checking!

**Comment by kdarbyshirebryant** [comment]
On 07/05/17 20:41, Borromini wrote:
> Hey Kevin,
>
> Here I am again profiting off your hard work ;-)
>
> I'm trying to apply your .65 bump to my local 17.01 branch (vanilla
> except for some |scripts/getver.sh| changes) but it breaks on a few patches:
>
> |code/lede/17.01$ patch -Np1 -i
> ../patches/main/0001-Kernel-bump-LEDE-17.01-kernel-to-4.4.65.patch
> patching file include/kernel-version.mk Hunk #1 FAILED at 3. 1 out of 1
> hunk FAILED -- saving rejects to file include/kernel-version.mk.rej
> patching file
> target/linux/ar71xx/patches-4.4/525-MIPS-ath79-enable-qca-usb-quirks.patch
> Reversed (or previously applied) patch detected! Skipping patch. 2 out
> of 2 hunks ignored -- saving rejects to file
> target/linux/ar71xx/patches-4.4/525-MIPS-ath79-enable-qca-usb-quirks.patch.rej
> patching file
> target/linux/ar71xx/patches-4.4/601-MIPS-ath79-add-more-register-defines.patch
> Reversed (or previously applied) patch detected! Skipping patch. 2 out
> of 2 hunks ignored -- saving rejects to file
> target/linux/ar71xx/patches-4.4/601-MIPS-ath79-add-more-register-defines.patch.rej
> patching file
> target/linux/ar71xx/patches-4.4/609-MIPS-ath79-ap136-fixes.patch
> Reversed (or previously applied) patch detected! Skipping patch. 3 out
> of 3 hunks ignored -- saving rejects to file
> target/linux/ar71xx/patches-4.4/609-MIPS-ath79-ap136-fixes.patch.rej |

A closer look suggests you don't need any of those patches anyway... 
they're all previously applied.

**Comment by bladeoner** [comment]
Could you please bump the pull request to 4.4.67?

**Pull request closed without merging**
