### PR TITLE
Bumpcake

### PR DESCRIPTION
**Pull request by dtaht**
This fixes the API breakage between mainline cake and lede cake. And lede cake, with itself.

Tested-by: dave taht <dave+github@taht.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
So it's broken in the 17.01 right now or just in master?
Also, please write in the commits what version you're bumping to. Make it much easier to backtrack.

**Comment by dtaht** [comment]
So I take it this was not pulled as I thought it was, but the new sqm-scripts were?

@kdarbyshirebryant @tohojo ?

**Comment by kdarbyshirebryant** [comment]
It has not yet been committed to LEDE master, no.  Patience.  Ideally this would have been done in lock step with the packages repo (where sqm-scripts resides) too, but that's even more fun to coordinate.  I didn't see jow in irc much yesterday...probably because I was mostly absent from it.  I'll ask him ever so nicely....

**Comment by dtaht** [comment]
My issue was that I was seeing weirdness with the default cake install in head. I have plots.

**Comment by jow-** [comment]
Merged into master.

**Pull request closed without merging**
