### PR TITLE
Add support for Buffalo WZR-450HP2D

### PR DESCRIPTION
**Pull request by majik-sheff**
A modified build of a WZR-450HP2
Maps out LEDs and all switches, and port numbers match the port labels on the device.
Tested on actual hardware.

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello @majik-sheff ,

Thank you for your first-time contribution! Unfortunately, something is wrong with your PR.

Please, squash all your commits into one and rebase it on current LEDE master branch. Use `git push --force` to overwrite your GitHub repository/branch, which will afterwards update your pull request here automatically.

Cheers,
Piotr

**Comment by majik-sheff** [comment]
I hope I did this right. I'm a total noob to git and github.

**Comment by mkresin** [comment]
> I hope I did this right. 

Nope you did not. There are now 17 commits instead of one. Please follow https://stackoverflow.com/a/5201642 to squash you commits. If your ```git log``` shows that you are down to one commit, use ```git push --force``` to update your github clone as already mentioned by pepe.

**Comment by majik-sheff** [comment]
I've done something horribly wrong.  I'll figure it out and try again.  Thank you for your patience and for this remarkable project.

**Pull request closed without merging**
