### PR TITLE
package/devel/binutils: Update to 2.27

### PR DESCRIPTION
**Pull request by diizzyy**
Updates binutils to 2.27

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile tested on ar71xx

**Comment by wongsyrone** [comment]
It seems this package should sync with toolchain's binutils.

**Comment by diizzyy** [comment]
What makes you say that, tool chain uses 2.25.1 whereas this port currently is at 2.25.
I've added support for 2.27 in pull request #402

**Comment by wongsyrone** [comment]
I am not watching this repo, just skimming the web page.

**Comment by nbd168** [comment]
Added to my staging tree at https://git.lede-project.org/?p=lede/nbd/staging.git;a=summary

**Pull request closed without merging**
