### PR TITLE
hostapd: add IEEE 802.11k support

### PR DESCRIPTION
**Pull request by BigNerd95**
Add IEEE 802.11K neighbor report and beacon report

Signed-off-by: Lorenzo Santina <lorenzo.santina@edu.unito.it>

### CODE REVIEW

**Comment by nbd168** [comment]
Please move all your cleanups to a separate commit to make review easier.

**Comment by BigNerd95** [comment]
Removed cleanup from my commit
I will clean up things better in a future PR

**Comment by mkresin** [comment]
Please bump the PKG_RELEASE in package/network/services/hostapd/Makefile.

**Comment by BigNerd95** [comment]
Done

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Pull request closed without merging**
