### PR TITLE
Update cake qdisc

### PR DESCRIPTION
**Pull request by kdarbyshirebryant**
Track upstream changes, incl changes in packet overhead accounting
(automatically taking care of linux' packet sizing knowledge),
improvements to triple isolated DRR handling (new flow dominance),
statistics tweak & allow more packet drops in stressed conditions.
    
Under tests this has significantly improved latency control under
'many flows to one' scenarious as is typical of bittorrent and MS
Windows update.
    
I also restored 'DSCP washing' functionality in my repo which follows
upstream closely (like a hawk!) with tc keywords 'wash/nowash'.  This
allows cake to limit/control packets in bands determined by a packet's
DSCP but to clear those DSCP bits on qdisc egress.  This functionality
was originally removed as part of an attempt to push cake into the
kernel, which hasn't actually happened as yet.
    
A matching commit is required to iproute2/tc to support the new overhead
handling, keyword changes as well as the 'wash/nowash' tweak.

Those interested in diving a bit deeper may find the updated manpage in
https://github.com/dtaht/tc-adv/commits/master useful.

Compile & run tested (for 2+ weeks) AR71xx, Archer C7 v2

### CODE REVIEW

**Comment by blogic** [comment]
merged, Thanks !

**Comment by mcaptur** [comment]
this wasn't merged.. cannot see it in master...

**Comment by kdarbyshirebryant** [comment]
Take a look in the cobalt branch.

**Comment by mcaptur** [comment]
github only  showing master branch.. not listing any other branches..

**Comment by kdarbyshirebryant** [comment]
The pr was merged into blogics staging tree where it will then be merged to lede master at some point.

**Comment by thagabe** [comment]
@kdarbyshirebryant "A matching commit is required to iproute2/tc to support the new overhead
handling, keyword changes as well as the 'wash/nowash' tweak." is there a PR open already or will you be sending a new PR? I would love to test this on my mvebu device as the new wifi module has some issues with sqm but cake more specifically.

**Comment by kdarbyshirebryant** [comment]
If you look there are two commits in the pr, one for module, one for iproute2.

**Comment by thagabe** [comment]
Thanks I had not noticed the addition since my last compile. I shall compile again

**Pull request closed without merging**
