### PR TITLE
ar71xx: add support to TP-Link Archer C58v1

### PR DESCRIPTION
**Pull request by heinzek**
TP-Link Archer C58v1 is a dual-band AC1350 router, based on Qualcomm/Atheros
QCA9561+QCA9886. It looks like Archer C59v1 wihout USB port.

C58 Specification:

775/650/258 MHz (CPU/DDR/AHB)
64 MB of RAM (DDR2)
8 MB of FLASH (SPI NOR)
3T3R 2.4 GHz
2T2R 5 GHz
5x 10/100 Mbps Ethernet
6x LED , 3x button
UART header on PCB, RX, TX at TP4+5 (Backside)
Missing:
-5GHz support due to some troubles with QCA9886 firmware

Flash instruction:
Use "factory" image directly in vendor GUI.

Recovery method:
Set PC to fixed ip address 192.168.0.66
Download lede-ar71xx-generic-archer-cXX-v1-squashfs-factory.bin
and rename it to tp_recovery.bin
Start a tftp server with the file tp_recovery.bin in its root directory
Turn off the router
Press and hold Reset button
Turn on router with the reset button pressed and wait ~15 seconds
Release the reset button and after a short time
the firmware should be transferred from the tftp server
Wait ~30 second to complete recovery.

Flash instruction under U-Boot, using UART:

tftp 0x81000000 lede-ar71xx-...-sysupgrade.bin
erase 0x9f020000 +$filesize
cp.b $fileaddr 0x9f020000 $filesize
reset

This commit is based on https://github.com/lede-project/source/pull/1112

### CODE REVIEW

**Comment by chunkeey** [comment]
You are in luck, @blogic made a package for the QCA9888 firmware here:
https://git.lede-project.org/?p=lede/blogic/staging.git;a=commit;h=2ab98089c36e84f459b057c09aca63cf35a4f9c2
From what I know the QCA9886 is a derivative of the QCA9888. Both share the same firmware (and pcie product id).

I think you could get the 5G working, if you do the following steps:
1. apply said patch (at least temporarily)

2. add the ath10k-firmware-qca9888 package to your DEVICE_PACKAGES in
    target/linux/ar71xx/image/tp-link.mk

3. modify target/linux/ar71xx/base-files/etc/hotplug.d/firmware/11-ath10k-caldata:
The 9888/9886 is a Wave-2 device. So, the "pre-cal" method will be needed.
Support for it was added by recently by:
https://github.com/lede-project/source/commit/025cb640cdf27f7c68fc1d89d0698605daa06c43

Note: the pre-cal is much bigger 12064 bytes (instead of 2116). 

```
diff --git a/target/linux/ar71xx/base-files/etc/hotplug.d/firmware/11-ath10k-caldata b/target/linux/ar71xx/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
index 91db049c44..b312cb7c6b 100644
--- a/target/linux/ar71xx/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
+++ b/target/linux/ar71xx/base-files/etc/hotplug.d/firmware/11-ath10k-caldata
@@ -134,6 +134,11 @@ case "$FIRMWARE" in
                ;;
        esac
        ;;
+"ath10k/pre-cal-pci-0000:00:00.0.bin")
+       archer-c58-v1)
+               ath10kcal_extract "art" 20480 12064
+               ath10kcal_patch_mac $(macaddr_add $(cat /sys/class/net/eth1/address) -2)
+               ;;
 *)
        exit 1
        ;;

```
I hope the offset and MAC is ok. It's hard to tell without having a dump of the ART partition.
Regards,
Christian

**Comment by heinzek** [comment]
Hi @chunkeey, Thanks this.

I add qca9888 firmware to makefile, generate ath10k-qca9888.ipk and install to latest snapshot.
edit 11-ath10k-caldata to get pre-cal-data... with patched mac adress.
firmware not started:
```
[    9.865955] ath10k_pci 0000:00:00.0: pci irq legacy oper_irq_mode 1 irq_mode 0 reset_mode 0
[   11.027885] ath10k_pci 0000:00:00.0: qca9888 hw2.0 target 0x01000000 chip_id 0x00000000 sub 0000:0000
[   11.037455] ath10k_pci 0000:00:00.0: kconfig debug 0 debugfs 1 tracing 0 dfs 1 testmode 1
[   11.056278] ath10k_pci 0000:00:00.0: firmware ver 10.4-3.2-00072 api 5 features no-p2p,mfp,peer-flow-ctrl crc32 b1da0716
[   11.387341] ath10k_pci 0000:00:00.0: failed to fetch board data for bus=pci,bmi-chip-id=0,bmi-board-id=20 from ath10k/QCA9888/hw2.0/board-2.bin
[   11.421232] ath10k_pci 0000:00:00.0: board_file api 1 bmi_id 0:20 crc32 74a04250
[   13.432822] ath10k_pci 0000:00:00.0: firmware crashed! (uuid fedd3759-b6fc-41b6-99ab-6b9a51e3383a)
[   13.442121] ath10k_pci 0000:00:00.0: qca9888 hw2.0 target 0x01000000 chip_id 0x00000000 sub 0000:0000
[   13.451658] ath10k_pci 0000:00:00.0: kconfig debug 0 debugfs 1 tracing 0 dfs 1 testmode 1
[   13.470504] ath10k_pci 0000:00:00.0: firmware ver 10.4-3.2-00072 api 5 features no-p2p,mfp,peer-flow-ctrl crc32 b1da0716
[   13.483089] ath10k_pci 0000:00:00.0: board_file api 1 bmi_id 0:20 crc32 74a04250
[   13.490746] ath10k_pci 0000:00:00.0: htt-ver 0.0 wmi-op 6 htt-op 4 cal pre-cal-file max-sta 32 raw 0 hwcrypto 1
[   13.503184] ath10k_pci 0000:00:00.0: firmware register dump:
[   13.509042] ath10k_pci 0000:00:00.0: [00]: 0x01000000 0x000015B3 0x000D029C 0x00975B31
[   13.517217] ath10k_pci 0000:00:00.0: [04]: 0x000D029C 0x00060F30 0x00000011 0x00030E00
[   13.525394] ath10k_pci 0000:00:00.0: [08]: 0x000C0000 0x00405E9C 0x00405EA4 0x00400000
[   13.533573] ath10k_pci 0000:00:00.0: [12]: 0x00000009 0x00000000 0x000D01E4 0x000D01EF
[   13.541753] ath10k_pci 0000:00:00.0: [16]: 0x000D029C 0x000D01E7 0x00000000 0x00000000
[   13.549933] ath10k_pci 0000:00:00.0: [20]: 0x400D029C 0x00405E1C 0x00975A00 0x00000000
[   13.558114] ath10k_pci 0000:00:00.0: [24]: 0x809CE66F 0x00405E7C 0x00405FB0 0xC00D029C
[   13.566288] ath10k_pci 0000:00:00.0: [28]: 0x809BC64F 0x00405E9C 0x000C0000 0x00405FB0
[   13.574467] ath10k_pci 0000:00:00.0: [32]: 0x809BC67C 0x00405EDC 0x000C0000 0x00405FB0
[   13.582646] ath10k_pci 0000:00:00.0: [36]: 0x809CE929 0x00405F0C 0x000C0000 0x00405FB0
[   13.590826] ath10k_pci 0000:00:00.0: [40]: 0x80986A31 0x00405F2C 0x00405FAC 0x00405F6C
[   13.599007] ath10k_pci 0000:00:00.0: [44]: 0x809CEAAF 0x00405F6C 0x00405FAC 0x004132CC
[   13.607181] ath10k_pci 0000:00:00.0: [48]: 0x809813AB 0x00405F9C 0x0041554C 0x00400000
[   13.615361] ath10k_pci 0000:00:00.0: [52]: 0x800D6D41 0x0040600C 0x00000004 0x00412F00
[   13.623540] ath10k_pci 0000:00:00.0: [56]: 0x800C383A 0x0040603C 0x00412D90 0x00400000
[   13.631718] ath10k_pci 0000:00:00.0: Copy Engine register dump:
[   13.637845] ath10k_pci 0000:00:00.0: [00]: 0x0004a000   2   2  19  18
[   13.644503] ath10k_pci 0000:00:00.0: [01]: 0x0004a400  11  11  10  11
[   13.651169] ath10k_pci 0000:00:00.0: [02]: 0x0004a800   0   0  63   0
[   13.657833] ath10k_pci 0000:00:00.0: [03]: 0x0004ac00   0   0   0   0
[   13.664494] ath10k_pci 0000:00:00.0: [04]: 0x0004b000   0   0   0   0
[   13.671158] ath10k_pci 0000:00:00.0: [05]: 0x0004b400   0   0   0   0
[   13.677824] ath10k_pci 0000:00:00.0: [06]: 0x0004b800   0   0   0   0
[   13.684483] ath10k_pci 0000:00:00.0: [07]: 0x0004bc00   1   1   1   1
[   13.691148] ath10k_pci 0000:00:00.0: [08]: 0x0004c000   0   0 127   0
[   13.697814] ath10k_pci 0000:00:00.0: [09]: 0x0004c400   1   1   1   1
[   13.704473] ath10k_pci 0000:00:00.0: [10]: 0x0004c800   0   0   0   0
[   13.711137] ath10k_pci 0000:00:00.0: [11]: 0x0004cc00   0   0   0   0
[   14.427209] ath10k_pci 0000:00:00.0: failed to receive control response completion, polling..
[   15.427201] ath10k_pci 0000:00:00.0: ctl_resp never came in (-145)
[   15.433587] ath10k_pci 0000:00:00.0: failed to connect to HTC: -145
[   15.508423] ath10k_pci 0000:00:00.0: could not init core (-145)
[   15.514719] ath10k_pci 0000:00:00.0: could not probe fw (-145)
[   15.527797] ath10k_pci 0000:00:00.0: cannot restart a device that hasn't been started
```

Now i delete board.bin and board-2.bin and download calibration data from flash and rename it to board.bin
dd if=/dev/mtd6 of=/lib/firmware/ath10k/QCA9888/hw2.0/board.bin bs=1 skip=20480 count=12048

after reboot wlan interface is up and working correctly

**Comment by chunkeey** [comment]
> [   11.387341] ath10k_pci 0000:00:00.0: failed to fetch board data for bus=pci,bmi-chip-id=0,bmi-board-id=20 from ath10k/QCA9888/hw2.0/board-2.bin
>
> Now i delete board.bin and board-2.bin and download calibration data from flash and rename it to > board.bin
> dd if=/dev/mtd6 of=/lib/firmware/ath10k/QCA9888/hw2.0/board.bin bs=1 skip=20480 count=12048
>
>after reboot wlan interface is up and working correctly

Yeah, so ath10k-firmware's board-2.bin does not have an entry for id=20. This should be reported to linux-wireless / ath10k-devel. If you want I could email you a board-2.bin with the boardData_0.bin from TP-Link. It should work as well.

**Comment by heinzek** [comment]
@chunkeey can I write directly to @kvalo ? 

Mac address on this interface is incorrectly, patched this with "ath10kcal_patch_mac" not working.
I fix this by using /etc/hotplug.d/ieee80211/10_fix_wifi_mac like in ipq806x.

**Comment by chunkeey** [comment]
> @chunkeey can I write directly to @kvalo ?
I don't know if he reads his github messages or not. The ML however is a safe bet. But please include some context. For example that you got a QCA9886 and it needs the "bus=pci,bmi-chip-id=0,bmi-board-id=20" board data to be present. For good measure include the ath10k error:

[ 11.387341] ath10k_pci 0000:00:00.0: failed to fetch board data for bus=pci,bmi-chip-id=0,bmi-board-id=20 from ath10k/QCA9888/hw2.0/board-2.bin you can try but he probably needs some context.

and also include, that "reusing the pre-cal" as board.bin did get you a working device.

>Mac address on this interface is incorrectly, patched this with "ath10kcal_patch_mac" not working.
>I fix this by using /etc/hotplug.d/ieee80211/10_fix_wifi_mac like in ipq806x.
I think the caldata-utils could maybe do it.
https://patchwork.ozlabs.org/patch/604557/

That said, it was never merged, so it's probably better to just stick with the 10_fix_wifi_mac method.

**Comment by greearb** [comment]
You probably need 'count=12064', not 12048.  That and ath10k-ct 9888 firmware (packaged in LEDE already) worked on a different system.  If you are extracting the eeprom (board) data from the local system, then call it 'board.bin', and remove any board-2.bin file.  In that case, the BMI id doesn't matter.

See https://forum.lede-project.org/t/archer-c59-v1-missing-ieee802-11-a-n-ac-5ghz/2226/15

**Comment by pepe2k** [comment]
@heinzek,

Thank you for your contribution!
I have merged your changes (with minor fixes in commit message) into [my staging tree](https://git.lede-project.org/?p=lede/pepe2k/staging.git;a=summary).

I will ask @blogic about that patch with qca9888 firmware package and eventually include it in DEVICE_PACKAGES when it's possible.

Dzięki! :neckbeard:

Cheers,
Piotr

**Pull request closed without merging**
