### PR TITLE
brcm47xx: fix switch port mapping on Asus RT-N16

### PR DESCRIPTION
**Pull request by majik-sheff**
On the Asus RT-N16, the ports are not mapped the in the same way as
the RT-N12.  It is, however, the same as the Linksys E3000v1.

Signed-off-by: Tim Thorpe <timfthorpe@gmail.com>

### CODE REVIEW

**Comment by mkresin** [comment]
Is this tested or another an edit via github webinterface?

You're changing the the cpu port from `5@eth0` to `8@eth0`. I'm in doubt that the switch will work at all with the change applied.

**Comment by mkresin** [comment]
As of writing you managed to to mess up the PR. Now there are 619 changed file in your commit...

**Comment by majik-sheff** [comment]
Yeah I swear git hates me.  I can't seem to get the rebase to work without claiming all of those changes for myself.  UGH.  And to answer your question, yes  this change is tested. I have it running on a couple of N-16s on my desk.  Lemme fix this commit mess and reopen the request.

**Comment by mkresin** [comment]
> Yeah I swear git hates me. I can't seem to get the rebase to work without claiming all of those changes for myself. UGH. And to answer your question, yes this change is tested. I have it running on a couple of N-16s on my desk. Lemme fix this commit mess and reopen the request.
> 
Could it be that you preserved your config during testing and the changed CPU port wasn't applied to your /etc/config/network? Would you please attach this file with your next comment.

**Pull request closed without merging**
