### PR TITLE
17.01 kernel: bump 4.4 to 4.4.100

### PR DESCRIPTION
**Pull request by bladeoner**
17.01 kernel: bump 4.4 to 4.4.100

Refreshed all patches.

Removed upstream ramips patch: 0063-set-CM_GCR_BASE_CMDEFTGT_MEM-according-to-datasheet.patch

Compile-tested: ar71xx
Run-tested: ar71xx

Signed-off-by: Etienne Haarsma <bladeoner112@gmail.com>

### CODE REVIEW

**Comment by stintel** [comment]
.101 is out, can you update this PR?

**Comment by bladeoner** [comment]
I will update the PR later.

**Comment by obsy** [comment]
And .102 is out...

**Comment by bladeoner** [comment]
I will open a new pull request for 4.4.102

**Comment by stintel** [comment]
@bladeoner please don't. Update this PR instead.

**Pull request closed without merging**
