### PR TITLE
fuse: update to latest release version

### PR DESCRIPTION
**Pull request by hbl0307106015**
update libfuse to 3.0.1

https://github.com/libfuse/libfuse/releases

Signed-off-by: BangLang Huang <banglang.huang@foxmail.com>

### CODE REVIEW

**Comment by diizzyy** [comment]
Run-time tested?

**Comment by hbl0307106015** [comment]
@diizzyy  Sorry for my mistake, I forgot to push some of the diff, now the pull request is complete,

**Comment by hbl0307106015** [comment]
@diizzyy  By the way, there is a problem, the ntfs-3g use 2.6.x as its default external fuse library version, 
how about create a fuse3-utils package (co-exist with the fuse-utils, or renamed the original as fuse2-utils) for beter compatibility ?

**Comment by diizzyy** [comment]
Unless there are any regressions just replace 2.X with 3.X.

**Comment by diizzyy** [comment]
@hbl0307106015 
You can bump this to 3.0.2 and provide a log of run-time testing?

**Comment by hbl0307106015** [comment]
@dizzy, ok, got it, I will have a run time test later.

**Comment by hbl0307106015** [comment]
hello-fuse3

**Comment by hbl0307106015** [comment]
@diizzyy Hi, I ran a test (libfuse-3.1.0) on my machine, here is the snapshot, is it ok ??

**Comment by hbl0307106015** [comment]
hello-fuse3-2

**Comment by hbl0307106015** [comment]
update libfuse to 3.1.0, @diizzyy

**Comment by hbl0307106015** [comment]
bump to libfuse 3.1.1, @diizzyy @pepe2k

**Comment by diizzyy** [comment]
Not a user of fuse but this seems fine to me having a quick look at it

**Comment by hbl0307106015** [comment]
Is there any possible to make fuse2.x and fuse3.x coexist? Maybe this is a better choice to maintain compatibility.

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Pull request closed without merging**
