### PR TITLE
gpio-ich/itco-wdt/w83627hf-wdt: add modules for Xeon platforms

### PR DESCRIPTION
**Pull request by pprindeville**
Drivers for supporting current Xeon motherboards.

Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>

### CODE REVIEW

**Comment by blogic** [comment]
please run "git log --oneline" ont he folders you are patching to see what the patches prefix should be. in this case it would need to be "kernel:"

**Comment by nbd168** [comment]
I think these should probably be enabled in the x86/64 kernel config instead of being packaged.

**Comment by pprindeville** [comment]
> please run "git log --oneline" ont he folders you are patching to see what the patches prefix should be. in this case it would need to be "kernel:"

@blogic: fixed, thanks.

**Comment by pprindeville** [comment]
> I think these should probably be enabled in the x86/64 kernel config instead of being packaged.

@nbd168: that might make sense for the ich and itco drivers; the w83627hf is obviously a 3rd party chipset and is less common.

Occasionally you end up with situations where two different drivers will match the same chipset (for instance, the w83627ehf and the nct6775 will both match the same PCI ID's, but the nct6775 is the better driver for the nct6775/6 (because it's more complete) and, equally importantly, isn't deprecated.

**Comment by nbd168** [comment]
Okay, please change the commit to only package w83627hf

**Comment by pprindeville** [comment]
> Okay, please change the commit to only package w83627hf

Done!

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
