### PR TITLE
ramips: fix cd-poll sd card remove randomly

### PR DESCRIPTION
**Pull request by Vonger**
Fix when add 'mediatek,cd-poll' to dts cause the sd card be removed randomly.
Special for the device without card-detect pin.

### CODE REVIEW

**Comment by mkresin** [comment]
Isn't it the same as your #1178?

**Comment by Vonger** [comment]
Yes, but this is submitted for Linux 4.9

**Comment by mkresin** [comment]
#1178 applies changes to target/linux/ramips/**patches-4.9**/0046-mmc-MIPS-ralink-add-sdhci-for-mt7620a-SoC.patch as well. If this PR replaces #1178, close #1178.

**Comment by Vonger** [comment]
Ah, ye, my mistake, closed :)

**Comment by blogic** [comment]
@Vonger merged, Thanks !

**Pull request closed without merging**
