### PR TITLE
rbcfg: move to Boot Loaders submenu of Utilities

### PR DESCRIPTION
**Pull request by bobafetthotmail**
Part of a wider housekeeping effort on the packages repository.

Signed-off-by: Alberto Bursi <alberto.bursi@outlook.it>

### CODE REVIEW

**Comment by blogic** [comment]
"Part of a wider housekeeping effort on the packages repository."

1) this is not the packages repo but trunk
2) the desription does not explain what the patch does

**Comment by bobafetthotmail** [comment]
Isn't the title enough? "rbcfg: move to Boot Loaders submenu of Utilities" should be clear enough for this one-line change.

**Comment by blogic** [comment]
you are refering to the subject. i am talking about the description

**Comment by bobafetthotmail** [comment]
ok, will add a description.

**Pull request closed without merging**
