### PR TITLE
ar71xx: Add EnGenius ENS200 support

### PR DESCRIPTION
**Pull request by hanetzer**
ENS200 Long-Range Wireless 2.4GHz Outdoor Bridge/AP

The device is based on Qualcomm/Atheros AR7240 rev 2., with wifi
provided by Atheros AR9285

Specifications:

- 400/400/200 MHz (CPU/DDR/AHB)
- 32 MB of RAM
- 8 MB of FLASH
- UART (J3) header on PCB (populated)
- 2x 10/100 Mbps Ethernet
- 2.4 GHz, up to 8dBi gain.
- 7x LED, 1x button

Flash instructions:

Due to space constraints in the vendor flash partitioning and
the relative inflexibility of the vendor's factory image format/
flash process I've elected to use/require an initramfs to install.

The stock u-boot will pull an initramfs (named vmlinux-art-linux)
from a tftp server at 192.168.1.101 when the device is powered on
while the reset switch is being pressed.

Steps:

1. Download the initramfs file (lede-ar71xx-generic-ens200-initramfs-kernel.bin)
   from downloads.lede-project.org

2. Install and configure a tftpd server on your host machine [1]

3. Copy the ramdisk to $TFTPROOT/vmlinux-art-linux, where $TFTPROOT is
   the root of the tftpd server you configured in step 2.

4. Set a static ip of 192.168.1.101 for the host machine running tftpd

5. While holding down the reset button (you'll likely need a paperclip
   or some other thin, hard object), plug in the ethernet cable from
   the PoE injector (no 'normal' power cable); when all the LEDs turn
   on you know its working.

6. Give the process some time to complete. At this point you can follow
   the 'Installing LEDE Sysupgrade'[2] guide to install.

[1]: https://lede-project.org/docs/howto/tftpserver
[2]: https://lede-project.org/docs/guide-quick-start/standardflashinginstructions#installing_lede_sysupgrade

### CODE REVIEW

**Comment by ntzrmtthihu777** [comment]
So. To begin discussion, as you can see, flash is really small on this device. Difficult to make a factory image that will work with this device, as you can't appear to make a kernel that fits in 1024k space allocated. In order to get around this, I've prepared an initramfs-uImage for the device, and from this environment applied a sysupgrade, which worked quite well.

So, with this in mind, how do the devs suggest we go about this?

**Comment by pepe2k** [comment]
Hello @ntzrmtthihu777,

Please, read our [submitting patches rules](https://lede-project.org/submitting-patches), and make sure your pull request follows them. Your commit is missing a proper prefix, description and SoB line.

Cheers,
Piotr

**Comment by ntzrmtthihu777** [comment]
>Hello @ntzrmtthihu777,

>Please, read our submitting patches rules, and make sure your pull request follows them. Your commit is missing a proper prefix, description and SoB line.

@pepe2k really? I know you ***had*** to have seen what was the first line of the PR description. This device has issues which need to be worked out before I'd be happy merging it/with it being merged.

You could have at least had read what my concerns were and gave advice wrt how to go about in the message above :/

**Comment by pepe2k** [comment]
Hello @ntzrmtthihu777,

> @pepe2k really? I know you had to have seen what was the first line of the PR description. This device has issues which need to be worked out before I'd be happy merging it/with it being merged.

Sure, first line was/is: "ENS200 Long-Range Wireless 2.4GHz Outdoor Bridge/AP".

> You could have at least had read what my concerns were and gave advice wrt how to go about in the message above :/

Sorry, but I just don't look closer on PR which have formal issues.

Cheers,
Piotr

**Comment by ntzrmtthihu777** [comment]
@pepe2k well, apparently github doesn't save edits to comments, but I had on either the first or second line something to the effect of 'placeholder for now'.

In any case, what do you think of the idea of using initramfs boot to install on this family of devices? We'd be able to ditch the senao-factory-image code and just produce initramfs and sysupgrade images. Shouldn't take much more space (if any) on the build/dl server, and then we avoid the stupidity involved in the factory image and vendor firmware update mechanism.

The u-boot for ENS202EXT/ENS200 (and probably others, given the amount of ramdisk downloads available from easywrt.com) already has provisions for booting a ramdisk from tftp without the need of dismantling the hardware (though that is a bit easier in my mind), and if we can boot a lede ramdisk we control the install environment and don't need to worry about the vendor's restrictive format.

In addition, with the failsafe boot partition, one can easily enough revert to stock firmware.

**Comment by mkresin** [comment]
@ntzrmtthihu777 Would you please add a LED config for the RSSI LEDs! Have a look at https://github.com/lede-project/source/commit/e7cd6f5d66b827e31cfa7e7bc019ac1b86aac770 for an example.

I noticed your question regarding LEDs connected to the ath9k GPIOs in #lede-dev. The Fritz 300e from the linked commit has the code to use the ath9k GPIOs.

What is up with the wireless, lan and power LEDs? Power LED connected to VCC once more? Wireless and LAN LEDs do work out of the box (aka wireless led is attached to the "default" ath9k GPIO as expected by the driver [which setup the phy0 trigger on it's own])?

**Comment by ntzrmtthihu777** [comment]
@mkresin Thanks for the pointers, I didn't know where to look for the gpio-leds setup for the wmac chip.
As far as I can tell 3/4 of the wlan indicator leds are attached to the normal ath79 gpio, and only one runs off the one on the pci card. Unsure about the two ethernet leds as of right now.

I don't understand your question here, could you please elaborate?

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Pull request closed without merging**
