### PR TITLE
download: allow specifying git clone options

### PR DESCRIPTION
**Pull request by fake666**
- for git, there is an inaccessible OPTS variable already
- allow setting it via PKG_SOURCE_OPTS
- can be used for adding "--depth 1" to the git command for shallow clones

Signed-off-by: Thomas 'fake' Jakobi <thomas@derfake.com>

### CODE REVIEW

**Comment by pepe2k** [comment]
@nbd168, @jow- ?

**Comment by jow-** [comment]
Hm, can't see any problems with this. LGTM

**Comment by fake666** [comment]
valid point. i'll rename it...

**Comment by fake666** [comment]
@jow ok like this?

**Comment by fake666** [comment]
... knock, knock... :)

**Comment by nbd168** [comment]
I've reviewed this again, and to me this does not make much sense. First of all, if you set --depth 1 to create a shallow clone, you won't be able to select a specific version anymore.
As such, this would only seem to work for strongly-discouraged 'moving target' makefiles that just use whatever version happens to be the most recent one in the git repository.
If you care about cloning a package fast, you could use CONFIG_SOURCE_TREE_OVERRIDE and the git-src symlink. This will ensure that after you've cloned the repo once, the build system can just take it from there. For personal use this should be more convenient as well.

**Comment by blogic** [comment]
@fake666 i share @nbd168 feelings, sorry ...

**Pull request closed without merging**
