### PR TITLE
hostapd-common: Multiple SSID support for STA interfaces

### PR DESCRIPTION
**Pull request by brunompena**
This patch adds support for multiple SSID configuration on STA
interfaces.
This is achieved by appending multiple "network" nodes to the supplicant
configuration and sending an update request (SIGHUP) to wpa_supplicant.

An example of such a configuration is:

config wifi-iface
        option device           'radio0'
        option ifname           'wlan0'
        option network          'wan'
        option mode             'sta'
        option hidden           '0'
        option ssid             'SSID_1'
        option encryption       'psk2'
        option passphrase       '1'
        option key              'SecretPassword_1'

config wifi-iface
        option device           'radio0'
        option ifname           'wlan0'
        option network          'wan'
        option mode             'sta'
        option hidden           '1'
        option ssid             'SSID_2'
        option encryption       'psk2'
        option passphrase       '1'
        option key              'SecretPassword_2'

Signed-off-by: Bruno Pena <brunompena@gmail.com>

### CODE REVIEW

**Comment by hauke** [comment]
Which devices have you tested this on? I am just interested which devices support multiple client SSIDs

**Comment by brunompena** [comment]
From your comment I see the title may be somewhat misleading.
This does not allow you to be connected to multiple SSID at the same time!
Instead it allows you to have multiple SSID for wpa_supplicant to use as they are available (just like you have it on your laptop).
I have this running on my TP-Link AC2600 so that it connects to the mobile hotspot of whomever is at home at that moment, to redistribute the Internet connectivity to all home devices.

**Comment by nbd168** [comment]
I think this way of specifying multiple networks is rather fragile. If you have the same `ifname`, but different values for `network`, things will be rather weird.
I would much rather like to see this implemented properly with a separate uci section type for a network belonging to an interface. If netifd becomes aware of those, wpa_supplicant could even notify it, so you could assign separate network configurations based on which one wpa_supplicant connected to.

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Pull request closed without merging**
