### PR TITLE
add WRTnode2q support

### PR DESCRIPTION
**Pull request by xzmu**
Add WRTnode2Q board support.
We test it, and it works well

### CODE REVIEW

**Comment by blogic** [comment]
there are several issues with the patch

* missing Signed-off-by line
* alphabetical ordering is utterly broken.

i can fix the second problem while merging but please provide a valid Signed-off-by line

**Comment by xzmu** [comment]
thanks a lot, I will fix the first problem

**Comment by xzmu** [comment]
I just added the sign-off line

**Comment by blogic** [comment]
is xzmu your fullname of a nickname ? SoB line needs to have the full name in it

**Comment by blogic** [comment]
@xzmu can we get a valid SoB line please with a fullname and not only nickname

**Comment by xzmu** [comment]
@blogic OK, I will do this,thanks for remind me

**Comment by blogic** [comment]
@xzmu 

I merged this into my staging tree. please test if it still works after my changes.
-> https://git.lede-project.org/lede/blogic/staging.git

**Comment by blogic** [comment]
@xzmu  did you test it ?

**Comment by xzmu** [comment]
@blogic I test it before I added signed off, I think after added signed off it will work too

**Comment by blogic** [comment]
@xzmu i cleaned up the patch and fixed alphabetical ordering. please test my staging to see if changes were correct. https://git.lede-project.org/lede/blogic/staging.git (see my comment from 3 days ago)

**Comment by xzmu** [comment]
@blogic I'm testing it now

**Comment by xzmu** [comment]
@blogic I tested it, and it works well.

**Pull request closed without merging**
