### PR TITLE
base-files: add submission service port

### PR DESCRIPTION
**Pull request by lucize**
prevent postfix start failure fatal: 0.0.0.0:submission: Unrecognized service

Signed-off-by: Lucian Cristian <lucian.cristian@gmail.com>

### CODE REVIEW

**Comment by stintel** [comment]
Pulled into my staging tree: https://git.lede-project.org/?p=lede/stintel/staging.git;a=commit;h=0c0c752f7d7cbf90777ce39e85b68a9949e49a69

**Comment by stintel** [comment]
Sorry, I was too soon. Please correct subject prefix (base-files), and I think we should follow IANA policy to add both TCP and UDP entries, even if the protocol doesn't use UDP.
See https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=587

**Comment by lucize** [comment]
wouldn't it be better to make a diiff with upstream services file and see what's missing, or the size of it does matter and we should add only relevant ports ?

**Comment by lucize** [comment]
renamed and added udp

**Comment by stintel** [comment]
Pulled into my staging tree: https://git.lede-project.org/?p=lede/stintel/staging.git;a=commit;h=8e75efc0fb52d02a0cdc13a5ad819b380de6f3da

**Pull request closed without merging**
