### PR TITLE
[patch v8]layerscape: add 64b/32b target for ls1043ardb/ls1012ardb device

### PR DESCRIPTION
**Pull request by fsl-jyt**
V8 patch update summary:
1.  Change Copyright/MAINTAINER E-mail address to my Gmail account, avoid the influence of company merger and change address.
2.  Put rcw(ls1043, ls1012) /uboot-32b(ls1043, ls1012) binary/ppfe firmware on github, create Makefile for pulling them to local while make procedure. Original package/boot/uboot-layerscape just for 64b build.
3.  Optimize default uboot bootargs.
4.  Adjust DEFAULT_PACKAGES for capable of both build ls1043 and ls1012 simultaneously.
5.  Optimize image/Makefile
6.  Add a new patch for ls1012ardb support based on ls1043 lede architecture.

### CODE REVIEW

**Comment by fsl-jyt** [comment]
[log-1028_ls1012-32b-64b_ls1043-32b-64b_bootup.txt](https://github.com/lede-project/source/files/558225/log-1028_ls1012-32b-64b_ls1043-32b-64b_bootup.txt)

A simple bootup log - ls1043/ls1012 64b/32b

**Comment by blogic** [comment]
merged, Thanks !

**Comment by fsl-jyt** [comment]
Thank you @blogic for merge my patch, this is a great encouragement to me.
And the same thanks also to all who have given me advice and help, thanks you very much!

I note the Openwrt is now rarely accepted new patches, whether it will no longer accept the new platform patch? Is it necessary for me to continue to provide the same patch to Openwrt github tree?

**Comment by jow-** [comment]
@fsl-jyt - the Layerscape 32bit variant seems to have issues building on our buildbots, please see http://phase1.builds.lede-project.org/builders/layerscape%2F32b/builds/7/steps/images/logs/stdio.

The final error is:

    FATAL ERROR: Couldn't open "/opt/buildbot/slaves/lede-targets-tah/layerscape_32b/build/build_dir/target-arm_cortex-a9_musl-1.1.15_eabi/linux-layerscape_32b/linux-4.4.30/arch/arm/boot/dts/../../../arm64/boot/dts/freescale/fsl-ls1012a-rdb.dtb.tmp": No such file or directory

**Comment by fsl-jyt** [comment]
Hi Jo-Philipp Wich,

After several attempts I reproduced this bug, I will investigate the root cause and try to fix it.
Find a clue, after arise this bug then run make again, the build process will success.

Thanks & Best Regards
Jiang Yutang

发件人: Jo-Philipp Wich [mailto:notifications@github.com]
发送时间: Saturday, November 05, 2016 2:30 AM
收件人: lede-project/source <source@noreply.github.com>
抄送: Y.T. Jiang <yutang.jiang@nxp.com>; Mention <mention@noreply.github.com>
主题: Re: [lede-project/source] [patch v8]layerscape: add 64b/32b target for ls1043ardb/ls1012ardb device (#450)


@fsl-jyt<https://github.com/fsl-jyt> - the Layerscape 32bit variant seems to have issues building on our buildbots, please see http://phase1.builds.lede-project.org/builders/layerscape%2F32b/builds/7/steps/images/logs/stdio.

The final error is:

FATAL ERROR: Couldn't open "/opt/buildbot/slaves/lede-targets-tah/layerscape_32b/build/build_dir/target-arm_cortex-a9_musl-1.1.15_eabi/linux-layerscape_32b/linux-4.4.30/arch/arm/boot/dts/../../../arm64/boot/dts/freescale/fsl-ls1012a-rdb.dtb.tmp": No such file or directory

**Comment by fsl-jyt** [comment]
Hi Jo-Philipp Wich,

Through more tests and analysis, I found the root cause: in my Device/ls1012ardb IMAGES variable, there are two separate firmware references to the same packages, while do mult-job compile, the same package build process will arise conflict occasionally. I will combine the PR481 to optimize the code and fix this bug.

Thanks & Best Regards
Jiang Yutang


发件人: Y.T. Jiang
发送时间: Monday, November 07, 2016 11:47 AM
收件人: lede-project/source <reply@reply.github.com>; lede-project/source <source@noreply.github.com>
抄送: Mention <mention@noreply.github.com>
主题: 答复: [lede-project/source] [patch v8]layerscape: add 64b/32b target for ls1043ardb/ls1012ardb device (#450)

Hi Jo-Philipp Wich,

After several attempts I reproduced this bug, I will investigate the root cause and try to fix it.
Find a clue, after arise this bug then run make again, the build process will success.

Thanks & Best Regards
Jiang Yutang

发件人: Jo-Philipp Wich [mailto:notifications@github.com]
发送时间: Saturday, November 05, 2016 2:30 AM
收件人: lede-project/source <source@noreply.github.com<mailto:source@noreply.github.com>>
抄送: Y.T. Jiang <yutang.jiang@nxp.com<mailto:yutang.jiang@nxp.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
主题: Re: [lede-project/source] [patch v8]layerscape: add 64b/32b target for ls1043ardb/ls1012ardb device (#450)


@fsl-jyt<https://github.com/fsl-jyt> - the Layerscape 32bit variant seems to have issues building on our buildbots, please see http://phase1.builds.lede-project.org/builders/layerscape%2F32b/builds/7/steps/images/logs/stdio.

The final error is:

FATAL ERROR: Couldn't open "/opt/buildbot/slaves/lede-targets-tah/layerscape_32b/build/build_dir/target-arm_cortex-a9_musl-1.1.15_eabi/linux-layerscape_32b/linux-4.4.30/arch/arm/boot/dts/../../../arm64/boot/dts/freescale/fsl-ls1012a-rdb.dtb.tmp": No such file or directory

**Comment by jow-** [comment]
@fsl-jyt - thanks a lot for looking into this so quickly.

I spotted another issue in the 64b subtarget which is not strictly your fault but we should address it nonetheless; the `uboot-layerscape` component fails to build on most of our buildslaves because it uses a TCL script to process the final binary but `tclsh` is no build requirement of the LEDE buildroot, therfore it is not installed on any of our builders.

The error excerpt is:

    tclsh byte_swap.tcl u-boot-dtb.bin u-boot-swap.bin 8
    make[3]: tclsh: Command not found
    make[3]: *** [u-boot-dtb.bin] Error 127

The easiest fix would be rewriting that `byte_swap.tcl` script in Perl, since that is guaranteed to be present.

**Comment by fsl-jyt** [comment]
Thank you Jo-Philipp Wich!

For ugly design reasons, some dev board need a byte swap operation to uboot or rcw.
The TCL script byte_swap.tcl come from other guy, I'm not familiar with both TCL and Perl, I need more time to coordinate the solution to rewrite the script.

Thanks & Best Regards
Jiang Yutang

发件人: Jo-Philipp Wich [mailto:notifications@github.com]
发送时间: Tuesday, November 08, 2016 5:26 PM
收件人: lede-project/source <source@noreply.github.com>
抄送: Y.T. Jiang <yutang.jiang@nxp.com>; Mention <mention@noreply.github.com>
主题: Re: [lede-project/source] [patch v8]layerscape: add 64b/32b target for ls1043ardb/ls1012ardb device (#450)


@fsl-jyt<https://github.com/fsl-jyt> - thanks a lot for looking into this so quickly.

I spotted another issue in the 64b subtarget which is not strictly your fault but we should address it nonetheless; the uboot-layerscape component fails to build on most of our buildslaves because it uses a TCL script to process the final binary but tclsh is no build requirement of the LEDE buildroot, therfore it is not installed on any of our builders.

The error excerpt is:

tclsh byte_swap.tcl u-boot-dtb.bin u-boot-swap.bin 8

make[3]: tclsh: Command not found

make[3]: *** [u-boot-dtb.bin] Error 127

The easiest fix would be rewriting that byte_swap.tcl script in Perl, since that is guaranteed to be present.

**Comment by fsl-jyt** [comment]
Hi Jo-Philipp Wich,

I have submit a PR 501 to fix this bug, please review:
https://github.com/lede-project/source/pull/501


Thanks & Best Regards
Jiang Yutang


发件人: Y.T. Jiang
发送时间: Tuesday, November 08, 2016 5:20 PM
收件人: lede-project/source <reply@reply.github.com>; lede-project/source <source@noreply.github.com>
抄送: Mention <mention@noreply.github.com>
主题: 答复: [lede-project/source] [patch v8]layerscape: add 64b/32b target for ls1043ardb/ls1012ardb device (#450)

Hi Jo-Philipp Wich,

Through more tests and analysis, I found the root cause: in my Device/ls1012ardb IMAGES variable, there are two separate firmware references to the same packages, while do mult-job compile, the same package build process will arise conflict occasionally. I will combine the PR481 to optimize the code and fix this bug.

Thanks & Best Regards
Jiang Yutang


发件人: Y.T. Jiang
发送时间: Monday, November 07, 2016 11:47 AM
收件人: lede-project/source <reply@reply.github.com>; lede-project/source <source@noreply.github.com<mailto:source@noreply.github.com>>
抄送: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
主题: 答复: [lede-project/source] [patch v8]layerscape: add 64b/32b target for ls1043ardb/ls1012ardb device (#450)

Hi Jo-Philipp Wich,

After several attempts I reproduced this bug, I will investigate the root cause and try to fix it.
Find a clue, after arise this bug then run make again, the build process will success.

Thanks & Best Regards
Jiang Yutang

发件人: Jo-Philipp Wich [mailto:notifications@github.com]
发送时间: Saturday, November 05, 2016 2:30 AM
收件人: lede-project/source <source@noreply.github.com<mailto:source@noreply.github.com>>
抄送: Y.T. Jiang <yutang.jiang@nxp.com<mailto:yutang.jiang@nxp.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
主题: Re: [lede-project/source] [patch v8]layerscape: add 64b/32b target for ls1043ardb/ls1012ardb device (#450)


@fsl-jyt<https://github.com/fsl-jyt> - the Layerscape 32bit variant seems to have issues building on our buildbots, please see http://phase1.builds.lede-project.org/builders/layerscape%2F32b/builds/7/steps/images/logs/stdio.

The final error is:

FATAL ERROR: Couldn't open "/opt/buildbot/slaves/lede-targets-tah/layerscape_32b/build/build_dir/target-arm_cortex-a9_musl-1.1.15_eabi/linux-layerscape_32b/linux-4.4.30/arch/arm/boot/dts/../../../arm64/boot/dts/freescale/fsl-ls1012a-rdb.dtb.tmp": No such file or directory

**Comment by fsl-jyt** [comment]
Jo-Philipp Wich!

I have studied TCL and Perl then rewriting that script in Perl, now submit a new PR 521 patch to replace the old TCL script. Please review, Thank you!
https://github.com/lede-project/source/pull/521


Thanks & Best Regards
Jiang Yutang

发件人: Y.T. Jiang
发送时间: Tuesday, November 08, 2016 7:06 PM
收件人: 'lede-project/source' <reply@reply.github.com>; lede-project/source <source@noreply.github.com>
抄送: Mention <mention@noreply.github.com>
主题: 答复: [lede-project/source] [patch v8]layerscape: add 64b/32b target for ls1043ardb/ls1012ardb device (#450)


Thank you Jo-Philipp Wich!

For ugly design reasons, some dev board need a byte swap operation to uboot or rcw.
The TCL script byte_swap.tcl come from other guy, I'm not familiar with both TCL and Perl, I need more time to coordinate the solution to rewrite the script.

Thanks & Best Regards
Jiang Yutang

发件人: Jo-Philipp Wich [mailto:notifications@github.com]
发送时间: Tuesday, November 08, 2016 5:26 PM
收件人: lede-project/source <source@noreply.github.com<mailto:source@noreply.github.com>>
抄送: Y.T. Jiang <yutang.jiang@nxp.com<mailto:yutang.jiang@nxp.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
主题: Re: [lede-project/source] [patch v8]layerscape: add 64b/32b target for ls1043ardb/ls1012ardb device (#450)


@fsl-jyt<https://github.com/fsl-jyt> - thanks a lot for looking into this so quickly.

I spotted another issue in the 64b subtarget which is not strictly your fault but we should address it nonetheless; the uboot-layerscape component fails to build on most of our buildslaves because it uses a TCL script to process the final binary but tclsh is no build requirement of the LEDE buildroot, therfore it is not installed on any of our builders.

The error excerpt is:

tclsh byte_swap.tcl u-boot-dtb.bin u-boot-swap.bin 8

make[3]: tclsh: Command not found

make[3]: *** [u-boot-dtb.bin] Error 127

The easiest fix would be rewriting that byte_swap.tcl script in Perl, since that is guaranteed to be present.

**Pull request closed without merging**
