### PR TITLE
ramips: use default setting for 4K_SECTORS_LIMIT

### PR DESCRIPTION
**Pull request by f00b4r0**
4K_SECTORS was introduced in 925e63e, which clearly states that
the intended target were 4MB devices.

Signed-off-by: Thibaut VARENE <hacks@slashdirt.org>

### CODE REVIEW

**Comment by mkresin** [comment]
As discussed on IRC, the patch as it is will break the same stuff I already broke by switching from 64k to 4k sectors. It needs a little bit more love.

**Comment by f00b4r0** [comment]
@heinzek could you test this on Archer C50 please? "keep settings" is currently broken on Archer C50 (among others). Can you try:

- from a booted master **WITHOUT** this PR applied, with custom settings, flashing an image **WITH** this PR applied with `sysupgrade -c`: **are settings preserved?**
- from a booted master **WITH** this PR applied, with custom settings, flashing an image **WITH** this PR applied with `sysupgrade -c` (e.g. same image than booted one): **are settings preserved?**

Please provide bootlogs in both cases (we expect to see jffs2 messages), thank you!

**Comment by f00b4r0** [comment]
A few notes about the implications here, based on input from @mkresin:

- changing BLOCKSIZE from 4k to 64k will break settings preservation on upgrade (`sysupgrade -c`) for the (4?) concerned devices because jffs2 takes the blocksize into account when creating the temporary jffs2 partition
- This would be a one-time breakage (similar to what happened when 4k BLOCKSIZE was initially introduced) and it can be worked around by backing up the config (`sysupgrade -b` or GUI interface) and restoring it afterwards.

About the WLR-600, as I understand it the problems comes as follows:

- 4k BLOCKSIZE is necessary to keep the 4k-alignement of the partitions, consistent with OFW scheme (this is necessary to preserve the ability to flash back OFW)
- keeping 4k BLOCKSIZE with 64k effective EB size should work as far as squashfs is concerned, but will be sub-optimal performance wise since in 15 out of 16 cases, the partial-eraser will be needed.
- 4k BLOCKSIZE with 64k EBs **should** work with the jffs2 overlay (contrary to the opposite case), as evidenced by [jffs2 documentation](http://www.linux-mtd.infradead.org/doc/jffs2.html):
  
> - JFFS2 treats each erase block of the flash separately. It will never write nodes which cross from one erase block to another.
> - The default is 64KiB, because that's the smallest erase block size you're likely to encounter often, and creating an image with smaller eraseblock size than the actual hardware is harmless -- it just gives annoying messages

Thus, for this device only maybe we can keep 4k BLOCKSIZE (regardless of it using 64k EBs in because of its larger flash), assuming the above analysis is correct: the partial-eraser works as intended and it doesn't break jffs2 (which must be tested/confirmed). There will be a penalty on the flash chip because the EBs will typically wear out more than they would if the jffs2 blocksize was matching the hardware EB size.

Comments welcome.

**Comment by f00b4r0** [comment]
@mkresin points out that the overlay creation routine requires the jffs2 EOF marker to be EB-aligned. In that case we could pad the rootfs_data to 64k to achieve this result.

**Comment by f00b4r0** [comment]
Testing on ex3800. First reboot after sysupgrade, config was preserved and dmesg showed the expected warnings:

```
[    4.894021] init: - preinit -
[    6.644507] 8021q: adding VLAN 0 to HW filter on device eth0
[    8.035381] jffs2: CLEANMARKER node found at 0x00001000, not first node in block (0x00000000)
[    8.059942] jffs2: Empty flash at 0x000017dc ends at 0x00002000
[    8.071768] jffs2: jffs2_scan_eraseblock(): Magic bitmask 0x1985 not found at 0x00002000: 0xadde instead
[    8.098213] jffs2: Empty flash at 0x00002004 ends at 0x00003000
[    8.117537] jffs2: CLEANMARKER node found at 0x00003000, not first node in block (0x00000000)
[    8.142083] jffs2: Empty flash at 0x0000300c ends at 0x00004000
[    8.153894] jffs2: CLEANMARKER node found at 0x00004000, not first node in block (0x00000000)
[    8.178426] jffs2: Empty flash at 0x0000400c ends at 0x00005000
[    8.190236] jffs2: CLEANMARKER node found at 0x00005000, not first node in block (0x00000000)
[    8.222263] jffs2: Empty flash at 0x0000500c ends at 0x00006000
[    8.234089] jffs2: CLEANMARKER node found at 0x00006000, not first node in block (0x00000000)
[    8.258604] jffs2: Empty flash at 0x0000600c ends at 0x00007000
[    8.270434] jffs2: CLEANMARKER node found at 0x00007000, not first node in block (0x00000000)
[    8.302467] jffs2: Empty flash at 0x0000700c ends at 0x00008000
[    8.314275] jffs2: CLEANMARKER node found at 0x00008000, not first node in block (0x00000000)
[    8.338795] jffs2: Empty flash at 0x0000800c ends at 0x00009000
[    8.350610] jffs2: CLEANMARKER node found at 0x00009000, not first node in block (0x00000000)
[    8.382649] jffs2: Empty flash at 0x0000900c ends at 0x0000a000
[    8.394475] jffs2: CLEANMARKER node found at 0x0000a000, not first node in block (0x00000000)
[    8.418990] jffs2: Empty flash at 0x0000a00c ends at 0x0000b000
[    8.430818] jffs2: CLEANMARKER node found at 0x0000b000, not first node in block (0x00000000)
[    8.462852] jffs2: Empty flash at 0x0000b00c ends at 0x0000c000
[    8.474659] jffs2: CLEANMARKER node found at 0x0000c000, not first node in block (0x00000000)
[    8.499178] jffs2: Empty flash at 0x0000c00c ends at 0x0000d000
[    8.510995] jffs2: CLEANMARKER node found at 0x0000d000, not first node in block (0x00000000)
[    8.543022] jffs2: Empty flash at 0x0000d00c ends at 0x0000e000
[    8.554848] jffs2: CLEANMARKER node found at 0x0000e000, not first node in block (0x00000000)
[    8.579363] jffs2: Empty flash at 0x0000e00c ends at 0x0000f000
[    8.591191] jffs2: CLEANMARKER node found at 0x0000f000, not first node in block (0x00000000)
[    8.640836] jffs2: Empty flash at 0x00050530 ends at 0x00051000
[    8.652679] jffs2: CLEANMARKER node found at 0x00051000, not first node in block (0x00050000)
[    8.677207] jffs2: Empty flash at 0x0005100c ends at 0x00052000
[    8.689030] jffs2: CLEANMARKER node found at 0x00052000, not first node in block (0x00050000)
[    8.721065] jffs2: Empty flash at 0x0005200c ends at 0x00053000
[    8.732872] jffs2: CLEANMARKER node found at 0x00053000, not first node in block (0x00050000)
[    8.757406] jffs2: Empty flash at 0x0005300c ends at 0x00054000
[    8.769213] jffs2: CLEANMARKER node found at 0x00054000, not first node in block (0x00050000)
[    8.801240] jffs2: Empty flash at 0x0005400c ends at 0x00055000
[    8.813066] jffs2: CLEANMARKER node found at 0x00055000, not first node in block (0x00050000)
[    8.837604] jffs2: Empty flash at 0x0005500c ends at 0x00056000
[    8.849427] jffs2: CLEANMARKER node found at 0x00056000, not first node in block (0x00050000)
[    8.881467] jffs2: Empty flash at 0x0005600c ends at 0x00057000
[    8.893274] jffs2: CLEANMARKER node found at 0x00057000, not first node in block (0x00050000)
[    8.917810] jffs2: Empty flash at 0x0005700c ends at 0x00058000
[    8.929617] jffs2: CLEANMARKER node found at 0x00058000, not first node in block (0x00050000)
[    8.961647] jffs2: Empty flash at 0x0005800c ends at 0x00059000
[    8.973473] jffs2: CLEANMARKER node found at 0x00059000, not first node in block (0x00050000)
[    8.997999] jffs2: Empty flash at 0x0005900c ends at 0x0005a000
[    9.009824] jffs2: CLEANMARKER node found at 0x0005a000, not first node in block (0x00050000)
[    9.041857] jffs2: Empty flash at 0x0005a00c ends at 0x0005b000
[    9.053665] jffs2: CLEANMARKER node found at 0x0005b000, not first node in block (0x00050000)
[    9.078200] jffs2: Empty flash at 0x0005b00c ends at 0x0005c000
[    9.090007] jffs2: CLEANMARKER node found at 0x0005c000, not first node in block (0x00050000)
[    9.122034] jffs2: Empty flash at 0x0005c00c ends at 0x0005d000
[    9.133861] jffs2: CLEANMARKER node found at 0x0005d000, not first node in block (0x00050000)
[    9.158390] jffs2: Empty flash at 0x0005d00c ends at 0x0005e000
[    9.170214] jffs2: CLEANMARKER node found at 0x0005e000, not first node in block (0x00050000)
[    9.202246] jffs2: Empty flash at 0x0005e00c ends at 0x0005f000
[    9.214053] jffs2: CLEANMARKER node found at 0x0005f000, not first node in block (0x00050000)
[    9.278957] jffs2: CLEANMARKER node found at 0x00431000, not first node in block (0x00430000)
[    9.303683] jffs2: CLEANMARKER node found at 0x00432000, not first node in block (0x00430000)
[    9.328409] jffs2: CLEANMARKER node found at 0x00433000, not first node in block (0x00430000)
[    9.353106] jffs2: CLEANMARKER node found at 0x00434000, not first node in block (0x00430000)
[    9.377830] jffs2: CLEANMARKER node found at 0x00435000, not first node in block (0x00430000)
[    9.402573] jffs2: CLEANMARKER node found at 0x00436000, not first node in block (0x00430000)
[    9.427318] jffs2: CLEANMARKER node found at 0x00437000, not first node in block (0x00430000)
[    9.452035] jffs2: CLEANMARKER node found at 0x00438000, not first node in block (0x00430000)
[    9.476718] jffs2: CLEANMARKER node found at 0x00439000, not first node in block (0x00430000)
[    9.501449] jffs2: CLEANMARKER node found at 0x0043a000, not first node in block (0x00430000)
[    9.526000] jffs2: Empty flash at 0x0043a00c ends at 0x0043b000
[    9.537812] jffs2: CLEANMARKER node found at 0x0043b000, not first node in block (0x00430000)
[    9.569835] jffs2: Empty flash at 0x0043b00c ends at 0x0043c000
[    9.581669] jffs2: CLEANMARKER node found at 0x0043c000, not first node in block (0x00430000)
[    9.606197] jffs2: Empty flash at 0x0043c00c ends at 0x0043d000
[    9.618020] jffs2: CLEANMARKER node found at 0x0043d000, not first node in block (0x00430000)
[    9.650038] jffs2: Empty flash at 0x0043d00c ends at 0x0043e000
[    9.661853] jffs2: CLEANMARKER node found at 0x0043e000, not first node in block (0x00430000)
[    9.686389] jffs2: Empty flash at 0x0043e00c ends at 0x0043f000
[    9.698196] jffs2: CLEANMARKER node found at 0x0043f000, not first node in block (0x00430000)
[    9.730541] jffs2: notice: (346) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 orphan) found.
[    9.763037] mount_root: switching to jffs2 overlay
```

The mount appeared clean and the configuration was preserved.

However, upon subsequent reboot more warnings are issued:

```
[    4.894021] init: - preinit -
[    6.644507] 8021q: adding VLAN 0 to HW filter on device eth0
[    8.035381] jffs2: CLEANMARKER node found at 0x00001000, not first node in block (0x00000000)
[    8.059942] jffs2: Empty flash at 0x000017dc ends at 0x00002000
[    8.071768] jffs2: jffs2_scan_eraseblock(): Magic bitmask 0x1985 not found at 0x00002000: 0xadde instead
[    8.098213] jffs2: Empty flash at 0x00002004 ends at 0x00003000
[    8.117537] jffs2: CLEANMARKER node found at 0x00003000, not first node in block (0x00000000)
[    8.142083] jffs2: Empty flash at 0x0000300c ends at 0x00004000
[    8.153894] jffs2: CLEANMARKER node found at 0x00004000, not first node in block (0x00000000)
[    8.178426] jffs2: Empty flash at 0x0000400c ends at 0x00005000
[    8.190236] jffs2: CLEANMARKER node found at 0x00005000, not first node in block (0x00000000)
[    8.222263] jffs2: Empty flash at 0x0000500c ends at 0x00006000
[    8.234089] jffs2: CLEANMARKER node found at 0x00006000, not first node in block (0x00000000)
[    8.258604] jffs2: Empty flash at 0x0000600c ends at 0x00007000
[    8.270434] jffs2: CLEANMARKER node found at 0x00007000, not first node in block (0x00000000)
[    8.302467] jffs2: Empty flash at 0x0000700c ends at 0x00008000
[    8.314275] jffs2: CLEANMARKER node found at 0x00008000, not first node in block (0x00000000)
[    8.338795] jffs2: Empty flash at 0x0000800c ends at 0x00009000
[    8.350610] jffs2: CLEANMARKER node found at 0x00009000, not first node in block (0x00000000)
[    8.382649] jffs2: Empty flash at 0x0000900c ends at 0x0000a000
[    8.394475] jffs2: CLEANMARKER node found at 0x0000a000, not first node in block (0x00000000)
[    8.418990] jffs2: Empty flash at 0x0000a00c ends at 0x0000b000
[    8.430818] jffs2: CLEANMARKER node found at 0x0000b000, not first node in block (0x00000000)
[    8.462852] jffs2: Empty flash at 0x0000b00c ends at 0x0000c000
[    8.474659] jffs2: CLEANMARKER node found at 0x0000c000, not first node in block (0x00000000)
[    8.499178] jffs2: Empty flash at 0x0000c00c ends at 0x0000d000
[    8.510995] jffs2: CLEANMARKER node found at 0x0000d000, not first node in block (0x00000000)
[    8.543022] jffs2: Empty flash at 0x0000d00c ends at 0x0000e000
[    8.554848] jffs2: CLEANMARKER node found at 0x0000e000, not first node in block (0x00000000)
[    8.579363] jffs2: Empty flash at 0x0000e00c ends at 0x0000f000
[    8.591191] jffs2: CLEANMARKER node found at 0x0000f000, not first node in block (0x00000000)
[    8.640836] jffs2: Empty flash at 0x00050530 ends at 0x00051000
[    8.652679] jffs2: CLEANMARKER node found at 0x00051000, not first node in block (0x00050000)
[    8.677207] jffs2: Empty flash at 0x0005100c ends at 0x00052000
[    8.689030] jffs2: CLEANMARKER node found at 0x00052000, not first node in block (0x00050000)
[    8.721065] jffs2: Empty flash at 0x0005200c ends at 0x00053000
[    8.732872] jffs2: CLEANMARKER node found at 0x00053000, not first node in block (0x00050000)
[    8.757406] jffs2: Empty flash at 0x0005300c ends at 0x00054000
[    8.769213] jffs2: CLEANMARKER node found at 0x00054000, not first node in block (0x00050000)
[    8.801240] jffs2: Empty flash at 0x0005400c ends at 0x00055000
[    8.813066] jffs2: CLEANMARKER node found at 0x00055000, not first node in block (0x00050000)
[    8.837604] jffs2: Empty flash at 0x0005500c ends at 0x00056000
[    8.849427] jffs2: CLEANMARKER node found at 0x00056000, not first node in block (0x00050000)
[    8.881467] jffs2: Empty flash at 0x0005600c ends at 0x00057000
[    8.893274] jffs2: CLEANMARKER node found at 0x00057000, not first node in block (0x00050000)
[    8.917810] jffs2: Empty flash at 0x0005700c ends at 0x00058000
[    8.929617] jffs2: CLEANMARKER node found at 0x00058000, not first node in block (0x00050000)
[    8.961647] jffs2: Empty flash at 0x0005800c ends at 0x00059000
[    8.973473] jffs2: CLEANMARKER node found at 0x00059000, not first node in block (0x00050000)
[    8.997999] jffs2: Empty flash at 0x0005900c ends at 0x0005a000
[    9.009824] jffs2: CLEANMARKER node found at 0x0005a000, not first node in block (0x00050000)
[    9.041857] jffs2: Empty flash at 0x0005a00c ends at 0x0005b000
[    9.053665] jffs2: CLEANMARKER node found at 0x0005b000, not first node in block (0x00050000)
[    9.078200] jffs2: Empty flash at 0x0005b00c ends at 0x0005c000
[    9.090007] jffs2: CLEANMARKER node found at 0x0005c000, not first node in block (0x00050000)
[    9.122034] jffs2: Empty flash at 0x0005c00c ends at 0x0005d000
[    9.133861] jffs2: CLEANMARKER node found at 0x0005d000, not first node in block (0x00050000)
[    9.158390] jffs2: Empty flash at 0x0005d00c ends at 0x0005e000
[    9.170214] jffs2: CLEANMARKER node found at 0x0005e000, not first node in block (0x00050000)
[    9.202246] jffs2: Empty flash at 0x0005e00c ends at 0x0005f000
[    9.214053] jffs2: CLEANMARKER node found at 0x0005f000, not first node in block (0x00050000)
[    9.278957] jffs2: CLEANMARKER node found at 0x00431000, not first node in block (0x00430000)
[    9.303683] jffs2: CLEANMARKER node found at 0x00432000, not first node in block (0x00430000)
[    9.328409] jffs2: CLEANMARKER node found at 0x00433000, not first node in block (0x00430000)
[    9.353106] jffs2: CLEANMARKER node found at 0x00434000, not first node in block (0x00430000)
[    9.377830] jffs2: CLEANMARKER node found at 0x00435000, not first node in block (0x00430000)
[    9.402573] jffs2: CLEANMARKER node found at 0x00436000, not first node in block (0x00430000)
[    9.427318] jffs2: CLEANMARKER node found at 0x00437000, not first node in block (0x00430000)
[    9.452035] jffs2: CLEANMARKER node found at 0x00438000, not first node in block (0x00430000)
[    9.476718] jffs2: CLEANMARKER node found at 0x00439000, not first node in block (0x00430000)
[    9.501449] jffs2: CLEANMARKER node found at 0x0043a000, not first node in block (0x00430000)
[    9.526000] jffs2: Empty flash at 0x0043a00c ends at 0x0043b000
[    9.537812] jffs2: CLEANMARKER node found at 0x0043b000, not first node in block (0x00430000)
[    9.569835] jffs2: Empty flash at 0x0043b00c ends at 0x0043c000
[    9.581669] jffs2: CLEANMARKER node found at 0x0043c000, not first node in block (0x00430000)
[    9.606197] jffs2: Empty flash at 0x0043c00c ends at 0x0043d000
[    9.618020] jffs2: CLEANMARKER node found at 0x0043d000, not first node in block (0x00430000)
[    9.650038] jffs2: Empty flash at 0x0043d00c ends at 0x0043e000
[    9.661853] jffs2: CLEANMARKER node found at 0x0043e000, not first node in block (0x00430000)
[    9.686389] jffs2: Empty flash at 0x0043e00c ends at 0x0043f000
[    9.698196] jffs2: CLEANMARKER node found at 0x0043f000, not first node in block (0x00430000)
[    9.730541] jffs2: notice: (346) jffs2_build_xattr_subsystem: complete building xattr subsystem, 0 of xdatum (0 unchecked, 0 orphan) and 0 of xref (0 dead, 0 orphan) found.
[    9.763037] mount_root: switching to jffs2 overlay
```

After the 3rd reboot the device wouldn't respond to ping, I assume the fs got corrupted at this point because the device booted fine in failsafe mode and issuing `mount_root` showed lots of error in dmesg. I then ran `firstboot` (after unmounting the overlay) to erase the jffs2 partition but that wasn't enough: the warnings were still there on the next boot. I ended up having to do a full reflash with `-n -p` to finally get a clean jffs2 overlay.

It looks like we either need to prevent config preservation when switching to larger eraseblocks, or we need to find an intermediary way to reformat the jffs2 overlay, and write back the changes afterwards.

**Pull request closed without merging**
