### PR TITLE
[RFC]: Add support for kernel 4.14

### PR DESCRIPTION
**Pull request by hauke**
This adds support for kernel 4.14 to LEDE.
This ports the generic patches to kernel 4.14 and also adds support for 
kernel 4.14 to the x86 target, I am also working on adding support for 
the lantiq target, but there are still some problems with the xrx200 
Ethernet driver.
I would like to use this on some arm64 boards where the main kernel 
development happens in the upstream kernel, for these boards it should 
be much easier to make them work on kernel 4.14 compared to kernel 4.9. 

My development tree can be found here:
https://git.lede-project.org/?p=lede/hauke/staging.git;a=shortlog;h=refs/heads/kernel-4.14
I will update this tree more often than these patches sets, but it will 
also be rebased.
It could be that not all patches went to the mailing list because they 
are too big.

This is my current state and everything should compile for the x86 
target, I think this is now in  a state to request some comments.
If some of my changes are looking suspicious to you please send a mail, 
I am also not sure about everything and I assume that there are probably 
some kernel configuration options set to the wrong value and some 
patches probably still have some problems.

### CODE REVIEW

**Comment by hauke** [comment]
@easyteacher  I removed the patch deactivating kmod-sched-cake it was more than a month ago when I tested this.

**Comment by luaraneda** [comment]
I ported some patches to get it compiling and and working on an ipq806x target (Asus AC58U).
- Ethernet (WAN, LAN), Wi-Fi, and flash (SPI NAND) are working.
- USB, PCIe, and some other features are not working (patches not ported yet)

I still have to do more testing, but the PCIe patches require changes that, at this time, are beyond my understanding.

**Comment by hauke** [comment]
@luaraneda have you found any problems in this patch set?

**Comment by luaraneda** [comment]
Not yet, I'm planning to do more testing (and patch porting) on the weekend, as it's not my main router at the moment.
I'll let you know if I find any problem.

**Comment by hauke** [comment]
I merged this into master.

**Comment by dissent1** [comment]
@luaraneda hey, where can I find your current state of porting ipq806x target onto k4.14? I'm into this for ipq8064/5.

**Comment by luaraneda** [comment]
@dissent1 here it is:
[https://github.com/luaraneda/source/tree/ipq806x-k4.14](https://github.com/luaraneda/source/tree/ipq806x-k4.14)

I should warn you that I removed several patches that are not yet upstreamed, and need rework, just to make the kernel compile. I'm going to assemble a detailed list after work.

I compile and run tested on an Asus ac58u (had to deselect the USB PHY driver).

**Comment by dissent1** [comment]
@luaraneda 
Am I correct that you've deleted only OPP-cpufreq patchset and pci patch? I have a rebased opp-cpufreq patchset. A split pci patch is in nbd's tree, so it will be easier to reapply.
If that's all I'll add add those patches.

**Comment by luaraneda** [comment]
Yes, those are some of the patches. I removed them, and then realized that some were modified/deleted on nbd's staging tree, specially the PCIe one, so I stopped working on them.

Like I said, after work I'll have more details :)

**Comment by luaraneda** [comment]
@dissent1 
I just committed a file to my repo with the status of the patches.
I took me a while to find the commits for the upstreamed patches, because the first time I didn't save them.
Please double check the patches, as I could be wrong about some of them.

I will continue working on some patches, and updating my repo.

I hope this will serve you at least as a starting point ;)

**Comment by dissent1** [comment]
@luaraneda biggest part is done it seems. I'll take care of ipq8064/5 specific patches after ipq806x  changes that remain in @nbd168 tree get merged into master.

@chunkeey there're are some ipq40xx patches under question, could you take a look if you are interested :)

**Pull request closed without merging**
