### PR TITLE
libpcap: bump to last commit

### PR DESCRIPTION
**Pull request by Ansuel**
Drop of 2 patch pushed upstream, refresh patch and bump to 1.9.0 version.

> Summary for 1.9.0 libpcap release
>   Man page improvements
>   Fix Linux cooked mode userspace filtering (GitHub pull request #429)
>   Fix compilation if IPv6 support not enabled
>   Fix some Linux memory-mapped capture buffer size issues
>   Don't fail if kernel filter can't be set on Linux (GitHub issue
>     #549)
>   Improve sorting of interfaces for pcap_findalldevs()
>   Don't list Linux usbmon devices if usbmon module isn't loaded
>   Report PCAP_ERROR_PERM_DENIED if no permission to open Linux usbmon
>     devices
>   Fix DLT_ type for Solaris IPNET devices
>   Always return an error message for errors finding DAG or Myricom
>     devices
>   If possible, don't require that a device be openable when
>     enumerating them for pcap_findalldevs()
>   Don't put incompletely-initialized addresses in the address list for
>   When finding Myricom devices, update description for regular
>     interfaces that are Myricom devices and handle SNF_FLAGS=0x2(port
>     aggregation enabled)
>   Fix compilation error in DAG support
>   Fix issues with CMake configuration

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by commodo** [comment]
there is a general preference for release tar-balls instead of git repo hashes

especially if the project releases regularly
[ there are some cases where there hasn't been a release tarball in 2+ years, but the git repo has recent stuff ] 

for libpcap, it looks like they release fairly regularly [ every N months or so ]
so, i think it would be preferred to wait for a release tarball ; than to move to a git repo source

**Comment by Ansuel** [comment]
I made this pr as we can drop 2 patch and from the git commit version 1.9.0 looks in the RC stage so...

**Comment by Ansuel** [comment]
Compiled and tested WRT1900ACS

**Comment by blogic** [comment]
is this a release version or just a snapshot file from git ?

**Comment by Ansuel** [comment]
@blogic From the commit looks like a rc to 1.9 version

**Comment by diizzyy** [comment]
Unless you have use-case where you need to upgrade libpcap please wait until 1.9.0 gets a proper release.

**Comment by blogic** [comment]
@Ansuel i have to agree with @diizzyy. please dont bump to a RC unless there is some critical reason to do so.

**Comment by blogic** [comment]
closing, please reopen when rebased ontop of a new stable release.

**Pull request closed without merging**
