### PR TITLE
ar71xx: fix lan ports on ens202ext

### PR DESCRIPTION
**Pull request by hanetzer**
Fixes FS#1084

May require a factory reset, it did in my case after a fresh install from factory.img
from stock firmware.

Signed-off-by: Marty E. Plummer <hanetzer@protonmail.com>

### CODE REVIEW

**Comment by mkresin** [comment]
Please add a proper commit message which describes what was wrong and what has been changed to fix it. At the moment it looks like a simple change from a lan + wan configuration to both ports as lan configuration.

Add the reference to the flyspray ticket to the commit message as well.

**Comment by hanetzer** [comment]
@mkresin is this to your liking, or should the flyspray reference be handled differently?

**Comment by mkresin** [comment]
If you change the commit message to:

```
ar71xx: fix lan ports on ens202ext

In the stock firmware both eth0 and eth1 are set to br-lan,
add this behavior to our images.

Fixes: FS#1084

Signed-off-by: Marty E. Plummer <hanetzer@protonmail.com>
```

i would say it is perfect.

**Comment by mkresin** [comment]
merged, thanks!

**Pull request closed without merging**
