### PR TITLE
grub2: upgrade to version 2.02-beta3

### PR DESCRIPTION
**Pull request by commodo**
After trying out a few things, I ended up upgrading grub2 internally.

It seems that grub2's build is a bit picky on the host-side ; even after upgrading it.
While `PKG_FIXUP:=autoreconf` seems to error mentioned in inital PR message (and commit https://github.com/lede-project/source/pull/531/commits/121cc9bb3aef28806acae5c7ff4c19a32faf5e7a), it exposes other issues, that are addressed in these commits: https://github.com/lede-project/source/pull/531/commits/e081fd4d073f0b9b7142f83452f572657029abda and https://github.com/lede-project/source/pull/531/commits/496a05404bc39390e04a17f0d8fd2014d97390ab

Not sure, if it's worth fixing this hassle [with grub2] as I addressed it in this PR.
Or whether the way I addressed the issue with the host-side build are completely corrects/sane.

------

Initial PR message is below:

~~The host-side build of grub2 requires this sometimes.~~
~~This will re-generate the ./configure script from configure.ac.~~
~~I don't know the conditions of how this reproduces, it just~~
~~sometimes appears, and sometimes doesn't.~~

~~Build error~~
```
<lede-dir>/build_dir/target-x86_64_musl-1.1.15_yogi/host/grub-2.02~beta2/build-aux/missing: line 81:  aclocal-1.14: command not found
WARNING: 'aclocal-1.14' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
Makefile:3962: recipe for target 'aclocal.m4' failed
```

~~Adding PKG_FIXUP adds sanity (i.e. autoreconf is used for host & target~~
~~builds) over just using HOST_FIXUP.~~

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by blogic** [comment]
merged, Thanks !

**Comment by commodo** [comment]
@blogic 

seems i broke the build with this one ; 
though the err I'm getting is different than on build bot: https://downloads.lede-project.org/snapshots/faillogs/x86_64/base/grub2/host-compile.txt

seems that `PKG_FIXUP:=autoreconf` on grub2 is also annoying [and not quite deterministic]
i'm seeing errs on my LEDE-based build, but I'm not getting any errs on LEDE trunk

i'll try out a few things/options
and i'll spin up some patches to fix this ; 

any objections if i also send an upgrade patch for this ?
grub2.02-beta2 is 3 years old, and there was a release sometime this year

**Comment by blogic** [comment]
yes, al;ready working on a fix

**Comment by commodo** [comment]
so ; i have something that seems to work on my LEDE-based build:
https://github.com/commodo/lede/commits/grub2-fix  (top 3 commits)

I don't have time right now to test whether they build on LEDE (maybe later ;  but tomorrow for sure).
I am not sure if patch: https://github.com/commodo/lede/commit/01c11cd528caf7ef8a202e38bda0b4a8306534d2  applies on grub2.02-beta2 (chances are it does)

On my build, I also updated the `gettext-full` build, which was broken [also on LEDE] before I touched this.

**Comment by commodo** [comment]
@blogic 
re-spinned this PR;
and PR comment;

**Comment by nbd168** [comment]
Merged to my staging tree, thanks

**Pull request closed without merging**
