### PR TITLE
x86: automate building UEFI bootable images

### PR DESCRIPTION
**Pull request by alive4ever**
This is a WIP.
Working: UEFI bootable ext4 image.
Not working: UEFI bootable squashfs image.
Not tested: ISO and ramdisk image.

The resulting image is located inside ./bin/target/x86/ for TARGET_x86_64_efi and ./bin/target/x86/efi for TARGET_x86_efi.

### CODE REVIEW

**Comment by nbd168** [comment]
Please don't add more subtargets for EFI. The normal ones should be able to handle adding EFI support just fine. If they need extra kernel config options, just enable them.

**Comment by alive4ever** [comment]
Thanks for the review. I'll create another branch that makes use of profile instead of subtarget.

**Comment by nbd168** [comment]
Please also don't use profiles for it. I think EFI and non-EFI builds should be done in one build run

**Comment by alive4ever** [comment]
New PR has been submitted, with no new profiles nor subtargets.

**Pull request closed without merging**
