### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by D-Albers**
Remove subversion as dependency

### CODE REVIEW

**Comment by BEA3CCCE** [comment]
correct

**Comment by mkresin** [comment]
Your commit has formal issues. Please have a look at [draft version of the github submission guidelines](https://github.com/bobafetthotmail/source/blob/68913cbafbd7b16f9819c5b29db3cda307a79b30/.github/pull_request_template) and the [generic submission guidelines](https://lede-project.org/docs/guide-developer/the-source-code#submitting_patches).

- no signed of by line
- no commit message
- wrong/missing prefix in commit title

Please have a look at the commit history of the README to have some examples on how to do it the right way.

Please use ```git commit --amend``` to add changes to your commit. Use ```git push --force``` to overwrite your github repository/branch. The PR will afterwards update automatically. Please don't close this PR and open a new one.

**Comment by pepe2k** [comment]
@D-Albers, I'm pretty sure svn is still required, at least for some packages (`PKG_SOURCE_PROTO`).
@mkresin can you confirm?

Cheers,
Piotr

**Comment by mkresin** [comment]
At least for ```tools/upslug2``` svn is still used:

```tools/upslug2/Makefile:PKG_SOURCE_PROTO:=svn```

Most likely some packages in the package feed use svn as well. As long as we have ```DownloadMethod/svn``` in ```include/download.mk``` defined, the reference to subversion should be kept.

**Pull request closed without merging**
