### PR TITLE
kernel: update 4.9 to 4.9.12

### PR DESCRIPTION
**Pull request by Ansuel**
Refresh generic patch

Compiled and tested WRT1900ACS

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Borromini** [comment]
4.9.12 just got released :-)

**Comment by Ansuel** [comment]
@Borromini ...ahahhahahahah wondefull...

**Comment by Ansuel** [comment]
Done update... no need to refresh patch

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
