### PR TITLE
update tools/sparse to support llvm 3.5.0

### PR DESCRIPTION
**Pull request by stsydow**
sparse-0.5.0 won't link against lvm 3.5.0 as  "llvm-config --libs"
does not include system libs like pthreads
This problem got fixed but not released yet, 
so we need to fetch from their git repo.

### CODE REVIEW

**Comment by blogic** [comment]
keeping PKG_VERSION:=0.5.0 seems wrong

**Comment by stsydow** [comment]
How should I call to make the update clear?
The following options come to my mind:
sparse-0.5.0+
sparse-0.5.0-rc1 - but there is no official version
or sparse-0.5.git-40791b94

**Comment by jow-** [comment]
I usually use something like `<baseversion>+git-<shorthash>` e.g. `0.5+git-40791b94`

**Comment by jow-** [comment]
@stsydow - I merged this PR into my staging tree and fixed it up:
 - squashed the two commits into one
 - rewrapped commit message
 - added signed-off-by
 - removed commented lines from makefile

See https://git.lede-project.org/?p=lede/jow/staging.git;a=commitdiff;h=b6e38eeb358d7ef71b140188e617719813c15e13 and tell me whether it is okay.

**Comment by stsydow** [comment]
Thanks, it´s fine!

**Pull request closed without merging**
