### PR TITLE
Ebtables: update to last commit

### PR DESCRIPTION
**Pull request by Ansuel**
Updated Ebtables and refreshed patch 

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by nbd168** [comment]
Please change the makefile to use PKG_SOURCE_DATE instead of PKG_VERSION  and drop PKG_SOURCE + PKG_SOURCE_SUBDIR

**Comment by nbd168** [comment]
Also, please add PKG_MIRROR_HASH (e.g. using make package/ebtables/check FIXUP=1 after you've done the other rework).

**Comment by Ansuel** [comment]
@nbd168 that command didn't give me hash output, anyway now the makefile should be good

**Comment by nbd168** [comment]
that commit still doesn't contain PKG_MIRROR_HASH

**Comment by Ansuel** [comment]
i don't know how to create it... need to put the hash of the download file? cause i think i don't have any mirror for a git repository

**Comment by nbd168** [comment]
I just tested it, running `make package/ebtables/check FIXUP=1` adds the missing hash.
By the way, you also didn't refresh the patches, please run make package/ebtables/refresh as well.

**Comment by Ansuel** [comment]
Ok done it... it was really easy

**Comment by nbd168** [comment]
It's `PKG_MIRROR_HASH:=997a877da02d6e2141e6d31c5d4dd005737facecfdbea07308c0e1286db8591c`

**Comment by Ansuel** [comment]
Yep, didn't know that if you add empty string and then do that command it autocomplete it

**Comment by Ansuel** [comment]
It's good now

**Comment by nbd168** [comment]
You forgot to remove PKG_SOURCE

**Comment by Ansuel** [comment]
Done, sorry for all this mess

**Comment by nbd168** [comment]
It seems that you still didn't refresh the patches

**Comment by Ansuel** [comment]
@nbd168 looks like we don't need a refresh, they apply on my side

**Comment by nbd168** [comment]
They apply with offsets (and fuzz), so they should be refreshed even though they apply

**Comment by Ansuel** [comment]
I finally refreshed the patch and i notice a little typo in the makefile about ebtables-utils

**Comment by nbd168** [comment]
Actually, that wasn't a typo. The code is fine the way it is, so please change it back.

**Comment by Ansuel** [comment]
Really? then sorry can i ask an explaination?

**Comment by Ansuel** [comment]
Done

**Comment by nbd168** [comment]
DEPENDS += ebtables means append 'ebtables' to the existing DEPENDS variable (which is inherited from the ebtables package.
Technically, appending isn't necessary, since by depending on ebtables, it will inherit its dependencies as well.
Not using + is intentional, because that makes ebtables-utils visible only if ebtables is selected

**Comment by nbd168** [comment]
Merged to my staging tree, thanks.

**Pull request closed without merging**
