### PR TITLE
ramips: Add support for Phicomm K2 PSG1218

### PR DESCRIPTION
**Pull request by Biercenter**
- CPU: MT7620A 580MHz
- Flash: 8MB
- RAM: 64MB
- External PA+LNA on both WLAN2.4 and WLAN5
- 4x LAN ethernet and 1x WAN ethernet

Signed-off-by: xuefu lin <xuefulin@gmail.com>

### CODE REVIEW

**Comment by bobafetthotmail** [comment]
Signed-off-by is still wrong, you must write your real name, not the nickname.

**Comment by Biercenter** [comment]
@bobafetthotmail if I write my real name, display invalid-email-address.

**Comment by Biercenter** [comment]
@bobafetthotmail I rewrite the coment. thanks.

**Comment by bobafetthotmail** [comment]
Ok, that is good, but you still need to fix the commit's Signed-off-by line.

**Comment by 981213** [comment]
In fact this dts could share a lot of code with the PSG1208 one like what the dts of lenovo Y1 and Y1S have done.

**Comment by Biercenter** [comment]
understood, thanks!

**Pull request closed without merging**
