### PR TITLE
ipq40xx: add support for the Compex WPJ428

### PR DESCRIPTION
**Pull request by mehlis**
hardware highlights:
    
 SOC:    IPQ4028 / QCA Dakota
 CPU:    Quad-Core ARMv7 Processor rev 5 (v7l) Cortex-A7
 DRAM:   256 MiB DDR3
 NOR:    32 MiB MX25L25635
 ETH:    Qualcomm Atheros QCA8075 Gigabit Switch (1 x WAN Port 0 with PoE, 1 x LAN)
 USB:    1 x 3.0 (via Synopsys DesignWare DWC3 controller in the SoC, Optional)
 USB:    1 x 2.0 on the M.2 (NGFF) "B Key" Socket for 4G Module
 WLAN1:  Qualcomm Atheros QCA4028 2.4GHz 802.11bgn 2:2x2
 WLAN2:  Qualcomm Atheros QCA4028 5GHz 802.11a/n/ac 2:2x2
 INPUT:  RESET Button
 LEDS:   Power, Status, Flash, ...
 MISC:   GPIO Buzzer
 
 tested and working:
            Ethernet
            Wifi
            USB 2.0
            LEDs
            Buzzer
            Reboot button
    
 not working:
            Reboot
            USB 3.0
    
 not tested:
            Flash
            Sysupgrade
   
 ramload:
            tftpboot lede-ipq806x-WPJ428-initramfs-fit-uImage.itb
            bootm

Signed-off-by: Christian Mehlis <christian@m3hlis.de>

### CODE REVIEW

**Comment by mehlis** [comment]
THis PR includes one commit from Ram Chandra Jangir <rjangir@codeaurora.org> for basic support to the QCA DK01 and DK04 ref boards. This support is nessary for Copex WPJ428 to have working USB.

The commit by Ram is discussed on LEDE mailing list but not merged jet!

**Comment by blogic** [comment]
@mehlis i merged the latest version of rams patches. please rebase this PR ontop of those patches.

**Comment by blogic** [comment]
@mehlis no feedback in several months. please reopen, once you rebased the PR

**Comment by ita93** [comment]
Hi, after run make command, I got a .bin image, How can i flash it by using uboot? Can you guide me. Thank you very much

**Comment by huzhifeng** [comment]
@mehlis 

No `lede-ipq806x-WPJ428-initramfs-fit-uImage.itb` found under `bin/targets/ipq806x/generic`, 

```
config.seed
lede-ipq806x-device-wpj428.manifest
lede-ipq806x-squashfs-root.img
lede-ipq806x-ubifs-root.img
lede-ipq806x-vmlinux.elf
lede-ipq806x-WPJ428-squashfs-sysupgrade.bin
lede-ipq806x-WPJ428-ubifs-sysupgrade.bin
packages
sha256sums
```

Can you describe the upgrade step in detail?

Thanks

**Comment by ita93** [comment]
@huzhifeng 
If you want to get itb image, you need to enable Ramdisk image:
make menuconfig
->Target Images -> Ramdisk

**Comment by huzhifeng** [comment]
@ita93 

Thank you so much

**Pull request closed without merging**
