### PR TITLE
ppp: add pppoe-discovery to ppp-mod-pppoe package

### PR DESCRIPTION
**Pull request by feckert**
Signed-off-by: Florian Eckert <Eckert.Florian@googlemail.com>

### CODE REVIEW

**Comment by jow-** [comment]
Whats the size of this extra executable?

**Comment by nbd168** [comment]
Also, what's the reason for this change? The commit message is a 'little' vague

**Comment by jow-** [comment]
Well I can see the use case (discovering PPPoE service announcements similar to how e.g. debian does it) but considering the fact that our current space situation already is severe and that ppp-mod-pppoe is a core package I tend to NAK this.

I have no issues with packaging this utility separately but the decision on whether to include it by default depends on the size it takes up...

**Comment by Ansuel** [comment]
What are the benefits of having this?

**Comment by feckert** [comment]
@nbd168 @Ansuel this tool is used to debug pppoe http://man.he.net/man8/pppoe-discovery
@jow- i would packaging it separately as you suggest. It think this is only selectable if ppp-mod-pppoe is selected?

**Comment by jow-** [comment]
@feckert - no, packages will be selectable independently

**Comment by feckert** [comment]
@jow-  Sorry for the misunderstanding. I would package pppoe-discovery like chat, pppdump or pppstats.

**Comment by dedeckeh** [comment]
Pulled into my staging tree with a small grammatical change (https://git.lede-project.org/?p=lede/dedeckeh/staging.git;a=commit;h=a21e79487ee5fd670708acbd230da51386ac892f).
Including the pppoe-discovery package by default in the build makes no sense imho
Thx

**Pull request closed without merging**
