### PR TITLE
mwlwifi: update to version 10.3.4.0 / 2017-08-10

### PR DESCRIPTION
**Pull request by anomeome**
Update mwlwifi to latest, tested on mamba

Signed-off-by: Kabuli Chana <newtownBuild@gmail.com>

### CODE REVIEW

**Comment by thagabe** [comment]
Tested on Rango works great! Let's merge!

**Comment by starcms** [comment]
Tested on caimen.  Merge!

**Comment by anomeome** [comment]
Seems some are experiencing issues with version [10.3.4.0-20170810](https://github.com/kaloz/mwlwifi/issues/198)

**Comment by AjkayAlan** [comment]
> Seems some are experiencing issues with version 10.3.4.0-20170810

The issue I am trying to help solve has been one which has existed for me since I bought a Rango (WRT3200ACM v1) in May. I don't think it should be a show stopper for you to merge, as there is not a big difference between the prior version versus this version for me.

**Comment by starcms** [comment]
There are no new issues in 0810 (this latest version) that haven't always been there.  Only additional fixes.  It should be merged.

**Comment by tapper82** [comment]
merge pleas.

**Comment by starcms** [comment]
This should be merged.  It has been out for a few weeks now and widely tested on all WRT1200/1900/3200 variants.  It is working great and has fixed issues that existed before.  No new issues were introduced.

**Comment by danielpetre** [comment]
+1 for my wrt1900acsv2 please :)

**Comment by tapper82** [comment]
+1

**Comment by hauke** [comment]
Thank you, this was merged into LEDE master.

**Comment by mkresin** [comment]
This commit causes build errors for targets using kernel 4.4

> /home/buildbot/slave-lede-local/malta_le/build/build_dir/target-mipsel_24kc_musl/linux-malta_le/compat-wireless-2017-01-31/drivers/net/wireless/intel/iwlwifi/mvm/fw-dbg.c:857:3: error: implicit declaration of function 'dev_coredumpsg' [-Werror=implicit-function-declaration]

by using the function dev_coredumpsg() which was introduced with kernel 4.7.

Please send a fix! Otherwise we need to revert the commit.

**Comment by mkresin** [comment]
Please disregard the comment. mwlwifi != iwlwifi.

**Comment by hauke** [comment]
This problem was fixed by 1b2c93988f59 it was not caused by mwlwifi

**Pull request closed without merging**
