### PR TITLE
package/utils/e2fsprogs: Update to 1.43.3

### PR DESCRIPTION
**Pull request by diizzyy**
Updates e2fsprogs to 1.43.3

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
Compile tested on ar71xx

**Comment by blogic** [comment]
please runtime test code after updating it.

**Comment by diizzyy** [comment]
Sure, I'm planning to do that tonight.

**Comment by diizzyy** [comment]
Runtime tested on ar71xx

**Comment by lynxis** [comment]
LGTM

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
