### PR TITLE
kernel: bump to 4.4.38

### PR DESCRIPTION
**Pull request by kdarbyshirebryant**
Bump & refresh patches for all 4.4 supported targets.

Compile & run tested: ar71xx - Archer C7 v2

Signed-off-by: Kevin Darbyshire-Bryant <kevin@darbyshire-bryant.me.uk>

### CODE REVIEW

**Comment by thagabe** [comment]
Checks out with mvebu.

**Comment by mkresin** [comment]
Are that changes identical to http://patchwork.ozlabs.org/patch/704827/?

**Comment by kdarbyshirebryant** [comment]
No they're not identical.  Stijn uses a sha256sum for the checksum, probably a good idea but inconsistent with the other entries.

Also I have a minor 'line number' bump for 1 patch in layerscape target which he does not have at all.

**Comment by blogic** [comment]
can you provide a PR with extra line number bump and sha256 please ?

**Comment by blogic** [comment]
merged, Thanks !

**Pull request closed without merging**
