### PR TITLE
lede-17.01: backport from Master: odhcpd: update to git HEAD version

### PR DESCRIPTION
**Pull request by bladeoner**
Backport from Master Branch.
Compile & run tested: ar71xx Netgear WNDR4300

Changes/Fixes:
f0bce9c dhcpv4: fix memset compile issue
0ba3278 dhcpv4: rework assignment lookup
e3b49f3 dhcpv4: cleanup dhcpv4_test usage
47fe122 dhcpv4: rework lease expire handling logic
028ab85 dhcpv4: force renew nonce authentication support
a827fca dhcpv4: avoid segfault when there's no IPv4 prefix
bea088b ndp: detect ifindex changes via interface netlink events
f66103e ubus: display accept reconf status for DHCPv6 assignments
f0e354b treewide: replace RELAYD prefix naming in macros
1a313f9 dhcpv4: fix possible segfault when lease is not created
e2d6eb4 dhcpv4: dhcpv4: move interface lease list insertion out of dhcpv4_assign
94e65ee ndp: use IPv4 address list when comparing IPv4 addresses
ff5020d dhcpv6-ia: rework reconfigure accept logic
296b4a0 dhcpv6: assign all viable DHCPv6 addresses by default (FS#402, FS#524)
f4d38e0 treewide: reflect managed mode is related to RA
f0d78e7 ndp: optimize check_addr6_updates code
94afe3b ndp: fix syslog tracing for netlink neigbor and address events
18df6cc treewide: rework logic to retrieve IPv6 interface addresses
803b83e router: use enum to specify order and index of iov struct
5dad295 treewide: rework code to get rid of fixed IPv6 address arrays
3e4c8ad config: rework code to get rid of IFNAMSIZ usage
ab7813e treewide: use angle-brackets to include libubox header files
93abe6f config: fix invalid hoplimit in RA message
2ae08d1 config: fix invalid retranstime in RA message
0005cb4 config: fix invalid reachabletime in RA message
5683dd2 config: limit ra_mtu to 65535
f8d40a5 router: fix interface mtu read error
f8f4b87 config: limit ra_retranstime to 60000
a2d8bf6 dhcpv4: display two hex digits per octet in syslog
a9e9bc4 config: make RA retransTime configurable via uci
2cb6b48 config: make RA reachableTime configurable via uci
e4504db config: make RA curHopLimit configurable via uci
9dd5316 config: make RA mtu configurable via UCI
29cb2ff config: fix dhcpv4 server being started
0ef74ec ndp.c: add switch/case fallthrough comments

Signed-off-by: Etienne Haarsma <bladeoner112@gmail.com>

### CODE REVIEW

**Comment by dedeckeh** [comment]
@bladeoner Is there a specific reason why you want to update odhcpd in lede-17.01 branch to the git HEAD version ?
The policy on the stable branch is to backport bug fixes but we rather avoid an update to the git HEAD version for stability reasons

**Comment by mkresin** [comment]
Not the contributor, but I'm especially interested in:

-  296b4a0 dhcpv6: assign all viable DHCPv6 addresses by default (FS#402, FS#524)

Albeit FS#402 is flagged as feature request, I do consider it as bug.

Might be specific to my configuration where dnsmasq runs at authoritative dns server, to allow me to resolve the GUA IPv6 address of internal clients, which doesn't work without this patch.

**Comment by dedeckeh** [comment]
@mkresin I agree this commit will fix end user issues; I will look into creating a lede-17.01 for odhcpd as was done for procd.

**Comment by bladeoner** [comment]
@dedeckeh there is not a specific reason. I just saw it was a while a go that odhcpd was updates so I just wanted to help put with this PR. 

Thank you for clarifying on why not update the stable branch to the latest git HEAD.

**Pull request closed without merging**
