### PR TITLE
brcm2708: fix failing hunk in patch 0050

### PR DESCRIPTION
**Pull request by ikstream**
This fixes the not applying hunk for the brcm2708 target

Signed-off-by: Stefan Venz <stefan.venz@protonmail.com>

### CODE REVIEW

**Comment by ConorOG** [comment]
You need to fix your quilt settings https://wiki.openwrt.org/doc/devel/patches

**Comment by jow-** [comment]
Will take care of refreshing the patch.

**Comment by jow-** [comment]
Nvm, @Noltari already staged a fix at https://git.lede-project.org/?p=lede/noltari/staging.git;a=commitdiff;h=65ae9db41ab70f496dbfbdb26a76952aa42d8ddf

**Comment by Noltari** [comment]
oops, I hadn't seen this...
Anyway, it's fixed now.
Thanks!

**Pull request closed without merging**
