### PR TITLE
ar71xx: Add support for A40/A60 and OM2Pv4/OM2P-HSv4

### PR DESCRIPTION
**Pull request by ecsv**

### CODE REVIEW

**Comment by blogic** [comment]
huge series, i had a quick skim over the patches, it looks like these only touch OM related code paths ?

**Comment by ecsv** [comment]
Yes, it is expected to only touch OM specific code paths. The files which contain non-OM specific code are either changes which are only touching OM specific sections or only add the OM specific identifiers to some switch-case blocks

**Comment by blogic** [comment]
thanks for the quick reply, i'll try to review this after lunch.

**Comment by blogic** [comment]
merged, Thanks !

please open a new PR if you want this lot backported to the lede-17.01 branch

**Comment by ecsv** [comment]
@blogic My PR #775 about the backport was already rejected and I was told that I should not open a backport PR.

**Pull request closed without merging**
