### PR TITLE
Utilize HTTPS urls when downloading sources

### PR DESCRIPTION
**Pull request by g4jc**
Multiple source mirrors in download.pl are using insecure protocols (such as HTTP and FTP), this pull request updates all the urls to utilize HTTPS.

### CODE REVIEW

**Comment by diizzyy** [comment]
This is a bad idea, we provide all protocols because of compatibility and all mirrors have been carefully evaluated in terms of peering, availability and where users are (in general) actually located.

**Comment by alive4ever** [comment]
I prefer upgrading mirrors with ftp protocol to use http protocol instead.

Regarding use of https protocol, this will add `ca-certificates` dependency to the host to perform certificate validation.

**Comment by bobafetthotmail** [comment]
I also prefer http to ftp because it's not uncommon for firewalls to block ftp while they rarely block http. 
I'd say https is irrelevant because the download is checksummed and checked anyway after download so any tampering will be detected.

> Regarding use of https protocol, this will add ca-certificates dependency to the host to perform certificate validation.

Is that even an issue? Or, are there linux distros where it isn't installed by default already?

**Comment by diizzyy** [comment]
HTTPS is going to preferred over HTTP and FTP due to security, MITM attacks etc and privacy.
We're not going to drop HTTP and FTP but they do have lower priority than HTTPS.

I've been very careful to make sure that we **NOT** run into certificates issues and since we did this change several months ago I'd say that I manage to do that successfully while trying to please everyone. FWIW, there has been a lot less complaints about speeds and missing tarballs etc since the change. :-)

**Comment by alive4ever** [comment]
If we want to use `https` for downloading sources, let's do it right. Let the download tools perform necessary certificate validation by removing `curl`'s `--insecure` switch and `wget`'s `--no-check-certificate`.

```
      perl

	return $have_curl
		? (qw(curl -f --connect-timeout 20 --retry 5 --location --insecure), shellwords($ENV{CURL_OPTIONS} || ''), $url)
		: (qw(wget --tries=5 --timeout=20 --no-check-certificate --output-document=-), shellwords($ENV{WGET_OPTIONS} || ''), $url)
	;
```

**Comment by diizzyy** [comment]
@alive4ever 
I fully agree on that one, however I think that might be an issue on platform where packages are several years old in general (such as Debian) which may cause failure on several levels esp when it comes to the packages repo.

**Comment by alive4ever** [comment]
> I think that might be an issue on platform where packages are several years old in general (such as Debian)

Debian oldstable and old-oldstable can just fetch the latest `ca-certificates` from `stable` or `testing` and install the package manually. Or even better, persuade Debian developers to add `ca-certificates` to security updates so it will be updated whenever there is a newer bundle from Mozilla.

A half-baked resource fetching method from `https` servers without  certificate verification doesn't comply with [RFC5280](https://tools.ietf.org/html/rfc5280#section-3.2).

Let's do `https` downloading right!

**Comment by diizzyy** [comment]
@alive4ever 
It is valid as 2014 / 2014 is really old :-/

**Comment by alive4ever** [comment]
For this change to be accepted, you must really sure that those download mirrors will keep maintaining support for https. Have you contacted the mirror maintainers on your changes regarding their commitment to support https?

>  It is valid as 2014 / 2014 is really old :-/

Debian oldoldstable is still supported, so it will work as expected.
What are recent CAs that have been added? [Amazon](https://aws.amazon.com/blogs/aws/new-aws-certificate-manager-deploy-ssltls-based-apps-on-aws/)? Lets Encrypt?

Those new CAs have their root cross-signed by other trusted CA, so that _old_ supported system such as Debian oldoldstable will be able to verify the certificate chain without any issue.

Regarding `--insecure` and `--no-check-certificate` removal, a new pull request should be made, since it's unrelated to this issue.

**Comment by diizzyy** [comment]
Someone(tm) should provide a full buildlog with those switches removed, I still think it's a very bad idea to just enforce HTTPS and change mirrors to rather dubious ones.

**Comment by alive4ever** [comment]
After carefully reading this pull request, the mirror ordering is representing protocol fallback.

Downloader tools will use `https` mirrors on the first try. When `https` mirror can't be reached, fallback to `http` mirrors. If `http` can't be reached, fall back to `ftp` mirrors.

I think there is no need to change the mirror ordering for now.

**Comment by diizzyy** [comment]
Indeed, I also submitted a pull request to push this approach further.
https://github.com/lede-project/source/pull/1133 + https://github.com/lede-project/source/pull/1189

**Comment by victoredwardocallaghan** [comment]
Given today's environment I cannot understand why this is even debatable any more. We absolutely *must* pull source over a secure channel exclusively and drop mirrors that don't provide this until they are fixed to do so.

**Comment by diizzyy** [comment]
@victoredwardocallaghan 
I'm not sure if you even realize that it's not a viable option no matter how much you want it.
We have several packages where the code is hosted on non HTTPS hosts, while the pull reqs above does increase the amount of "trusted" hosts far from everything is going to be available. Apart from that doing fallback to HTTP and/or FTP is a sane tradeoff, in most cases you have at least two HTTPS hosts and if both fails then I'd say that something is broken on the client end.

**Comment by bobafetthotmail** [comment]
@victoredwardocallaghan the source packages used by LEDE are checksummed and the communication is mostly one-way with no password exchange.
If there are man-in-the-middle attacks (or if the mirror is providing bogus files) the package will fail the checksum check and be discarded.

**Comment by victoredwardocallaghan** [comment]
@bobafetthotmail not all hashes are made equal, beyond that, hashing is *not* a complete cryptographic validation of authenticity as one can craft payloads to collide in the hashes co-domain. The purpose of the hash is to check for file corruption not authenticity! Additionally, this isn't about passwords in transit obviously so I don't see why you even say that. The problem is malware/backdoors/<insert-bad-stuff> being crafted into src tarballs while in transit.

@diizzyy It is viable if we make steps to make it viable - reducing the attack surface is a solid start. It is clear this should be a on going project to resolve this as swiftly as possible over the coming months. Mirrors that cannot be fixed for whatever reason should have their tarballs gpg signed and checked at download time.

**Comment by diizzyy** [comment]
@victoredwardocallaghan 
Yeah... I wish you the best of luck really

**Comment by bobafetthotmail** [comment]
> not all hashes are made equal, beyond that, hashing is not a complete cryptographic validation of authenticity as one can craft payloads to collide in the hashes co-domain. 

I wish them luck in doing that with SHA256 hashing (which is what is being used in LEDE to check the tarballs). MD5 was phased out shortly after the LEDE split. Still available for compatibility with community package repos but not used for core packages.

**Comment by diizzyy** [comment]
I think we can close this, 

* Downloads won't be HTTPS only because of practical reasons (far from all projects host their files on HTTPS capable hosts)

* Moving towards this (or at least more HTTPS enabled downloads) got rejected because it's no within the project. https://github.com/lede-project/source/pull/1133 + https://github.com/lede-project/source/pull/1189
Hosting everything within the project is just insane and will mean even more work and infrastructure.

* There are no defined host system requirements and I think there's a general desire to have as few requirements as possible as far as installed software goes meaning that old systems will fail because of outdated certificates. 

To my knowledge there are no distros who does this which would help looking at how they practically handling this?

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Pull request closed without merging**
