### PR TITLE
ar71xx: archer C7: change reset button to reset function

### PR DESCRIPTION
**Pull request by heinzek**
Changed button description.
This router have only one button named Reset/WPS.
Reset/restart function is more important as WPS.

Signed-off-by: Henryk Heisig <hyniu@o2.pl>

### CODE REVIEW

**Comment by pepe2k** [comment]
@heinzek, there are also other devices with same "problem", e.g. TL-WDR3600/43x0, what with them? IMHO, we should be consistent in this subject.

Cheers,
Piotr

**Comment by heinzek** [comment]
Great idea. I change this in TL-WDR3600/43x0 and set proper button description.

**Comment by diizzyy** [comment]
I'm going to say no here because it doesn't make any sense.
If you want to reset/restart your router just pull the plug or (if available) use the hardware power switch. You can't replace the WDS button with pulling the plug.

**Comment by pepe2k** [comment]
> I'm going to say no here because it doesn't make any sense.
> If you want to reset/restart your router just pull the plug or (if available) use the hardware power switch. You can't replace the WDS button with pulling the plug.

We use reset button [not only for rebooting the device](https://github.com/lede-project/source/blob/master/package/base-files/files/etc/rc.button/reset#L17). For me it's more like a question how we should deal with buttons which have more than one function in vendor's firmware.

Cheers,
Piotr

**Comment by blogic** [comment]
i agree with @pepe2k 
i'll close this in a day or two if there are no other opinions being voiced

**Comment by diizzyy** [comment]
Wait what? Why can't we have a timer based function? Quick press... WPS, long press reset?

**Comment by pepe2k** [comment]
> Wait what? Why can't we have a timer based function? Quick press... WPS, long press reset?

I don't think there is a way to define more than one input event code for a particular GPIO driven button in kernel (correct me if I'm wrong). We could start using a reset button also for wps function, but that might be misleading for users, especially if their devices include separated buttons for these functions (reset and wps).

Cheers,
Piotr

**Comment by heinzek** [comment]
> If you want to reset/restart your router just pull the plug or (if available) use the hardware power switch

You have right but restart function is not the same as turn power on/off. Some device have harddisk or mmc/sd device. When You power off this device you may lose unsaved data.
reboot function use sync command before reboot device.

> Wait what? Why can't we have a timer based function? Quick press... WPS, long press reset?

Key restart have timer based function:
0-4 sec = reboot
5-99 sec = reset

add wps option to this button is possible, but i dont known how this change will work on another devices that have separate reset and wps button.

I think this is possble to add:
0-1sec - wps
2-4sec - reboot
5-99sec - reset

**Comment by pepe2k** [comment]
If there are no other comments, I would prefer to close this PR. There is [ongoing discussion on the mailing list](http://lists.infradead.org/pipermail/lede-dev/2017-February/006134.html) about possible solution/s for multi-function buttons.

Cheers,
Piotr

**Comment by heinzek** [comment]
OKAY. I'll be waiting.

**Pull request closed without merging**
