### PR TITLE
kernel: bump 4.9 to 4.9.14

### PR DESCRIPTION
**Pull request by Ansuel**
Drop 070 generic patch (pushed upstream), refresh patch

Signed-off-by: Ansuel Smith <ansuelsmth@gmail.com>

### CODE REVIEW

**Comment by Ansuel** [comment]
Compiling for testing right now...

**Comment by nbd168** [comment]
Only parts of patch 070 were applied, not all of it. Please only drop the get_devce/put_device related chunks, not all of it.

**Comment by Ansuel** [comment]
@nbd168 ok sorry 
should be good now (don't know if it applyies with offset... think not)

**Comment by nbd168** [comment]
It looks like you've reverted a change to 702-phy_add_aneg_done_function.patch, please fix

**Comment by nbd168** [comment]
If you want to make sure that there are no patch offsets, just run make target/linux/refresh. Please do this with every platform that uses 4.9

**Comment by Ansuel** [comment]
@nbd168 i know but i'm recompiling all the toolchain and stuff at the moment and i can't do it
 
fixed 702 patch

**Pull request closed without merging**
