### PR TITLE
add support for TP-Link 882 886 941nv7 6300v2

### PR DESCRIPTION
**Pull request by am2dk**
add support for TP-Link 882 886 941nv7 6300v2
which already be issued at http://www.right.com.cn/forum/thread-179557-1-1.html

Support TP-Link 882/886
Qualcomm Atheros TP9343 rev 0 750 MHz
64MB DDR1 400 MHz
8MB SPI Flash
802.11a/na/b/g/ng
GPIO x 18,
10/100 Ethernet
20dBm, Optional Onboard Antenna
DC Input, 8.5V DC

Support TP-Link 941nv7
QCA9558 720MHz
64MB DDR1 400 MHz
8MB SPI Flash
802.11a/na/b/g/ng
GPIO x 16,
10/100 Ethernet
20dBm, Optional Onboard Antenna
DC Input, 8.5V DC

Support TP-Link 6300v2
AR9344 600MHz
64MB DDR2 400 MHz
8MB SPI Flash
802.11a/na/b/g/ng/ac
GPIO x 20,
10/100 Ethernet
20dBm, Optional Onboard Antenna
DC Input, 9V DC

So I just want to merg my code into lede to help anyone.
Signed-off-by: Xiang Wang 347006777@qq.com

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello @am2dk,

Please, take a look at the submission rules and follow them:
https://lede-project.org/docs/guide-developer/the-source-code#submitting_patches

Cheers,
Piotr

**Comment by am2dk** [comment]
Yeah I add some inform in this.

**Comment by mkresin** [comment]
@am2dk It is impossible to review your PR and it can not be merged as it is. All your commits have the same commit title and do not have a commit message which describes what the are for. Furthermore, they are wrong organised.

Please add a single commit for each board you are adding support for. Please have a look at the [pull request template draft](https://github.com/bobafetthotmail/source/blob/c7cfdff4fa40f53511b8c8a4bd2e60aa980dc6fd/.github/pull_request_template) as well for informations how it should look like.

**Comment by pepe2k** [comment]
@am2dk it still doesn't look correct and it definitely won't be accepted.

There are already many examples of how it should be done, please take a look how it was done by other contributors: eb97f41fc23ffbd6635b402d6e0bbd8e8ef029bb, e39dc8d823c86559eedbbdcee5f5c14b827fed0f, 261415a660c12a5673fe3d48dabaf677e1d5c32c, 274546046de47883031d8279fdc60856517fb263, d38ffd8cd916ac23e4247816ab3f4575bd036566, eb97f41fc23ffbd6635b402d6e0bbd8e8ef029bb

**Comment by am2dk** [comment]
I have definited all changes yet.

**Comment by mkresin** [comment]
No, it is still wrong. One commit per board and this commit should include everything that is required to add support for this board. At the moment you have 44 commits where multiple commits are touching the same file over and over again.

For example, [this commit ](https://github.com/lede-project/source/pull/759/commits/2752a5bfe940a7455fa6ffa1b0b38b360903b66c) can be dropped. It doesn't do anything beside adding a blank line. There are more such commits. Drop them!

[This commit](https://github.com/lede-project/source/pull/759/commits/b58f75402e9717d0b152cd231f110b622b7c7490) adds stuff for multiple boards, which is wrong.

Would should be at the commits tab in the end is:

- "ar71xx: add support for tl-wdr6300-v2" containing all additions/changes related to the tl-wdr6300-v2
- "ar71xx: add support for tl-wr941nd-v7" containing all additions/changes related to the tl-wr941nd-v7
- "ar71xx: add support for tl-wr882n-v1" containing all additions/changes related to the tl-wr882n-v1
- "ar71xx: add support for tl-wr886n-v5" containing all additions/changes related to the tl-wr886n-v5

The commits creating tplink-wmac.* should be merged into a single commit. The commit message should explain what you are doing and why it is required.

Be prepared to do more of this reorganisation stuff. I have not checked all commits yet.

**Pull request closed without merging**
