### PR TITLE
kernel: Fix commit a5922f6

### PR DESCRIPTION
**Pull request by diizzyy**
Add kmod-mmc as dependency and only build this if platform is mvebu

Signed-off-by: Daniel Engberg <daniel.engberg.lists@pyret.net>

### CODE REVIEW

**Comment by diizzyy** [comment]
@hauke  @heinzek 
This should fix the buildbots

**Comment by mkresin** [comment]
Please fix you commit title. `kernel: btmrvl: add mmc dependency` describes what you are doing. Reference the commit you fix in the commit message.

IMHO this module should not have a dependency on mvebu. The kernel helptext says:

> This driver is required if you want to support Marvell Bluetooth devices, such as 8688/8787/8797/8887/8897/8997.

At least the 88W8897 is used on a  Azurewave AW-CB178NF, which is a M.2 module and can be used on more that the mvebu platform.

**Comment by mkresin** [comment]
@hauke made the requested changes and merged the commit. Thanks!

**Comment by diizzyy** [comment]
@mkresin 
In theory indeed but that's probably unlikely to occur in the end? It was just a quick attempt to avoid building it for several platforms where it's never going to be used. Either way, we have working buildbots now. :-)

**Pull request closed without merging**
