### PR TITLE
ar71xx: add support for Buffalo WZR-450HP2D

### PR DESCRIPTION
**Pull request by majik-sheff**
The WZR-450HP2D is a derivative of the WZR-450HP2 with more LEDs and a different ordering for the LAN ports.

Specifications:
- QCA 9558 720 MHz
- 128 MB of RAM
- 16 MB of FLASH
- UART  header on PCB (unpopulated)
- 5x 10/100/1000 Mbps Ethernet
- 2.4 GHz B/G/N
- 3x external, detachable antennas
- 7x LED, 1x button, 1x toggle switch

Signed-off-by: Tim Thorpe <timfthorpe@gmail.com>

### CODE REVIEW

**Comment by pepe2k** [comment]
Hello @majik-sheff,

Please, read our [submitting patches rules](https://lede-project.org/submitting-patches), and make sure your patch or pull request follows them.

Cheers,
Piotr

**Comment by majik-sheff** [comment]
Added the signed off line.  Was there anything else I missed?

Thanks for the patience,

Tim

**Comment by pepe2k** [comment]
Hello @majik-sheff,

Your commit still doesn't contain proper SoB line, description and prefix in the title. Your PR includes two additional `merge` commits with are incorrect, please rebase on current master branch instead and force push to update your branch.

Also, please don't include support for boards in `legacy` building code (files: `ar71xx/image/legacy-devices.mk` and `ar71xx/image/legacy.mk`). Please, include building code for your board in `generic` building code.

Cheers,
Piotr

**Comment by pepe2k** [comment]
Hello @majik-sheff,

I'm closing your PR due to inactivity.
Please, reopen it if you have time to fix the outlined issues.

Cheers,
Piotr

**Pull request closed without merging**
