### PR TITLE
build: move HOST_BUILD_PREFIX to rules.mk

### PR DESCRIPTION
**Pull request by commodo**
`HOST_BUILD_PREFIX` is defined as:
```
HOST_BUILD_PREFIX:=$(if $(IS_PACKAGE_BUILD),$(STAGING_DIR)/host,$(STAGING_DIR_HOST))
```

Which looks like a short-hand for all 3 vars (IS_PACKAGE_BUILD, STAGING_DIR & STAGING_DIR_HOST)
and all 3 are defined in rules.mk
So, it makes sense to have HOST_BUILD_PREFIX defined moved here as well.

Signed-off-by: Alexandru Ardelean <ardeleanalex@gmail.com>

### CODE REVIEW

**Comment by jow-** [comment]
I am not sure whether any package that uses `HOST_BUILD_PREFIX` also includes `host-build.mk` already.

**Comment by commodo** [comment]
@jow- ; so this patch is more of an RFC to issue https://github.com/openwrt/packages/issues/3430
a quick history on this [in the python changeset]: 
* this change was introduce to python packages: https://github.com/openwrt/packages/pull/3297
* that broke python packages (that depend on python and/or python3) ; but not python & python3
 * it was considered whether to move the HOST_BUILD_PREFIX to rules.mk
 * it was also considered to include host-build.mk in python-package.mk & python3-package.mk which are exported ; this was chosen initially
* the chosen fix [sounds funny, like from Kung Pao [ the movie ] ] ;  fixed python packages, but introduced issue https://github.com/openwrt/packages/issues/3430 ; so now there are 2 ideas:
 * add include guards to mk files (including host-build.mk)
 * revert change that includes host-build.mk in python-package.mk & python3-package.mk + move HOST_BUILD_PREFIX in rules.mk ; this PR is a an RFC for that

**Comment by jow-** [comment]
@commodo - I am preparing some changes to solve this issue, will open a PR against python/python3 in a few minutes

**Comment by commodo** [comment]
superseded by https://github.com/lede-project/source/commit/d7bec5609c6e7408726f455c97d82b2b99d9ef19 & https://github.com/lede-project/source/commit/b7f7e9fe424bc80bf89d3ebb18adcac412e4047f

**Pull request closed without merging**
