### PR TITLE
wwan:  fix ifname handling and fix some shellcheck warnings

### PR DESCRIPTION
**Pull request by feckert**
- If system has more then one and different wwan interface (modem) the wwan protohandler will always take the modem which is discovered first. The protohandler will always setup the same interface. To fix this take configured network ifname to get the associated device.
- fix some shell warning with shell https://github.com/koalaman/shellcheck

### CODE REVIEW

**Comment by blogic** [comment]
all patches are missing the description text

**Comment by feckert** [comment]
@blogic ping

**Comment by feckert** [comment]
@blogic sorry for the additional ping. I know you have a lot to-do!

**Comment by blogic** [comment]
With the remerge in progress, all PRs on the lede-project organisation will be closed. Please help getting this merged or rebase/post it on the openwrt project page (https://github.com/openwrt/openwrt/pulls). All remaining PRs will be closed in 30 days.

**Pull request closed without merging**
