### PR TITLE
ramips: create mt7620 fakeroot image on the fly

### PR DESCRIPTION
**Pull request by jclehner**
This patch removes the static fakeroot uImage required by some
Netgear devices, using `mkimage -s` instead.

Signed-off-by: Joseph C. Lehner <joseph.c.lehner@gmail.com>

### CODE REVIEW

**Comment by mkresin** [comment]
Would it be possible that you move ```Build/append-fakeroot``` to ```include/image-commands.mk``` and "fix" ```target/linux/ipq806x/image/Makefile``` as well. Have a look at ```Build/uImage``` in ```include/image-commands.mk``` for variables you can use.

The ```Build/append-file``` could be dropped afterwards.

**Comment by jclehner** [comment]
Will do.

**Comment by jclehner** [comment]
Done. Updated image code for `ipq806x`,`apm821xx` and `mt7620`. I built images with the old and new code, and they both yield the same result, but I only have an `mt7620` device to test this on.

**Comment by mkresin** [comment]
Hey Joseph,

I've merged a modified version of your PR into my [staging tree](https://git.lede-project.org/?p=lede/mkresin/staging.git;a=summary). Would you please review my changes (if possible runtime test) to make sure that i didn't broke anything!

I will try to find tester for at least one of the changed images in ```ipq806x``` and ```apm821xx```.

I had a look at ```ar71xx``` as well. The netgear images are already using the new build code. But it isn't a fakeroot what they are using. The whole Kernel is in that squashfs partition that has the uImage (filesystem) header.

**Comment by mkresin** [comment]
I received the confirmation that everything is working fine with your patch + my changes on top for the apm821xx/WNDR4700 and ipq806x/R7800.

Only your confirmation for mt7620 is missing.

**Comment by jclehner** [comment]
Confirmed working on `mt7620/EX2700`, sorry for the delay!

**Pull request closed without merging**
